<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>FireSTARR: firestarr::logging::Log Class Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">FireSTARR
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.php');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespacefirestarr.php">firestarr</a></li><li class="navelem"><a class="el" href="namespacefirestarr_1_1logging.php">logging</a></li><li class="navelem"><a class="el" href="classfirestarr_1_1logging_1_1Log.php">Log</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-static-methods">Static Public Member Functions</a> &#124;
<a href="#pri-static-attribs">Static Private Attributes</a> &#124;
<a href="classfirestarr_1_1logging_1_1Log-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">firestarr::logging::Log Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>Provides logging functionality.  
 <a href="classfirestarr_1_1logging_1_1Log.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="Log_8h_source.php">Log.h</a>&gt;</code></p>
<div class="dynheader">
Collaboration diagram for firestarr::logging::Log:</div>
<div class="dyncontent">
<div class="center"><img src="classfirestarr_1_1logging_1_1Log__coll__graph.png" border="0" usemap="#afirestarr_1_1logging_1_1Log_coll__map" alt="Collaboration graph"/></div>
<map name="afirestarr_1_1logging_1_1Log_coll__map" id="afirestarr_1_1logging_1_1Log_coll__map">
<area shape="rect" title="Provides logging functionality." alt="" coords="5,145,153,281"/>
<area shape="rect" title=" " alt="" coords="60,5,99,83"/>
</map>
</div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-static-methods"></a>
Static Public Member Functions</h2></td></tr>
<tr class="memitem:aeae41fa8b4fe6765c7ed57763e293a63"><td class="memItemLeft" align="right" valign="top">static void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1logging_1_1Log.php#aeae41fa8b4fe6765c7ed57763e293a63">output</a> (const char *name, const char *format, va_list *args) noexcept</td></tr>
<tr class="memdesc:aeae41fa8b4fe6765c7ed57763e293a63"><td class="mdescLeft">&#160;</td><td class="mdescRight">Output a message to the log.  <a href="classfirestarr_1_1logging_1_1Log.php#aeae41fa8b4fe6765c7ed57763e293a63">More...</a><br /></td></tr>
<tr class="separator:aeae41fa8b4fe6765c7ed57763e293a63"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aec96e3a1912bbcc22824aee73abb4b14"><td class="memItemLeft" align="right" valign="top">static void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1logging_1_1Log.php#aec96e3a1912bbcc22824aee73abb4b14">setLogLevel</a> (int log_level) noexcept</td></tr>
<tr class="memdesc:aec96e3a1912bbcc22824aee73abb4b14"><td class="mdescLeft">&#160;</td><td class="mdescRight">Set logging level to a specific level.  <a href="classfirestarr_1_1logging_1_1Log.php#aec96e3a1912bbcc22824aee73abb4b14">More...</a><br /></td></tr>
<tr class="separator:aec96e3a1912bbcc22824aee73abb4b14"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a754395053c108ce52922eaee737584b7"><td class="memItemLeft" align="right" valign="top">static void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1logging_1_1Log.php#a754395053c108ce52922eaee737584b7">increaseLogLevel</a> () noexcept</td></tr>
<tr class="memdesc:a754395053c108ce52922eaee737584b7"><td class="mdescLeft">&#160;</td><td class="mdescRight">Increase amount of logging output by one level.  <a href="classfirestarr_1_1logging_1_1Log.php#a754395053c108ce52922eaee737584b7">More...</a><br /></td></tr>
<tr class="separator:a754395053c108ce52922eaee737584b7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a07c9d1bd50a8d2f80fb7d8840008e443"><td class="memItemLeft" align="right" valign="top">static void&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1logging_1_1Log.php#a07c9d1bd50a8d2f80fb7d8840008e443">decreaseLogLevel</a> () noexcept</td></tr>
<tr class="memdesc:a07c9d1bd50a8d2f80fb7d8840008e443"><td class="mdescLeft">&#160;</td><td class="mdescRight">Decrease amount of logging output by one level.  <a href="classfirestarr_1_1logging_1_1Log.php#a07c9d1bd50a8d2f80fb7d8840008e443">More...</a><br /></td></tr>
<tr class="separator:a07c9d1bd50a8d2f80fb7d8840008e443"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2bbec15b677b9f38e8e0cec0ee46d41c"><td class="memItemLeft" align="right" valign="top">static int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1logging_1_1Log.php#a2bbec15b677b9f38e8e0cec0ee46d41c">getLogLevel</a> () noexcept</td></tr>
<tr class="memdesc:a2bbec15b677b9f38e8e0cec0ee46d41c"><td class="mdescLeft">&#160;</td><td class="mdescRight">Get current logging level.  <a href="classfirestarr_1_1logging_1_1Log.php#a2bbec15b677b9f38e8e0cec0ee46d41c">More...</a><br /></td></tr>
<tr class="separator:a2bbec15b677b9f38e8e0cec0ee46d41c"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pri-static-attribs"></a>
Static Private Attributes</h2></td></tr>
<tr class="memitem:a7d7641f9eeef527e7bfba730bab1ffaf"><td class="memItemLeft" align="right" valign="top">static int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1logging_1_1Log.php#a7d7641f9eeef527e7bfba730bab1ffaf">logging_level_</a> = <a class="el" href="namespacefirestarr_1_1logging.php#ae97fef0f2c11153019951e242e28a2de">LOG_DEBUG</a></td></tr>
<tr class="memdesc:a7d7641f9eeef527e7bfba730bab1ffaf"><td class="mdescLeft">&#160;</td><td class="mdescRight">Current logging level.  <a href="classfirestarr_1_1logging_1_1Log.php#a7d7641f9eeef527e7bfba730bab1ffaf">More...</a><br /></td></tr>
<tr class="separator:a7d7641f9eeef527e7bfba730bab1ffaf"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>Provides logging functionality. </p>

<p class="definition">Definition at line <a class="el" href="Log_8h_source.php#l00033">33</a> of file <a class="el" href="Log_8h_source.php">Log.h</a>.</p>
</div><h2 class="groupheader">Member Function Documentation</h2>
<a id="a07c9d1bd50a8d2f80fb7d8840008e443"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a07c9d1bd50a8d2f80fb7d8840008e443">&#9670;&nbsp;</a></span>decreaseLogLevel()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void firestarr::logging::Log::decreaseLogLevel </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span><span class="mlabel">noexcept</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Decrease amount of logging output by one level. </p>
<dl class="section return"><dt>Returns</dt><dd>None </dd></dl>

<p class="definition">Definition at line <a class="el" href="Log_8cpp_source.php#l00030">30</a> of file <a class="el" href="Log_8cpp_source.php">Log.cpp</a>.</p>
<div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="classfirestarr_1_1logging_1_1Log_a07c9d1bd50a8d2f80fb7d8840008e443_cgraph.png" border="0" usemap="#aclassfirestarr_1_1logging_1_1Log_a07c9d1bd50a8d2f80fb7d8840008e443_cgraph" alt=""/></div>
<map name="aclassfirestarr_1_1logging_1_1Log_a07c9d1bd50a8d2f80fb7d8840008e443_cgraph" id="aclassfirestarr_1_1logging_1_1Log_a07c9d1bd50a8d2f80fb7d8840008e443_cgraph">
<area shape="rect" title="Decrease amount of logging output by one level." alt="" coords="5,5,168,47"/>
<area shape="rect" href="classfirestarr_1_1logging_1_1Log.php#a2bbec15b677b9f38e8e0cec0ee46d41c" title="Get current logging level." alt="" coords="216,5,344,47"/>
</map>
</div>

</div>
</div>
<a id="a2bbec15b677b9f38e8e0cec0ee46d41c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a2bbec15b677b9f38e8e0cec0ee46d41c">&#9670;&nbsp;</a></span>getLogLevel()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">int firestarr::logging::Log::getLogLevel </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span><span class="mlabel">noexcept</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Get current logging level. </p>
<dl class="section return"><dt>Returns</dt><dd>Current logging level </dd></dl>

<p class="definition">Definition at line <a class="el" href="Log_8cpp_source.php#l00035">35</a> of file <a class="el" href="Log_8cpp_source.php">Log.cpp</a>.</p>
<div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="classfirestarr_1_1logging_1_1Log_a2bbec15b677b9f38e8e0cec0ee46d41c_icgraph.png" border="0" usemap="#aclassfirestarr_1_1logging_1_1Log_a2bbec15b677b9f38e8e0cec0ee46d41c_icgraph" alt=""/></div>
<map name="aclassfirestarr_1_1logging_1_1Log_a2bbec15b677b9f38e8e0cec0ee46d41c_icgraph" id="aclassfirestarr_1_1logging_1_1Log_a2bbec15b677b9f38e8e0cec0ee46d41c_icgraph">
<area shape="rect" title="Get current logging level." alt="" coords="1285,2083,1413,2124"/>
<area shape="rect" href="namespacefirestarr_1_1logging.php#a4253b6677b26aa72ac4e784e0891af82" title="Log with DEBUG level." alt="" coords="1100,739,1212,780"/>
<area shape="rect" href="classfirestarr_1_1logging_1_1Log.php#a07c9d1bd50a8d2f80fb7d8840008e443" title="Decrease amount of logging output by one level." alt="" coords="1075,2200,1237,2241"/>
<area shape="rect" href="namespacefirestarr_1_1logging.php#aa744a6caeb1cf6e09066cc5bd79af369" title="Log with ERROR level." alt="" coords="1100,1799,1212,1840"/>
<area shape="rect" href="namespacefirestarr_1_1logging.php#a7fcb338a90c4921f3c6109d9a88c9d92" title="Log with EXTENSIVE level." alt="" coords="1100,2505,1212,2547"/>
<area shape="rect" href="classfirestarr_1_1logging_1_1Log.php#a754395053c108ce52922eaee737584b7" title="Increase amount of logging output by one level." alt="" coords="1077,2571,1235,2612"/>
<area shape="rect" href="namespacefirestarr_1_1logging.php#ae505e6144c4c8127c9870e1dfa81039b" title="Log with INFO level." alt="" coords="1100,1391,1212,1432"/>
<area shape="rect" href="namespacefirestarr_1_1logging.php#a0ce472ba500e288fc9ddce4fe754ff9a" title="Log with NOTE level." alt="" coords="1100,2083,1212,2124"/>
<area shape="rect" href="namespacefirestarr_1_1logging.php#a348ff451a66eac8e3d5c853ee9a1b75c" title="Log with VERBOSE level." alt="" coords="1100,261,1212,303"/>
<area shape="rect" href="namespacefirestarr_1_1logging.php#af593934bad06e48689405ed621934f1c" title="Log with WARNING level." alt="" coords="883,2629,995,2671"/>
<area shape="rect" href="classfirestarr_1_1data_1_1GridBase.php#a95140f9c6c4d9b2302f906a9353136a5" title="Create .prj file in directory with base name for file." alt="" coords="861,356,1017,397"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1EnvironmentInfo.php#aa24e2a528711f734fa45f93b817bf0af" title="Constructor." alt="" coords="852,589,1027,631"/>
<area shape="rect" href="classfirestarr_1_1data_1_1GridBase.php#aa2f5f9bcd53090215dcefe78e70e740f" title="Find Coordinates for Point." alt="" coords="861,1092,1017,1133"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1Environment.php#a64d04afa288baf7ae92c1b697807e778" title="Load from rasters." alt="" coords="327,2253,501,2295"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1Environment.php#ab40c5e443a96f64a748991efe007d855" title="Load from rasters in folder that have same projection as Perimeter." alt="" coords="327,816,501,857"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Model.php#a198b3a0ff8f350f80b61142c2cde3d5f" title="Run Scenarios initialized from given inputs." alt="" coords="125,1349,258,1391"/>
<area shape="rect" href="Main_8cpp.php#aee608aedd5b0b58f2966c2ff15101925" title=" " alt="" coords="5,1386,56,1413"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Model.php#ac4159bf05562f6c9816718e331773233" title="Constructor." alt="" coords="873,291,1006,332"/>
<area shape="rect" href="namespacefirestarr_1_1util.php#a216a6c4fff5389e386c8c5969b92afe7" title=" " alt="" coords="880,421,999,463"/>
<area shape="rect" href="namespacefirestarr_1_1data.php#ab4496fe1247936b36ead7a86e7abee7e" title=" " alt="" coords="876,655,1003,696"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Model.php#acc76ae427ef30745a022b23628560b30" title="Read weather used for Scenarios." alt="" coords="873,873,1006,915"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Scenario.php#a6c27d631ec97664e71dcc8af8653fdf6" title="Run the Scenario." alt="" coords="853,1041,1026,1067"/>
<area shape="rect" href="namespacefirestarr_1_1sim.php#a96b22fe1cbbbe23ee5add23f198bf3d6" title="Runs test cases for constant weather and fuel based on given arguments." alt="" coords="354,886,474,913"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Model.php#ad73313aead546785538f27f53fe0f914" title="Run Iterations until confidence is reached." alt="" coords="610,1967,743,2008"/>
<area shape="rect" href="namespacefirestarr_1_1data.php#a9a0bafd711ce9aa0aeaa528ee234542b" title=" " alt="" coords="866,721,1013,747"/>
<area shape="rect" href="classfirestarr_1_1data_1_1GridMap.php#a0d8649c9a44527ed8a127e6d52571a8f" title="Save GridMap contents to .asc file." alt="" coords="601,297,752,339"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1EnvironmentInfo.php#a3c91989f571aecbec02c8b79dfa4b1df" title="Determine Coordinates in the grid for the Point." alt="" coords="589,1039,764,1080"/>
<area shape="rect" href="namespacefirestarr_1_1topo.php#a03d701e836ff628b6b907683e7ff656e" title=" " alt="" coords="613,1104,740,1145"/>
<area shape="rect" href="classfirestarr_1_1data_1_1ConstantGrid.php#acb83ad8fd5645c39fd501c1f361bed8b" title="Read a section of a TIFF into a ConstantGrid." alt="" coords="599,2253,754,2295"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1EnvironmentInfo.php#ae89d109beb612d8e2cddcb79fc619a25" title="Load the full Environment using the given FuelLookup to determine fuels." alt="" coords="104,2253,279,2295"/>
<area shape="rect" href="namespacefirestarr_1_1util.php#a01f442cbfac0eb7538a6eeb690d45311" title="Get a list of rasters in the given directory for the specified year." alt="" coords="619,705,734,747"/>
<area shape="rect" href="namespacefirestarr_1_1util.php#a184a1348724695546113f8be7cdb0f69" title=" " alt="" coords="617,421,736,463"/>
<area shape="rect" href="namespacefirestarr_1_1sim.php#a1ad746b67bf7b564d3065891f9a62ffa" title=" " alt="" coords="604,1221,749,1247"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Model.php#a197a6f13fe401f0224fb6d6ff8314e76" title="Find Cell(s) that can burn closest to Location." alt="" coords="873,1580,1006,1621"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Model.php#aa426303dd9471bfc0f772042b64d7ed9" title="Make starts based on desired point and where nearest combustible cells are." alt="" coords="610,1580,743,1621"/>
<area shape="rect" href="namespacefirestarr_1_1data.php#afdb97071581cec39531413a6d62997bc" title=" " alt="" coords="878,2747,1001,2788"/>
<area shape="rect" href="namespacefirestarr_1_1wx.php#a408ab9942535e94b574a723e4356d6a9" title=" " alt="" coords="880,2813,999,2839"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1BurnedMap.php#a8775fc310860e0203977d750d96beab4" title="Constructor." alt="" coords="855,1697,1023,1739"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Scenario.php#aecb0887700a3e690cc4e1b058666d305" title="Take whatever steps are necessary to process the given Event." alt="" coords="602,93,751,135"/>
<area shape="rect" href="classfirestarr_1_1data_1_1GridMap.php#a72142b89653f96b2513a0859fafc5c1d" title="Make a list of all Locations that are on the edge of cells with a value." alt="" coords="864,1361,1015,1403"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1SettingsImplementation.php#ad62d323b119c294af4957ad6d789b5dc" title="Read settings from a file." alt="" coords="549,2372,804,2413"/>
<area shape="rect" href="namespacefirestarr_1_1sim.php#a65bb7516ac34869a79ef27aac8ab84af" title=" " alt="" coords="880,2017,999,2059"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1Environment.php#af0a0f163eb3a3fa210b504466683519e" title="Load from rasters." alt="" coords="852,2265,1027,2307"/>
<area shape="rect" href="namespacefirestarr_1_1sim.php#a608e95dcaf1ac0da95fdf74bbbd26967" title=" " alt="" coords="878,2083,1001,2124"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1ProbabilityMap.php#adc9a4cb7a0d86f4d60c3deca91192aa3" title="Save total, low, moderate, and high maps, and output information to log." alt="" coords="860,2331,1019,2372"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Semaphore.php#aed3949517b62c68db0f26588013473b3" title="Create a Semaphore that limits number of concurrent things running." alt="" coords="857,2396,1021,2437"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1ProbabilityMap.php#a90df654319d36e91f11c5bf941327796" title="Output Statistics to log." alt="" coords="860,2461,1019,2503"/>
<area shape="rect" href="classfirestarr_1_1util_1_1UsageCount.php#a6a327e552b07301e571a206d7fb6fe33" title=" " alt="" coords="856,2200,1023,2241"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Scenario.php#ae9fea7b9a4248046eb5886fd5b431ed6" title="End the simulation." alt="" coords="865,123,1014,164"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Scenario.php#ab8a1fff89a55abc3893a9fcbe40e3617" title="Schedule a fire spread Event." alt="" coords="865,5,1014,47"/>
</map>
</div>

</div>
</div>
<a id="a754395053c108ce52922eaee737584b7"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a754395053c108ce52922eaee737584b7">&#9670;&nbsp;</a></span>increaseLogLevel()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void firestarr::logging::Log::increaseLogLevel </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span><span class="mlabel">noexcept</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Increase amount of logging output by one level. </p>
<dl class="section return"><dt>Returns</dt><dd>None </dd></dl>

<p class="definition">Definition at line <a class="el" href="Log_8cpp_source.php#l00025">25</a> of file <a class="el" href="Log_8cpp_source.php">Log.cpp</a>.</p>
<div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="classfirestarr_1_1logging_1_1Log_a754395053c108ce52922eaee737584b7_cgraph.png" border="0" usemap="#aclassfirestarr_1_1logging_1_1Log_a754395053c108ce52922eaee737584b7_cgraph" alt=""/></div>
<map name="aclassfirestarr_1_1logging_1_1Log_a754395053c108ce52922eaee737584b7_cgraph" id="aclassfirestarr_1_1logging_1_1Log_a754395053c108ce52922eaee737584b7_cgraph">
<area shape="rect" title="Increase amount of logging output by one level." alt="" coords="5,5,164,47"/>
<area shape="rect" href="classfirestarr_1_1logging_1_1Log.php#a2bbec15b677b9f38e8e0cec0ee46d41c" title="Get current logging level." alt="" coords="212,5,340,47"/>
</map>
</div>

</div>
</div>
<a id="aeae41fa8b4fe6765c7ed57763e293a63"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aeae41fa8b4fe6765c7ed57763e293a63">&#9670;&nbsp;</a></span>output()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void firestarr::logging::Log::output </td>
          <td>(</td>
          <td class="paramtype">const char *&#160;</td>
          <td class="paramname"><em>name</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">const char *&#160;</td>
          <td class="paramname"><em>format</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">va_list *&#160;</td>
          <td class="paramname"><em>args</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span><span class="mlabel">noexcept</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Output a message to the log. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">name</td><td>Name of logging level to mark message with </td></tr>
    <tr><td class="paramname">format</td><td>Format string for message </td></tr>
    <tr><td class="paramname">args</td><td>Arguments to use in format string </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>None </dd></dl>

<p class="definition">Definition at line <a class="el" href="Log_8cpp_source.php#l00039">39</a> of file <a class="el" href="Log_8cpp_source.php">Log.cpp</a>.</p>
<div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="classfirestarr_1_1logging_1_1Log_aeae41fa8b4fe6765c7ed57763e293a63_icgraph.png" border="0" usemap="#aclassfirestarr_1_1logging_1_1Log_aeae41fa8b4fe6765c7ed57763e293a63_icgraph" alt=""/></div>
<map name="aclassfirestarr_1_1logging_1_1Log_aeae41fa8b4fe6765c7ed57763e293a63_icgraph" id="aclassfirestarr_1_1logging_1_1Log_aeae41fa8b4fe6765c7ed57763e293a63_icgraph">
<area shape="rect" title="Output a message to the log." alt="" coords="1755,1687,1867,1728"/>
<area shape="rect" href="namespacefirestarr_1_1logging.php#a4253b6677b26aa72ac4e784e0891af82" title="Log with DEBUG level." alt="" coords="1416,839,1528,880"/>
<area shape="rect" href="namespacefirestarr_1_1logging.php#aa744a6caeb1cf6e09066cc5bd79af369" title="Log with ERROR level." alt="" coords="1595,1745,1707,1787"/>
<area shape="rect" href="namespacefirestarr_1_1logging.php#a7fcb338a90c4921f3c6109d9a88c9d92" title="Log with EXTENSIVE level." alt="" coords="1595,2132,1707,2173"/>
<area shape="rect" href="namespacefirestarr_1_1logging.php#ae505e6144c4c8127c9870e1dfa81039b" title="Log with INFO level." alt="" coords="1416,1687,1528,1728"/>
<area shape="rect" href="namespacefirestarr_1_1logging.php#a0ce472ba500e288fc9ddce4fe754ff9a" title="Log with NOTE level." alt="" coords="995,387,1107,428"/>
<area shape="rect" href="namespacefirestarr_1_1logging.php#a348ff451a66eac8e3d5c853ee9a1b75c" title="Log with VERBOSE level." alt="" coords="1595,1319,1707,1360"/>
<area shape="rect" href="namespacefirestarr_1_1logging.php#af593934bad06e48689405ed621934f1c" title="Log with WARNING level." alt="" coords="785,2015,897,2056"/>
<area shape="rect" href="classfirestarr_1_1data_1_1GridBase.php#a95140f9c6c4d9b2302f906a9353136a5" title="Create .prj file in directory with base name for file." alt="" coords="1184,755,1340,796"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1EnvironmentInfo.php#aa24e2a528711f734fa45f93b817bf0af" title="Constructor." alt="" coords="1175,572,1349,613"/>
<area shape="rect" href="classfirestarr_1_1data_1_1GridBase.php#aa2f5f9bcd53090215dcefe78e70e740f" title="Find Coordinates for Point." alt="" coords="763,871,919,912"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1Environment.php#a64d04afa288baf7ae92c1b697807e778" title="Load from rasters." alt="" coords="228,1707,403,1748"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1Environment.php#ab40c5e443a96f64a748991efe007d855" title="Load from rasters in folder that have same projection as Perimeter." alt="" coords="753,1140,928,1181"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Model.php#a198b3a0ff8f350f80b61142c2cde3d5f" title="Run Scenarios initialized from given inputs." alt="" coords="249,1009,382,1051"/>
<area shape="rect" href="Main_8cpp.php#aee608aedd5b0b58f2966c2ff15101925" title=" " alt="" coords="67,966,118,993"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Model.php#ac4159bf05562f6c9816718e331773233" title="Constructor." alt="" coords="1195,1075,1329,1116"/>
<area shape="rect" href="namespacefirestarr_1_1util.php#a216a6c4fff5389e386c8c5969b92afe7" title=" " alt="" coords="1203,1257,1321,1299"/>
<area shape="rect" href="namespacefirestarr_1_1data.php#ab4496fe1247936b36ead7a86e7abee7e" title=" " alt="" coords="1199,637,1325,679"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Model.php#acc76ae427ef30745a022b23628560b30" title="Read weather used for Scenarios." alt="" coords="1195,1192,1329,1233"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Scenario.php#a6c27d631ec97664e71dcc8af8653fdf6" title="Run the Scenario." alt="" coords="754,1463,927,1490"/>
<area shape="rect" href="namespacefirestarr_1_1sim.php#a96b22fe1cbbbe23ee5add23f198bf3d6" title="Runs test cases for constant weather and fuel based on given arguments." alt="" coords="255,794,375,821"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Model.php#ad73313aead546785538f27f53fe0f914" title="Run Iterations until confidence is reached." alt="" coords="511,637,645,679"/>
<area shape="rect" href="namespacefirestarr_1_1data.php#a9a0bafd711ce9aa0aeaa528ee234542b" title=" " alt="" coords="1189,821,1335,847"/>
<area shape="rect" href="classfirestarr_1_1data_1_1GridMap.php#a0d8649c9a44527ed8a127e6d52571a8f" title="Save GridMap contents to .asc file." alt="" coords="976,972,1127,1013"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1EnvironmentInfo.php#a3c91989f571aecbec02c8b79dfa4b1df" title="Determine Coordinates in the grid for the Point." alt="" coords="491,871,665,912"/>
<area shape="rect" href="namespacefirestarr_1_1topo.php#a03d701e836ff628b6b907683e7ff656e" title=" " alt="" coords="515,805,641,847"/>
<area shape="rect" href="classfirestarr_1_1data_1_1ConstantGrid.php#acb83ad8fd5645c39fd501c1f361bed8b" title="Read a section of a TIFF into a ConstantGrid." alt="" coords="501,1644,655,1685"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1Perimeter.php#a68c886bbc16e8a8434668c3f2a1ba63f" title="Initialize perimeter from a file." alt="" coords="236,1641,395,1683"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1EnvironmentInfo.php#ae89d109beb612d8e2cddcb79fc619a25" title="Load the full Environment using the given FuelLookup to determine fuels." alt="" coords="5,1707,180,1748"/>
<area shape="rect" href="namespacefirestarr_1_1util.php#a01f442cbfac0eb7538a6eeb690d45311" title="Get a list of rasters in the given directory for the specified year." alt="" coords="994,1089,1109,1131"/>
<area shape="rect" href="namespacefirestarr_1_1util.php#a184a1348724695546113f8be7cdb0f69" title=" " alt="" coords="992,1257,1111,1299"/>
<area shape="rect" href="namespacefirestarr_1_1sim.php#a1ad746b67bf7b564d3065891f9a62ffa" title=" " alt="" coords="505,1265,651,1291"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Model.php#a197a6f13fe401f0224fb6d6ff8314e76" title="Find Cell(s) that can burn closest to Location." alt="" coords="1195,2015,1329,2056"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Model.php#aa426303dd9471bfc0f772042b64d7ed9" title="Make starts based on desired point and where nearest combustible cells are." alt="" coords="774,1628,907,1669"/>
<area shape="rect" href="namespacefirestarr_1_1data.php#afdb97071581cec39531413a6d62997bc" title=" " alt="" coords="1411,2132,1533,2173"/>
<area shape="rect" href="namespacefirestarr_1_1wx.php#a408ab9942535e94b574a723e4356d6a9" title=" " alt="" coords="1413,2198,1531,2225"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1BurnedMap.php#a8775fc310860e0203977d750d96beab4" title="Constructor." alt="" coords="757,1377,925,1419"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Scenario.php#aecb0887700a3e690cc4e1b058666d305" title="Take whatever steps are necessary to process the given Event." alt="" coords="1187,1375,1337,1416"/>
<area shape="rect" href="classfirestarr_1_1data_1_1GridMap.php#a72142b89653f96b2513a0859fafc5c1d" title="Make a list of all Locations that are on the edge of cells with a value." alt="" coords="1187,1847,1337,1888"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1SettingsImplementation.php#ad62d323b119c294af4957ad6d789b5dc" title="Read settings from a file." alt="" coords="451,1931,705,1972"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Scenario.php#aa9a4707910b9e191b66710b4df852516" title="Evaluate next Event in the queue." alt="" coords="977,1476,1126,1517"/>
<area shape="rect" href="namespacefirestarr_1_1sim.php#a65bb7516ac34869a79ef27aac8ab84af" title=" " alt="" coords="781,536,900,577"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1Environment.php#af0a0f163eb3a3fa210b504466683519e" title="Load from rasters." alt="" coords="753,471,928,512"/>
<area shape="rect" href="namespacefirestarr_1_1sim.php#a608e95dcaf1ac0da95fdf74bbbd26967" title=" " alt="" coords="779,601,902,643"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1ProbabilityMap.php#adc9a4cb7a0d86f4d60c3deca91192aa3" title="Save total, low, moderate, and high maps, and output information to log." alt="" coords="761,5,920,47"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Semaphore.php#aed3949517b62c68db0f26588013473b3" title="Create a Semaphore that limits number of concurrent things running." alt="" coords="759,71,923,112"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1ProbabilityMap.php#a90df654319d36e91f11c5bf941327796" title="Output Statistics to log." alt="" coords="761,136,920,177"/>
<area shape="rect" href="classfirestarr_1_1util_1_1UsageCount.php#a6a327e552b07301e571a206d7fb6fe33" title=" " alt="" coords="757,201,924,243"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Scenario.php#ae9fea7b9a4248046eb5886fd5b431ed6" title="End the simulation." alt="" coords="1397,1348,1547,1389"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1Scenario.php#ab8a1fff89a55abc3893a9fcbe40e3617" title="Schedule a fire spread Event." alt="" coords="1397,1413,1547,1455"/>
</map>
</div>

</div>
</div>
<a id="aec96e3a1912bbcc22824aee73abb4b14"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aec96e3a1912bbcc22824aee73abb4b14">&#9670;&nbsp;</a></span>setLogLevel()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">void firestarr::logging::Log::setLogLevel </td>
          <td>(</td>
          <td class="paramtype">int&#160;</td>
          <td class="paramname"><em>log_level</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span><span class="mlabel">noexcept</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Set logging level to a specific level. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">log_level</td><td><a class="el" href="classfirestarr_1_1logging_1_1Log.php" title="Provides logging functionality.">Log</a> level to use </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>None </dd></dl>

<p class="definition">Definition at line <a class="el" href="Log_8cpp_source.php#l00021">21</a> of file <a class="el" href="Log_8cpp_source.php">Log.cpp</a>.</p>

</div>
</div>
<h2 class="groupheader">Member Data Documentation</h2>
<a id="a7d7641f9eeef527e7bfba730bab1ffaf"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a7d7641f9eeef527e7bfba730bab1ffaf">&#9670;&nbsp;</a></span>logging_level_</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">int firestarr::logging::Log::logging_level_ = <a class="el" href="namespacefirestarr_1_1logging.php#ae97fef0f2c11153019951e242e28a2de">LOG_DEBUG</a></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span><span class="mlabel">private</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Current logging level. </p>

<p class="definition">Definition at line <a class="el" href="Log_8h_source.php#l00038">38</a> of file <a class="el" href="Log_8h_source.php">Log.h</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>FireSTARR/src/<a class="el" href="Log_8h_source.php">Log.h</a></li>
<li>FireSTARR/src/<a class="el" href="Log_8cpp_source.php">Log.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
