<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>FireSTARR: firestarr::fuel::fbp::FuelC2 Class Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">FireSTARR
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.php');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespacefirestarr.php">firestarr</a></li><li class="navelem"><a class="el" href="namespacefirestarr_1_1fuel.php">fuel</a></li><li class="navelem"><a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php">fbp</a></li><li class="navelem"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php">FuelC2</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#pub-methods">Public Member Functions</a> &#124;
<a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2-members.php">List of all members</a>  </div>
  <div class="headertitle">
<div class="title">firestarr::fuel::fbp::FuelC2 Class Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p>FBP fuel type C-2.  
 <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php#details">More...</a></p>

<p><code>#include &lt;<a class="el" href="FBP45_8h_source.php">FBP45.h</a>&gt;</code></p>
<div class="dynheader">
Inheritance diagram for firestarr::fuel::fbp::FuelC2:</div>
<div class="dyncontent">
<div class="center"><img src="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2__inherit__graph.png" border="0" usemap="#afirestarr_1_1fuel_1_1fbp_1_1FuelC2_inherit__map" alt="Inheritance graph"/></div>
<map name="afirestarr_1_1fuel_1_1fbp_1_1FuelC2_inherit__map" id="afirestarr_1_1fuel_1_1fbp_1_1FuelC2_inherit__map">
<area shape="rect" title="FBP fuel type C&#45;2." alt="" coords="31,2187,216,2381"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelConifer.php" title=" " alt="" coords="38,1928,209,2137"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php" title="A StandardFuel that is not made of multiple fuels." alt="" coords="19,1353,217,1577"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelConifer.php" title="A conifer fuel type." alt="" coords="139,1627,342,1851"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1StandardFuel.php" title="A FuelBase made of a standard fuel type." alt="" coords="5,889,231,1304"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelBase.php" title="Base class for all FuelTypes." alt="" coords="13,499,223,840"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelType.php" title="An FBP fuel type." alt="" coords="25,5,211,449"/>
</map>
</div>
<div class="dynheader">
Collaboration diagram for firestarr::fuel::fbp::FuelC2:</div>
<div class="dyncontent">
<div class="center"><img src="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2__coll__graph.png" border="0" usemap="#afirestarr_1_1fuel_1_1fbp_1_1FuelC2_coll__map" alt="Collaboration graph"/></div>
<map name="afirestarr_1_1fuel_1_1fbp_1_1FuelC2_coll__map" id="afirestarr_1_1fuel_1_1fbp_1_1FuelC2_coll__map">
<area shape="rect" title="FBP fuel type C&#45;2." alt="" coords="185,2868,370,3063"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelConifer.php" title=" " alt="" coords="192,2609,363,2819"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php" title="A StandardFuel that is not made of multiple fuels." alt="" coords="173,2035,371,2259"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelConifer.php" title="A conifer fuel type." alt="" coords="293,2308,496,2532"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1StandardFuel.php" title="A FuelBase made of a standard fuel type." alt="" coords="159,1571,385,1985"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelBase.php" title="Base class for all FuelTypes." alt="" coords="217,1167,428,1493"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelType.php" title="An FBP fuel type." alt="" coords="231,675,417,1089"/>
<area shape="rect" title=" " alt="" coords="193,410,239,487"/>
<area shape="rect" title=" " alt="" coords="299,410,349,487"/>
<area shape="rect" title=" " alt="" coords="373,410,464,487"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1Duff.php" title="Base class for DuffType." alt="" coords="1135,785,1295,979"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title=" " alt="" coords="1081,1622,1245,1934"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title="A specific type of Duff layer, and the associated smouldering coefficients." alt="" coords="1289,1189,1479,1471"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title=" " alt="" coords="1799,1622,1980,1934"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title=" " alt="" coords="1295,1622,1473,1934"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title=" " alt="" coords="2011,1622,2175,1934"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title=" " alt="" coords="2199,1622,2366,1934"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title=" " alt="" coords="430,1622,594,1934"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title=" " alt="" coords="628,1622,809,1934"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title=" " alt="" coords="849,1622,1031,1934"/>
<area shape="rect" href="classfirestarr_1_1util_1_1LookupTable.php" title=" " alt="" coords="2319,785,2489,979"/>
<area shape="rect" href="classfirestarr_1_1util_1_1LookupTable.php" title="A table initialized using the given function ranging over the number of digits and precision." alt="" coords="2307,351,2501,546"/>
<area shape="rect" title=" " alt="" coords="2352,145,2456,223"/>
<area shape="rect" title=" " alt="" coords="2385,5,2423,83"/>
<area shape="rect" title=" " alt="" coords="2153,843,2295,921"/>
<area shape="rect" href="classfirestarr_1_1data_1_1LogValue.php" title="A result of calling log(x) for some value of x, pre&#45;calculated at compile time." alt="" coords="35,1291,192,1369"/>
<area shape="rect" href="classfirestarr_1_1data_1_1Index.php" title=" " alt="" coords="39,711,172,1053"/>
<area shape="rect" href="classfirestarr_1_1data_1_1Index.php" title="A wrapper around a double to ensure correct types are used." alt="" coords="5,285,168,612"/>
<area shape="rect" title=" " alt="" coords="57,145,117,223"/>
</map>
</div>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="pub-methods"></a>
Public Member Functions</h2></td></tr>
<tr class="memitem:a5b7766d10f5065d1ae82cb47c4d35261"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php#a5b7766d10f5065d1ae82cb47c4d35261">FuelC2</a> ()=delete</td></tr>
<tr class="separator:a5b7766d10f5065d1ae82cb47c4d35261"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9e12f9290f85e5fd55ddfa9fe55f7fd5"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php#a9e12f9290f85e5fd55ddfa9fe55f7fd5">~FuelC2</a> ()=default</td></tr>
<tr class="separator:a9e12f9290f85e5fd55ddfa9fe55f7fd5"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a05553861da7a9e8ae7b3633aea594a98"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php#a05553861da7a9e8ae7b3633aea594a98">FuelC2</a> (const <a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php">FuelC2</a> &amp;rhs) noexcept=delete</td></tr>
<tr class="separator:a05553861da7a9e8ae7b3633aea594a98"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ada1c48f3e82b895608b6848550cea55b"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php#ada1c48f3e82b895608b6848550cea55b">FuelC2</a> (<a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php">FuelC2</a> &amp;&amp;rhs) noexcept=delete</td></tr>
<tr class="separator:ada1c48f3e82b895608b6848550cea55b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad187f8e3ead64b5a18060e3d3a753902"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php">FuelC2</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php#ad187f8e3ead64b5a18060e3d3a753902">operator=</a> (const <a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php">FuelC2</a> &amp;rhs) noexcept=delete</td></tr>
<tr class="separator:ad187f8e3ead64b5a18060e3d3a753902"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af42f6e6702ff255296d7b1cb5898353c"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php">FuelC2</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php#af42f6e6702ff255296d7b1cb5898353c">operator=</a> (<a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php">FuelC2</a> &amp;&amp;rhs) noexcept=delete</td></tr>
<tr class="separator:af42f6e6702ff255296d7b1cb5898353c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab70ec0ca0c0f10df0cd2c8b46ca02810"><td class="memItemLeft" align="right" valign="top">constexpr&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php#ab70ec0ca0c0f10df0cd2c8b46ca02810">FuelC2</a> (const <a class="el" href="namespacefirestarr.php#a2cc099cdbca82a68a7d1cc6350f16453">FuelCodeSize</a> &amp;<a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#abafed0f685ef59a90afdf7af3d8ea110">code</a>) noexcept</td></tr>
<tr class="memdesc:ab70ec0ca0c0f10df0cd2c8b46ca02810"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type C-2.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php#ab70ec0ca0c0f10df0cd2c8b46ca02810">More...</a><br /></td></tr>
<tr class="separator:ab70ec0ca0c0f10df0cd2c8b46ca02810"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aab7326f75775c1055abb9d8412267f73"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php#aab7326f75775c1055abb9d8412267f73">surfaceFuelConsumption</a> (const <a class="el" href="classfirestarr_1_1sim_1_1SpreadInfo.php">SpreadInfo</a> &amp;spread) const noexcept override</td></tr>
<tr class="memdesc:aab7326f75775c1055abb9d8412267f73"><td class="mdescLeft">&#160;</td><td class="mdescRight">Surface Fuel Consumption (SFC) (kg/m^2) [ST-X-3 eq 10].  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php#aab7326f75775c1055abb9d8412267f73">More...</a><br /></td></tr>
<tr class="separator:aab7326f75775c1055abb9d8412267f73"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_classfirestarr_1_1fuel_1_1FuelConifer')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="classfirestarr_1_1fuel_1_1FuelConifer.php">firestarr::fuel::FuelConifer&lt; 110, 282, 150, 64, 3, 80, 34, 0, 100 &gt;</a></td></tr>
<tr class="memitem:abae23c9277c8e7414263a7dc8eb73731 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelConifer.php#abae23c9277c8e7414263a7dc8eb73731">FuelConifer</a> ()=delete</td></tr>
<tr class="separator:abae23c9277c8e7414263a7dc8eb73731 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af5bac38f4358d2a1de5ce0927f224499 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelConifer.php#af5bac38f4358d2a1de5ce0927f224499">FuelConifer</a> (const <a class="el" href="classfirestarr_1_1fuel_1_1FuelConifer.php">FuelConifer</a> &amp;rhs) noexcept=delete</td></tr>
<tr class="separator:af5bac38f4358d2a1de5ce0927f224499 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5209874c83a94bd989beee5852596190 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelConifer.php#a5209874c83a94bd989beee5852596190">FuelConifer</a> (<a class="el" href="classfirestarr_1_1fuel_1_1FuelConifer.php">FuelConifer</a> &amp;&amp;rhs) noexcept=delete</td></tr>
<tr class="separator:a5209874c83a94bd989beee5852596190 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adfb98f21419e340a2d8cdaebcae441d1 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelConifer.php#adfb98f21419e340a2d8cdaebcae441d1">~FuelConifer</a> ()=default</td></tr>
<tr class="separator:adfb98f21419e340a2d8cdaebcae441d1 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a559b44f888589385a4b78756880efec9 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classfirestarr_1_1fuel_1_1FuelConifer.php">FuelConifer</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelConifer.php#a559b44f888589385a4b78756880efec9">operator=</a> (const <a class="el" href="classfirestarr_1_1fuel_1_1FuelConifer.php">FuelConifer</a> &amp;rhs) noexcept=delete</td></tr>
<tr class="separator:a559b44f888589385a4b78756880efec9 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afaf071c167ce9c1b9b284c313f14761c inherit pub_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classfirestarr_1_1fuel_1_1FuelConifer.php">FuelConifer</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelConifer.php#afaf071c167ce9c1b9b284c313f14761c">operator=</a> (<a class="el" href="classfirestarr_1_1fuel_1_1FuelConifer.php">FuelConifer</a> &amp;&amp;rhs) noexcept=delete</td></tr>
<tr class="separator:afaf071c167ce9c1b9b284c313f14761c inherit pub_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_classfirestarr_1_1fuel_1_1FuelNonMixed')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php">firestarr::fuel::FuelNonMixed&lt; A, B, C, Bui0, Cbh, Cfl, BulkDensity, InorganicPercent, DuffDepth &gt;</a></td></tr>
<tr class="memitem:ab39559b88c6aad53e29ea625f4dfa313 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php#ab39559b88c6aad53e29ea625f4dfa313">FuelNonMixed</a> ()=delete</td></tr>
<tr class="separator:ab39559b88c6aad53e29ea625f4dfa313 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0b62f6170803eeea4dd38f48d6eb70f9 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php#a0b62f6170803eeea4dd38f48d6eb70f9">~FuelNonMixed</a> ()=default</td></tr>
<tr class="separator:a0b62f6170803eeea4dd38f48d6eb70f9 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9414851290a677b4819564799fd05735 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php#a9414851290a677b4819564799fd05735">FuelNonMixed</a> (const <a class="el" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php">FuelNonMixed</a> &amp;rhs) noexcept=delete</td></tr>
<tr class="separator:a9414851290a677b4819564799fd05735 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a508ad49e77f093883e341994b3642628 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php#a508ad49e77f093883e341994b3642628">FuelNonMixed</a> (<a class="el" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php">FuelNonMixed</a> &amp;&amp;rhs) noexcept=delete</td></tr>
<tr class="separator:a508ad49e77f093883e341994b3642628 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aae6a62c53bc6af8db5f659fbd9c09637 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php">FuelNonMixed</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php#aae6a62c53bc6af8db5f659fbd9c09637">operator=</a> (const <a class="el" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php">FuelNonMixed</a> &amp;rhs) noexcept=delete</td></tr>
<tr class="separator:aae6a62c53bc6af8db5f659fbd9c09637 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab0c7b5e475929056bd658a5cfc935542 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php">FuelNonMixed</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php#ab0c7b5e475929056bd658a5cfc935542">operator=</a> (<a class="el" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php">FuelNonMixed</a> &amp;&amp;rhs) noexcept=delete</td></tr>
<tr class="separator:ab0c7b5e475929056bd658a5cfc935542 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_classfirestarr_1_1fuel_1_1StandardFuel')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php">firestarr::fuel::StandardFuel&lt; A, B, C, Bui0, Cbh, Cfl, BulkDensity, InorganicPercent, DuffDepth &gt;</a></td></tr>
<tr class="memitem:a6f6635c86c631eb58aa2c66492c4a66f inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">constexpr&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#a6f6635c86c631eb58aa2c66492c4a66f">StandardFuel</a> (const <a class="el" href="namespacefirestarr.php#a2cc099cdbca82a68a7d1cc6350f16453">FuelCodeSize</a> &amp;<a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#abafed0f685ef59a90afdf7af3d8ea110">code</a>, const char *<a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#a30b502469a8011c6df38119eb33736fc">name</a>, const bool can_crown, const <a class="el" href="classfirestarr_1_1data_1_1LogValue.php">LogValue</a> log_q, const <a class="el" href="classfirestarr_1_1fuel_1_1Duff.php">Duff</a> *duff_ffmc, const <a class="el" href="classfirestarr_1_1fuel_1_1Duff.php">Duff</a> *duff_dmc) noexcept</td></tr>
<tr class="memdesc:a6f6635c86c631eb58aa2c66492c4a66f inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="mdescLeft">&#160;</td><td class="mdescRight">Constructor.  <a href="classfirestarr_1_1fuel_1_1StandardFuel.php#a6f6635c86c631eb58aa2c66492c4a66f">More...</a><br /></td></tr>
<tr class="separator:a6f6635c86c631eb58aa2c66492c4a66f inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afa6d4acee27d123ffd8af3a21e735af9 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">constexpr&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#afa6d4acee27d123ffd8af3a21e735af9">StandardFuel</a> (const <a class="el" href="namespacefirestarr.php#a2cc099cdbca82a68a7d1cc6350f16453">FuelCodeSize</a> &amp;<a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#abafed0f685ef59a90afdf7af3d8ea110">code</a>, const char *<a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#a30b502469a8011c6df38119eb33736fc">name</a>, const bool can_crown, const <a class="el" href="classfirestarr_1_1data_1_1LogValue.php">LogValue</a> log_q, const <a class="el" href="classfirestarr_1_1fuel_1_1Duff.php">Duff</a> *duff) noexcept</td></tr>
<tr class="memdesc:afa6d4acee27d123ffd8af3a21e735af9 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="mdescLeft">&#160;</td><td class="mdescRight">Constructor.  <a href="classfirestarr_1_1fuel_1_1StandardFuel.php#afa6d4acee27d123ffd8af3a21e735af9">More...</a><br /></td></tr>
<tr class="separator:afa6d4acee27d123ffd8af3a21e735af9 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aaa115e8fbf6467e9da300238b6c3d48f inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#aaa115e8fbf6467e9da300238b6c3d48f">StandardFuel</a> (<a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php">StandardFuel</a> &amp;&amp;rhs) noexcept=delete</td></tr>
<tr class="separator:aaa115e8fbf6467e9da300238b6c3d48f inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a46b7783172e09f3d9cd7649c9e2ec7f1 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#a46b7783172e09f3d9cd7649c9e2ec7f1">StandardFuel</a> (const <a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php">StandardFuel</a> &amp;rhs) noexcept=delete</td></tr>
<tr class="separator:a46b7783172e09f3d9cd7649c9e2ec7f1 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a94fb21dbb8a54f0638fa3625618c7dc9 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php">StandardFuel</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#a94fb21dbb8a54f0638fa3625618c7dc9">operator=</a> (<a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php">StandardFuel</a> &amp;&amp;rhs) noexcept=delete</td></tr>
<tr class="separator:a94fb21dbb8a54f0638fa3625618c7dc9 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0b8a53a3941c808a71b73b6ede60ec5e inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php">StandardFuel</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#a0b8a53a3941c808a71b73b6ede60ec5e">operator=</a> (const <a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php">StandardFuel</a> &amp;rhs)=delete</td></tr>
<tr class="separator:a0b8a53a3941c808a71b73b6ede60ec5e inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aaa463dcf481b83ea32fe3ad6ff366d80 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#aaa463dcf481b83ea32fe3ad6ff366d80">rosBasic</a> (const double isi) const noexcept</td></tr>
<tr class="memdesc:aaa463dcf481b83ea32fe3ad6ff366d80 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="mdescLeft">&#160;</td><td class="mdescRight">Initial rate of spread (m/min) [ST-X-3 eq 26].  <a href="classfirestarr_1_1fuel_1_1StandardFuel.php#aaa463dcf481b83ea32fe3ad6ff366d80">More...</a><br /></td></tr>
<tr class="separator:aaa463dcf481b83ea32fe3ad6ff366d80 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad7e29468c4ad61f480cb0439eaacf47d inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#ad7e29468c4ad61f480cb0439eaacf47d">crownConsumption</a> (const double cfb) const noexcept override</td></tr>
<tr class="memdesc:ad7e29468c4ad61f480cb0439eaacf47d inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="mdescLeft">&#160;</td><td class="mdescRight">Crown Fuel Consumption (CFC) (kg/m^2) [ST-X-3 eq 66].  <a href="classfirestarr_1_1fuel_1_1StandardFuel.php#ad7e29468c4ad61f480cb0439eaacf47d">More...</a><br /></td></tr>
<tr class="separator:ad7e29468c4ad61f480cb0439eaacf47d inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a15ff42656b872ab4c97bb64119687ad1 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#a15ff42656b872ab4c97bb64119687ad1">limitIsf</a> (const double mu, const double rsf) const noexcept</td></tr>
<tr class="memdesc:a15ff42656b872ab4c97bb64119687ad1 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="mdescLeft">&#160;</td><td class="mdescRight">ISI with slope influence and zero wind (ISF) [ST-X-3 eq 41].  <a href="classfirestarr_1_1fuel_1_1StandardFuel.php#a15ff42656b872ab4c97bb64119687ad1">More...</a><br /></td></tr>
<tr class="separator:a15ff42656b872ab4c97bb64119687ad1 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab81c50aaf3fb129f3e4aae527567da92 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#ab81c50aaf3fb129f3e4aae527567da92">criticalSurfaceIntensity</a> (const <a class="el" href="classfirestarr_1_1sim_1_1SpreadInfo.php">SpreadInfo</a> &amp;spread) const noexcept override</td></tr>
<tr class="memdesc:ab81c50aaf3fb129f3e4aae527567da92 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="mdescLeft">&#160;</td><td class="mdescRight">Critical Surface Fire Intensity (CSI) [ST-X-3 eq 56].  <a href="classfirestarr_1_1fuel_1_1StandardFuel.php#ab81c50aaf3fb129f3e4aae527567da92">More...</a><br /></td></tr>
<tr class="separator:ab81c50aaf3fb129f3e4aae527567da92 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a728a6f95c9da861ad8cdd16c2041eb72 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#a728a6f95c9da861ad8cdd16c2041eb72">lengthToBreadth</a> (const double ws) const noexcept override</td></tr>
<tr class="memdesc:a728a6f95c9da861ad8cdd16c2041eb72 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="mdescLeft">&#160;</td><td class="mdescRight">Length to Breadth ratio [ST-X-3 eq 79].  <a href="classfirestarr_1_1fuel_1_1StandardFuel.php#a728a6f95c9da861ad8cdd16c2041eb72">More...</a><br /></td></tr>
<tr class="separator:a728a6f95c9da861ad8cdd16c2041eb72 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2a4441e8682ecc5f0271abb49f5b2854 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#a2a4441e8682ecc5f0271abb49f5b2854">finalRos</a> (const <a class="el" href="classfirestarr_1_1sim_1_1SpreadInfo.php">SpreadInfo</a> &amp;, double, double, const double rss) const noexcept override</td></tr>
<tr class="memdesc:a2a4441e8682ecc5f0271abb49f5b2854 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="mdescLeft">&#160;</td><td class="mdescRight">Final rate of spread (m/min)  <a href="classfirestarr_1_1fuel_1_1StandardFuel.php#a2a4441e8682ecc5f0271abb49f5b2854">More...</a><br /></td></tr>
<tr class="separator:a2a4441e8682ecc5f0271abb49f5b2854 inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad6726c63b5e731cff9c4eb11bcc94e3b inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#ad6726c63b5e731cff9c4eb11bcc94e3b">buiEffect</a> (const double bui) const noexcept override</td></tr>
<tr class="memdesc:ad6726c63b5e731cff9c4eb11bcc94e3b inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="mdescLeft">&#160;</td><td class="mdescRight">BUI Effect on surface fire rate of spread [ST-X-3 eq 54].  <a href="classfirestarr_1_1fuel_1_1StandardFuel.php#ad6726c63b5e731cff9c4eb11bcc94e3b">More...</a><br /></td></tr>
<tr class="separator:ad6726c63b5e731cff9c4eb11bcc94e3b inherit pub_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_classfirestarr_1_1fuel_1_1FuelBase')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php">firestarr::fuel::FuelBase&lt; BulkDensity, InorganicPercent, DuffDepth &gt;</a></td></tr>
<tr class="memitem:a008b29f8faa6cebeee46165dbb84187f inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php#a008b29f8faa6cebeee46165dbb84187f">~FuelBase</a> ()=default</td></tr>
<tr class="separator:a008b29f8faa6cebeee46165dbb84187f inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab723decfc7f0295f93b27df214b29000 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memItemLeft" align="right" valign="top">constexpr&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php#ab723decfc7f0295f93b27df214b29000">FuelBase</a> (const <a class="el" href="namespacefirestarr.php#a2cc099cdbca82a68a7d1cc6350f16453">FuelCodeSize</a> &amp;<a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#abafed0f685ef59a90afdf7af3d8ea110">code</a>, const char *<a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#a30b502469a8011c6df38119eb33736fc">name</a>, const bool can_crown, const <a class="el" href="classfirestarr_1_1fuel_1_1Duff.php">Duff</a> *duff_ffmc, const <a class="el" href="classfirestarr_1_1fuel_1_1Duff.php">Duff</a> *duff_dmc)</td></tr>
<tr class="memdesc:ab723decfc7f0295f93b27df214b29000 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="mdescLeft">&#160;</td><td class="mdescRight">Constructor.  <a href="classfirestarr_1_1fuel_1_1FuelBase.php#ab723decfc7f0295f93b27df214b29000">More...</a><br /></td></tr>
<tr class="separator:ab723decfc7f0295f93b27df214b29000 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad3b727c825f7397cba2568434c0cd4b3 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php#ad3b727c825f7397cba2568434c0cd4b3">FuelBase</a> (<a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php">FuelBase</a> &amp;&amp;rhs) noexcept=delete</td></tr>
<tr class="separator:ad3b727c825f7397cba2568434c0cd4b3 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a40db1bff108d397961f438f01553e984 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php#a40db1bff108d397961f438f01553e984">FuelBase</a> (const <a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php">FuelBase</a> &amp;rhs)=delete</td></tr>
<tr class="separator:a40db1bff108d397961f438f01553e984 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afbcc091b6a7e60e2a78177dab1ff98d5 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php">FuelBase</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php#afbcc091b6a7e60e2a78177dab1ff98d5">operator=</a> (<a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php">FuelBase</a> &amp;&amp;rhs) noexcept=delete</td></tr>
<tr class="separator:afbcc091b6a7e60e2a78177dab1ff98d5 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aca7d7d762430c8975d3a2ead64d3faeb inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php">FuelBase</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php#aca7d7d762430c8975d3a2ead64d3faeb">operator=</a> (const <a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php">FuelBase</a> &amp;rhs)=delete</td></tr>
<tr class="separator:aca7d7d762430c8975d3a2ead64d3faeb inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a776d4f5b6532fa965a59b3931974ebef inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php#a776d4f5b6532fa965a59b3931974ebef">crownFractionBurned</a> (const double rss, const double rso) const noexcept override</td></tr>
<tr class="memdesc:a776d4f5b6532fa965a59b3931974ebef inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="mdescLeft">&#160;</td><td class="mdescRight">Crown Fraction Burned (CFB) [ST-X-3 eq 58].  <a href="classfirestarr_1_1fuel_1_1FuelBase.php#a776d4f5b6532fa965a59b3931974ebef">More...</a><br /></td></tr>
<tr class="separator:a776d4f5b6532fa965a59b3931974ebef inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8f8697c56dd0787b4a0296344dac9229 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php#a8f8697c56dd0787b4a0296344dac9229">probabilityPeat</a> (const double mc_fraction) const noexcept override</td></tr>
<tr class="memdesc:a8f8697c56dd0787b4a0296344dac9229 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="mdescLeft">&#160;</td><td class="mdescRight">Calculate probability of burning [Anderson eq 1].  <a href="classfirestarr_1_1fuel_1_1FuelBase.php#a8f8697c56dd0787b4a0296344dac9229">More...</a><br /></td></tr>
<tr class="separator:a8f8697c56dd0787b4a0296344dac9229 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a748d7f71e6cb627cdcd62045900ca491 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php#a748d7f71e6cb627cdcd62045900ca491">survivalProbability</a> (const <a class="el" href="classfirestarr_1_1wx_1_1FwiWeather.php">wx::FwiWeather</a> &amp;wx) const noexcept override</td></tr>
<tr class="memdesc:a748d7f71e6cb627cdcd62045900ca491 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="mdescLeft">&#160;</td><td class="mdescRight">Survival probability calculated using probability of ony survival based on multiple formulae.  <a href="classfirestarr_1_1fuel_1_1FuelBase.php#a748d7f71e6cb627cdcd62045900ca491">More...</a><br /></td></tr>
<tr class="separator:a748d7f71e6cb627cdcd62045900ca491 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a236c9513bedf5136e677198a4a1391f6 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memItemLeft" align="right" valign="top">constexpr const <a class="el" href="classfirestarr_1_1fuel_1_1Duff.php">Duff</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php#a236c9513bedf5136e677198a4a1391f6">duffDmcType</a> () const</td></tr>
<tr class="memdesc:a236c9513bedf5136e677198a4a1391f6 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="mdescLeft">&#160;</td><td class="mdescRight">Type of duff deeper underground.  <a href="classfirestarr_1_1fuel_1_1FuelBase.php#a236c9513bedf5136e677198a4a1391f6">More...</a><br /></td></tr>
<tr class="separator:a236c9513bedf5136e677198a4a1391f6 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a24b24d5956c90576bd1a95e9a179878c inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memItemLeft" align="right" valign="top">constexpr const <a class="el" href="classfirestarr_1_1fuel_1_1Duff.php">Duff</a> *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php#a24b24d5956c90576bd1a95e9a179878c">duffFfmcType</a> () const</td></tr>
<tr class="memdesc:a24b24d5956c90576bd1a95e9a179878c inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="mdescLeft">&#160;</td><td class="mdescRight">Type of duff near the surface.  <a href="classfirestarr_1_1fuel_1_1FuelBase.php#a24b24d5956c90576bd1a95e9a179878c">More...</a><br /></td></tr>
<tr class="separator:a24b24d5956c90576bd1a95e9a179878c inherit pub_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td colspan="2" onclick="javascript:toggleInherit('pub_methods_classfirestarr_1_1fuel_1_1FuelType')"><img src="closed.png" alt="-"/>&#160;Public Member Functions inherited from <a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php">firestarr::fuel::FuelType</a></td></tr>
<tr class="memitem:a0b9d8dddfc7ad466623343ae68d7e7b5 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memItemLeft" align="right" valign="top">virtual&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#a0b9d8dddfc7ad466623343ae68d7e7b5">~FuelType</a> () noexcept=default</td></tr>
<tr class="separator:a0b9d8dddfc7ad466623343ae68d7e7b5 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9b334abda0b4a1e526220b377fe6acc1 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memItemLeft" align="right" valign="top">constexpr&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#a9b334abda0b4a1e526220b377fe6acc1">FuelType</a> (const <a class="el" href="namespacefirestarr.php#a2cc099cdbca82a68a7d1cc6350f16453">FuelCodeSize</a> &amp;<a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#abafed0f685ef59a90afdf7af3d8ea110">code</a>, const char *<a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#a30b502469a8011c6df38119eb33736fc">name</a>, const bool can_crown) noexcept</td></tr>
<tr class="memdesc:a9b334abda0b4a1e526220b377fe6acc1 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="mdescLeft">&#160;</td><td class="mdescRight">Fuel type.  <a href="classfirestarr_1_1fuel_1_1FuelType.php#a9b334abda0b4a1e526220b377fe6acc1">More...</a><br /></td></tr>
<tr class="separator:a9b334abda0b4a1e526220b377fe6acc1 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9cc710bbae7d9a93bbd08d56195a2862 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#a9cc710bbae7d9a93bbd08d56195a2862">FuelType</a> (<a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php">FuelType</a> &amp;&amp;rhs) noexcept=delete</td></tr>
<tr class="separator:a9cc710bbae7d9a93bbd08d56195a2862 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afaa143a290ee14fd70dbda1b2484fd41 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#afaa143a290ee14fd70dbda1b2484fd41">FuelType</a> (const <a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php">FuelType</a> &amp;rhs) noexcept=delete</td></tr>
<tr class="separator:afaa143a290ee14fd70dbda1b2484fd41 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aef5fb49e8a43da07f7938b4c09506964 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php">FuelType</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#aef5fb49e8a43da07f7938b4c09506964">operator=</a> (<a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php">FuelType</a> &amp;&amp;rhs) noexcept=delete</td></tr>
<tr class="separator:aef5fb49e8a43da07f7938b4c09506964 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab08bb475a96ba2fa023ad3230f2c7092 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memItemLeft" align="right" valign="top"><a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php">FuelType</a> &amp;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#ab08bb475a96ba2fa023ad3230f2c7092">operator=</a> (const <a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php">FuelType</a> &amp;rhs) noexcept=delete</td></tr>
<tr class="separator:ab08bb475a96ba2fa023ad3230f2c7092 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a9fb1c635dad47312482465444eb12107 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memItemLeft" align="right" valign="top">constexpr bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#a9fb1c635dad47312482465444eb12107">canCrown</a> () const</td></tr>
<tr class="memdesc:a9fb1c635dad47312482465444eb12107 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="mdescLeft">&#160;</td><td class="mdescRight">Whether or not this fuel can have a crown fire.  <a href="classfirestarr_1_1fuel_1_1FuelType.php#a9fb1c635dad47312482465444eb12107">More...</a><br /></td></tr>
<tr class="separator:a9fb1c635dad47312482465444eb12107 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a30b502469a8011c6df38119eb33736fc inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memItemLeft" align="right" valign="top">constexpr const char *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#a30b502469a8011c6df38119eb33736fc">name</a> () const</td></tr>
<tr class="memdesc:a30b502469a8011c6df38119eb33736fc inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="mdescLeft">&#160;</td><td class="mdescRight">Name of the fuel.  <a href="classfirestarr_1_1fuel_1_1FuelType.php#a30b502469a8011c6df38119eb33736fc">More...</a><br /></td></tr>
<tr class="separator:a30b502469a8011c6df38119eb33736fc inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abafed0f685ef59a90afdf7af3d8ea110 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memItemLeft" align="right" valign="top">constexpr <a class="el" href="namespacefirestarr.php#a2cc099cdbca82a68a7d1cc6350f16453">FuelCodeSize</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#abafed0f685ef59a90afdf7af3d8ea110">code</a> () const</td></tr>
<tr class="memdesc:abafed0f685ef59a90afdf7af3d8ea110 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="mdescLeft">&#160;</td><td class="mdescRight">Code for this fuel type.  <a href="classfirestarr_1_1fuel_1_1FuelType.php#abafed0f685ef59a90afdf7af3d8ea110">More...</a><br /></td></tr>
<tr class="separator:abafed0f685ef59a90afdf7af3d8ea110 inherit pub_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="inherited"></a>
Additional Inherited Members</h2></td></tr>
<tr class="inherit_header pub_static_methods_classfirestarr_1_1fuel_1_1FuelBase"><td colspan="2" onclick="javascript:toggleInherit('pub_static_methods_classfirestarr_1_1fuel_1_1FuelBase')"><img src="closed.png" alt="-"/>&#160;Static Public Member Functions inherited from <a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php">firestarr::fuel::FuelBase&lt; BulkDensity, InorganicPercent, DuffDepth &gt;</a></td></tr>
<tr class="memitem:a75b7511445ecefc5115962d30e66ad06 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memItemLeft" align="right" valign="top">static constexpr double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php#a75b7511445ecefc5115962d30e66ad06">bulkDensity</a> ()</td></tr>
<tr class="memdesc:a75b7511445ecefc5115962d30e66ad06 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="mdescLeft">&#160;</td><td class="mdescRight"><a class="el" href="classfirestarr_1_1fuel_1_1Duff.php" title="Base class for DuffType.">Duff</a> Bulk Density (g/cm^3) [Anderson table 1].  <a href="classfirestarr_1_1fuel_1_1FuelBase.php#a75b7511445ecefc5115962d30e66ad06">More...</a><br /></td></tr>
<tr class="separator:a75b7511445ecefc5115962d30e66ad06 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abf5880ab684b8eaf925dba9b36edf1c7 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memItemLeft" align="right" valign="top">static constexpr double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php#abf5880ab684b8eaf925dba9b36edf1c7">inorganicPercent</a> ()</td></tr>
<tr class="memdesc:abf5880ab684b8eaf925dba9b36edf1c7 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="mdescLeft">&#160;</td><td class="mdescRight">Inorganic Percent (% / 100) [Anderson table 1].  <a href="classfirestarr_1_1fuel_1_1FuelBase.php#abf5880ab684b8eaf925dba9b36edf1c7">More...</a><br /></td></tr>
<tr class="separator:abf5880ab684b8eaf925dba9b36edf1c7 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a970b8f6f2abef383fd327e6971c9bc50 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memItemLeft" align="right" valign="top">static constexpr double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php#a970b8f6f2abef383fd327e6971c9bc50">duffDepth</a> ()</td></tr>
<tr class="memdesc:a970b8f6f2abef383fd327e6971c9bc50 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="mdescLeft">&#160;</td><td class="mdescRight">DuffDepth Depth of <a class="el" href="classfirestarr_1_1fuel_1_1Duff.php" title="Base class for DuffType.">Duff</a> layer (cm) [Anderson table 1].  <a href="classfirestarr_1_1fuel_1_1FuelBase.php#a970b8f6f2abef383fd327e6971c9bc50">More...</a><br /></td></tr>
<tr class="separator:a970b8f6f2abef383fd327e6971c9bc50 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a28f0cec23e67ced740f4f8c481b2f272 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memItemLeft" align="right" valign="top">static constexpr double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php#a28f0cec23e67ced740f4f8c481b2f272">ffmcRatio</a> ()</td></tr>
<tr class="memdesc:a28f0cec23e67ced740f4f8c481b2f272 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="mdescLeft">&#160;</td><td class="mdescRight">What fraction of the duff layer should use FFMC to determine moisture.  <a href="classfirestarr_1_1fuel_1_1FuelBase.php#a28f0cec23e67ced740f4f8c481b2f272">More...</a><br /></td></tr>
<tr class="separator:a28f0cec23e67ced740f4f8c481b2f272 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6c4b4453a76327f7dc21e9a7d7984ac9 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memItemLeft" align="right" valign="top">static constexpr double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php#a6c4b4453a76327f7dc21e9a7d7984ac9">dmcRatio</a> ()</td></tr>
<tr class="memdesc:a6c4b4453a76327f7dc21e9a7d7984ac9 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="mdescLeft">&#160;</td><td class="mdescRight">What fraction of the duff layer should use DMC to determine moisture.  <a href="classfirestarr_1_1fuel_1_1FuelBase.php#a6c4b4453a76327f7dc21e9a7d7984ac9">More...</a><br /></td></tr>
<tr class="separator:a6c4b4453a76327f7dc21e9a7d7984ac9 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelBase"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pub_static_methods_classfirestarr_1_1fuel_1_1FuelType"><td colspan="2" onclick="javascript:toggleInherit('pub_static_methods_classfirestarr_1_1fuel_1_1FuelType')"><img src="closed.png" alt="-"/>&#160;Static Public Member Functions inherited from <a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php">firestarr::fuel::FuelType</a></td></tr>
<tr class="memitem:af5a3f460d906dbd37e70ea06532c2d01 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memItemLeft" align="right" valign="top">static constexpr <a class="el" href="namespacefirestarr.php#a2cc099cdbca82a68a7d1cc6350f16453">FuelCodeSize</a>&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#af5a3f460d906dbd37e70ea06532c2d01">safeCode</a> (const <a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php">FuelType</a> *fuel)</td></tr>
<tr class="memdesc:af5a3f460d906dbd37e70ea06532c2d01 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="mdescLeft">&#160;</td><td class="mdescRight">Convert <a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php" title="An FBP fuel type.">FuelType</a> to its code, or 0 if nullptr.  <a href="classfirestarr_1_1fuel_1_1FuelType.php#af5a3f460d906dbd37e70ea06532c2d01">More...</a><br /></td></tr>
<tr class="separator:af5a3f460d906dbd37e70ea06532c2d01 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adc303bf4a936c65869ad225884338842 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memItemLeft" align="right" valign="top">static constexpr const char *&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#adc303bf4a936c65869ad225884338842">safeName</a> (const <a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php">FuelType</a> *fuel)</td></tr>
<tr class="memdesc:adc303bf4a936c65869ad225884338842 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="mdescLeft">&#160;</td><td class="mdescRight">Convert <a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php" title="An FBP fuel type.">FuelType</a> to its name, or 0 if nullptr.  <a href="classfirestarr_1_1fuel_1_1FuelType.php#adc303bf4a936c65869ad225884338842">More...</a><br /></td></tr>
<tr class="separator:adc303bf4a936c65869ad225884338842 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa255127ab1542419474b25bd7516cc93 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memItemLeft" align="right" valign="top">static constexpr double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#aa255127ab1542419474b25bd7516cc93">criticalRos</a> (const double sfc, const double csi)</td></tr>
<tr class="memdesc:aa255127ab1542419474b25bd7516cc93 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="mdescLeft">&#160;</td><td class="mdescRight">Critical rate of spread (m/min)  <a href="classfirestarr_1_1fuel_1_1FuelType.php#aa255127ab1542419474b25bd7516cc93">More...</a><br /></td></tr>
<tr class="separator:aa255127ab1542419474b25bd7516cc93 inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad9b29752ccfe987931c141043c46b70e inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memItemLeft" align="right" valign="top">static constexpr bool&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#ad9b29752ccfe987931c141043c46b70e">isCrown</a> (const double csi, const double sfi)</td></tr>
<tr class="memdesc:ad9b29752ccfe987931c141043c46b70e inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="mdescLeft">&#160;</td><td class="mdescRight">Whether or not this is a crown fire.  <a href="classfirestarr_1_1fuel_1_1FuelType.php#ad9b29752ccfe987931c141043c46b70e">More...</a><br /></td></tr>
<tr class="separator:ad9b29752ccfe987931c141043c46b70e inherit pub_static_methods_classfirestarr_1_1fuel_1_1FuelType"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pro_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td colspan="2" onclick="javascript:toggleInherit('pro_methods_classfirestarr_1_1fuel_1_1FuelConifer')"><img src="closed.png" alt="-"/>&#160;Protected Member Functions inherited from <a class="el" href="classfirestarr_1_1fuel_1_1FuelConifer.php">firestarr::fuel::FuelConifer&lt; 110, 282, 150, 64, 3, 80, 34, 0, 100 &gt;</a></td></tr>
<tr class="memitem:afad6f96669be7aac404c8598d4fb9cc7 inherit pro_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="memItemLeft" align="right" valign="top">constexpr&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelConifer.php#afad6f96669be7aac404c8598d4fb9cc7">FuelConifer</a> (const <a class="el" href="namespacefirestarr.php#a2cc099cdbca82a68a7d1cc6350f16453">FuelCodeSize</a> &amp;<a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#abafed0f685ef59a90afdf7af3d8ea110">code</a>, const char *<a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#a30b502469a8011c6df38119eb33736fc">name</a>, const <a class="el" href="classfirestarr_1_1data_1_1LogValue.php">LogValue</a> log_q, const <a class="el" href="classfirestarr_1_1fuel_1_1Duff.php">Duff</a> *duff_ffmc, const <a class="el" href="classfirestarr_1_1fuel_1_1Duff.php">Duff</a> *duff_dmc)</td></tr>
<tr class="memdesc:afad6f96669be7aac404c8598d4fb9cc7 inherit pro_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="mdescLeft">&#160;</td><td class="mdescRight">A conifer FBP fuel type.  <a href="classfirestarr_1_1fuel_1_1FuelConifer.php#afad6f96669be7aac404c8598d4fb9cc7">More...</a><br /></td></tr>
<tr class="separator:afad6f96669be7aac404c8598d4fb9cc7 inherit pro_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af2261262eef9b37d1983ff23e6c0b497 inherit pro_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="memItemLeft" align="right" valign="top">constexpr&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelConifer.php#af2261262eef9b37d1983ff23e6c0b497">FuelConifer</a> (const <a class="el" href="namespacefirestarr.php#a2cc099cdbca82a68a7d1cc6350f16453">FuelCodeSize</a> &amp;<a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#abafed0f685ef59a90afdf7af3d8ea110">code</a>, const char *<a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#a30b502469a8011c6df38119eb33736fc">name</a>, const <a class="el" href="classfirestarr_1_1data_1_1LogValue.php">LogValue</a> log_q, const <a class="el" href="classfirestarr_1_1fuel_1_1Duff.php">Duff</a> *duff)</td></tr>
<tr class="memdesc:af2261262eef9b37d1983ff23e6c0b497 inherit pro_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="mdescLeft">&#160;</td><td class="mdescRight">A conifer FBP fuel type.  <a href="classfirestarr_1_1fuel_1_1FuelConifer.php#af2261262eef9b37d1983ff23e6c0b497">More...</a><br /></td></tr>
<tr class="separator:af2261262eef9b37d1983ff23e6c0b497 inherit pro_methods_classfirestarr_1_1fuel_1_1FuelConifer"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pro_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td colspan="2" onclick="javascript:toggleInherit('pro_methods_classfirestarr_1_1fuel_1_1FuelNonMixed')"><img src="closed.png" alt="-"/>&#160;Protected Member Functions inherited from <a class="el" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php">firestarr::fuel::FuelNonMixed&lt; A, B, C, Bui0, Cbh, Cfl, BulkDensity, InorganicPercent, DuffDepth &gt;</a></td></tr>
<tr class="memitem:acd335257941e3b4780ebec5d42404f4d inherit pro_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php#acd335257941e3b4780ebec5d42404f4d">calculateIsf</a> (const <a class="el" href="classfirestarr_1_1sim_1_1SpreadInfo.php">SpreadInfo</a> &amp;spread, const double isi) const noexcept override</td></tr>
<tr class="memdesc:acd335257941e3b4780ebec5d42404f4d inherit pro_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="mdescLeft">&#160;</td><td class="mdescRight">ISI with slope influence and zero wind (ISF) [ST-X-3 eq 41].  <a href="classfirestarr_1_1fuel_1_1FuelNonMixed.php#acd335257941e3b4780ebec5d42404f4d">More...</a><br /></td></tr>
<tr class="separator:acd335257941e3b4780ebec5d42404f4d inherit pro_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a8c2bd46d5490d2127ebb168b0a338981 inherit pro_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="memItemLeft" align="right" valign="top">double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php#a8c2bd46d5490d2127ebb168b0a338981">calculateRos</a> (const int, const <a class="el" href="classfirestarr_1_1wx_1_1FwiWeather.php">wx::FwiWeather</a> &amp;, const double isi) const noexcept override</td></tr>
<tr class="memdesc:a8c2bd46d5490d2127ebb168b0a338981 inherit pro_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="mdescLeft">&#160;</td><td class="mdescRight">Initial rate of spread (m/min) [ST-X-3 eq 26].  <a href="classfirestarr_1_1fuel_1_1FuelNonMixed.php#a8c2bd46d5490d2127ebb168b0a338981">More...</a><br /></td></tr>
<tr class="separator:a8c2bd46d5490d2127ebb168b0a338981 inherit pro_methods_classfirestarr_1_1fuel_1_1FuelNonMixed"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pro_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td colspan="2" onclick="javascript:toggleInherit('pro_methods_classfirestarr_1_1fuel_1_1StandardFuel')"><img src="closed.png" alt="-"/>&#160;Protected Member Functions inherited from <a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php">firestarr::fuel::StandardFuel&lt; A, B, C, Bui0, Cbh, Cfl, BulkDensity, InorganicPercent, DuffDepth &gt;</a></td></tr>
<tr class="memitem:ad4aaaaef5db0757696cbe307437e45cd inherit pro_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#ad4aaaaef5db0757696cbe307437e45cd">~StandardFuel</a> ()=default</td></tr>
<tr class="separator:ad4aaaaef5db0757696cbe307437e45cd inherit pro_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="inherit_header pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td colspan="2" onclick="javascript:toggleInherit('pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel')"><img src="closed.png" alt="-"/>&#160;Static Protected Member Functions inherited from <a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php">firestarr::fuel::StandardFuel&lt; A, B, C, Bui0, Cbh, Cfl, BulkDensity, InorganicPercent, DuffDepth &gt;</a></td></tr>
<tr class="memitem:a1025fad5a2acba1b9db09877199e1fd8 inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">static constexpr double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#a1025fad5a2acba1b9db09877199e1fd8">bui0</a> () noexcept</td></tr>
<tr class="memdesc:a1025fad5a2acba1b9db09877199e1fd8 inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="mdescLeft">&#160;</td><td class="mdescRight">Average Build-up Index for the fuel type [ST-X-3 table 7].  <a href="classfirestarr_1_1fuel_1_1StandardFuel.php#a1025fad5a2acba1b9db09877199e1fd8">More...</a><br /></td></tr>
<tr class="separator:a1025fad5a2acba1b9db09877199e1fd8 inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5aa8abfd21d72436b780a0f99f26198b inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">static constexpr double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#a5aa8abfd21d72436b780a0f99f26198b">cbh</a> () noexcept</td></tr>
<tr class="memdesc:a5aa8abfd21d72436b780a0f99f26198b inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="mdescLeft">&#160;</td><td class="mdescRight">Crown base height (m) [ST-X-3 table 8].  <a href="classfirestarr_1_1fuel_1_1StandardFuel.php#a5aa8abfd21d72436b780a0f99f26198b">More...</a><br /></td></tr>
<tr class="separator:a5aa8abfd21d72436b780a0f99f26198b inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ad1106cc122aeab357ef5b7fee8364df3 inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">static constexpr double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#ad1106cc122aeab357ef5b7fee8364df3">cfl</a> () noexcept</td></tr>
<tr class="memdesc:ad1106cc122aeab357ef5b7fee8364df3 inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="mdescLeft">&#160;</td><td class="mdescRight">Crown fuel load (kg/m^2) [ST-X-3 table 8].  <a href="classfirestarr_1_1fuel_1_1StandardFuel.php#ad1106cc122aeab357ef5b7fee8364df3">More...</a><br /></td></tr>
<tr class="separator:ad1106cc122aeab357ef5b7fee8364df3 inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af1623e91dde59b6e3ba1a4fedc9f011e inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">static constexpr double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#af1623e91dde59b6e3ba1a4fedc9f011e">a</a> () noexcept</td></tr>
<tr class="memdesc:af1623e91dde59b6e3ba1a4fedc9f011e inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="mdescLeft">&#160;</td><td class="mdescRight">Rate of spread parameter a [ST-X-3 table 6].  <a href="classfirestarr_1_1fuel_1_1StandardFuel.php#af1623e91dde59b6e3ba1a4fedc9f011e">More...</a><br /></td></tr>
<tr class="separator:af1623e91dde59b6e3ba1a4fedc9f011e inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a6c853b012102df2e4941a5dac669cee2 inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">static constexpr double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#a6c853b012102df2e4941a5dac669cee2">negB</a> () noexcept</td></tr>
<tr class="memdesc:a6c853b012102df2e4941a5dac669cee2 inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="mdescLeft">&#160;</td><td class="mdescRight">Negative of rate of spread parameter b [ST-X-3 table 6].  <a href="classfirestarr_1_1fuel_1_1StandardFuel.php#a6c853b012102df2e4941a5dac669cee2">More...</a><br /></td></tr>
<tr class="separator:a6c853b012102df2e4941a5dac669cee2 inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a769470a141f725847552ca848ba7301d inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">static constexpr double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#a769470a141f725847552ca848ba7301d">c</a> () noexcept</td></tr>
<tr class="memdesc:a769470a141f725847552ca848ba7301d inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="mdescLeft">&#160;</td><td class="mdescRight">Rate of spread parameter c [ST-X-3 table 6].  <a href="classfirestarr_1_1fuel_1_1StandardFuel.php#a769470a141f725847552ca848ba7301d">More...</a><br /></td></tr>
<tr class="separator:a769470a141f725847552ca848ba7301d inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab7fdf24e10e7c73b20b2762aa0644b12 inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memItemLeft" align="right" valign="top">static constexpr double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#ab7fdf24e10e7c73b20b2762aa0644b12">foliarMoistureEffect</a> (const double isi, const double fmc) noexcept</td></tr>
<tr class="memdesc:ab7fdf24e10e7c73b20b2762aa0644b12 inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="mdescLeft">&#160;</td><td class="mdescRight">Crown fire spread rate (RSC) (m/min) [ST-X-3 eq 64].  <a href="classfirestarr_1_1fuel_1_1StandardFuel.php#ab7fdf24e10e7c73b20b2762aa0644b12">More...</a><br /></td></tr>
<tr class="separator:ab7fdf24e10e7c73b20b2762aa0644b12 inherit pro_static_methods_classfirestarr_1_1fuel_1_1StandardFuel"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<a name="details" id="details"></a><h2 class="groupheader">Detailed Description</h2>
<div class="textblock"><p>FBP fuel type C-2. </p>

<p class="definition">Definition at line <a class="el" href="FBP45_8h_source.php#l00700">700</a> of file <a class="el" href="FBP45_8h_source.php">FBP45.h</a>.</p>
</div><h2 class="groupheader">Constructor &amp; Destructor Documentation</h2>
<a id="a5b7766d10f5065d1ae82cb47c4d35261"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a5b7766d10f5065d1ae82cb47c4d35261">&#9670;&nbsp;</a></span>FuelC2() <span class="overload">[1/4]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">firestarr::fuel::fbp::FuelC2::FuelC2 </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a9e12f9290f85e5fd55ddfa9fe55f7fd5"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a9e12f9290f85e5fd55ddfa9fe55f7fd5">&#9670;&nbsp;</a></span>~FuelC2()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">firestarr::fuel::fbp::FuelC2::~FuelC2 </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">default</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="a05553861da7a9e8ae7b3633aea594a98"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a05553861da7a9e8ae7b3633aea594a98">&#9670;&nbsp;</a></span>FuelC2() <span class="overload">[2/4]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">firestarr::fuel::fbp::FuelC2::FuelC2 </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php">FuelC2</a> &amp;&#160;</td>
          <td class="paramname"><em>rhs</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span><span class="mlabel">noexcept</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ada1c48f3e82b895608b6848550cea55b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ada1c48f3e82b895608b6848550cea55b">&#9670;&nbsp;</a></span>FuelC2() <span class="overload">[3/4]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">firestarr::fuel::fbp::FuelC2::FuelC2 </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php">FuelC2</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>rhs</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span><span class="mlabel">noexcept</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="ab70ec0ca0c0f10df0cd2c8b46ca02810"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ab70ec0ca0c0f10df0cd2c8b46ca02810">&#9670;&nbsp;</a></span>FuelC2() <span class="overload">[4/4]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">constexpr firestarr::fuel::fbp::FuelC2::FuelC2 </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="namespacefirestarr.php#a2cc099cdbca82a68a7d1cc6350f16453">FuelCodeSize</a> &amp;&#160;</td>
          <td class="paramname"><em>code</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">inline</span><span class="mlabel">explicit</span><span class="mlabel">constexpr</span><span class="mlabel">noexcept</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>FBP fuel type C-2. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">code</td><td>Code to identify fuel with </td></tr>
  </table>
  </dd>
</dl>

<p class="definition">Definition at line <a class="el" href="FBP45_8h_source.php#l00713">713</a> of file <a class="el" href="FBP45_8h_source.php">FBP45.h</a>.</p>

</div>
</div>
<h2 class="groupheader">Member Function Documentation</h2>
<a id="ad187f8e3ead64b5a18060e3d3a753902"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ad187f8e3ead64b5a18060e3d3a753902">&#9670;&nbsp;</a></span>operator=() <span class="overload">[1/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php">FuelC2</a>&amp; firestarr::fuel::fbp::FuelC2::operator= </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php">FuelC2</a> &amp;&#160;</td>
          <td class="paramname"><em>rhs</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span><span class="mlabel">noexcept</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="af42f6e6702ff255296d7b1cb5898353c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af42f6e6702ff255296d7b1cb5898353c">&#9670;&nbsp;</a></span>operator=() <span class="overload">[2/2]</span></h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php">FuelC2</a>&amp; firestarr::fuel::fbp::FuelC2::operator= </td>
          <td>(</td>
          <td class="paramtype"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php">FuelC2</a> &amp;&amp;&#160;</td>
          <td class="paramname"><em>rhs</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">delete</span><span class="mlabel">noexcept</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

</div>
</div>
<a id="aab7326f75775c1055abb9d8412267f73"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aab7326f75775c1055abb9d8412267f73">&#9670;&nbsp;</a></span>surfaceFuelConsumption()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">double firestarr::fuel::fbp::FuelC2::surfaceFuelConsumption </td>
          <td>(</td>
          <td class="paramtype">const <a class="el" href="classfirestarr_1_1sim_1_1SpreadInfo.php">SpreadInfo</a> &amp;&#160;</td>
          <td class="paramname"><em>spread</em></td><td>)</td>
          <td> const</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">override</span><span class="mlabel">virtual</span><span class="mlabel">noexcept</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Surface Fuel Consumption (SFC) (kg/m^2) [ST-X-3 eq 10]. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">spread</td><td>SpreadInfo to use </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Surface Fuel Consumption (SFC) (kg/m^2) [ST-X-3 eq 10] </dd></dl>

<p>Implements <a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#a8f3010d1b2fb22d7b8c4c0cd53d72374">firestarr::fuel::FuelType</a>.</p>

<p class="definition">Definition at line <a class="el" href="FBP45_8cpp_source.php#l00053">53</a> of file <a class="el" href="FBP45_8cpp_source.php">FBP45.cpp</a>.</p>

</div>
</div>
<hr/>The documentation for this class was generated from the following files:<ul>
<li>FireSTARR/src/<a class="el" href="FBP45_8h_source.php">FBP45.h</a></li>
<li>FireSTARR/src/<a class="el" href="FBP45_8cpp_source.php">FBP45.cpp</a></li>
</ul>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
