<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>FireSTARR: FireSTARR/src/Duff.cpp File Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">FireSTARR
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.php');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_4d88195d9c9596897c1a7e6e6c1a3b9e.php">FireSTARR</a></li><li class="navelem"><a class="el" href="dir_fee61d26c5aa45e5f9c842f18eee2357.php">src</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#namespaces">Namespaces</a>  </div>
  <div class="headertitle">
<div class="title">Duff.cpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="stdafx_8h_source.php">stdafx.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="Duff_8h_source.php">Duff.h</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Duff.cpp:</div>
<div class="dyncontent">
<div class="center"><img src="Duff_8cpp__incl.png" border="0" usemap="#aFireSTARR_2src_2Duff_8cpp" alt=""/></div>
<map name="aFireSTARR_2src_2Duff_8cpp" id="aFireSTARR_2src_2Duff_8cpp">
<area shape="rect" title=" " alt="" coords="2581,5,2743,32"/>
<area shape="rect" href="stdafx_8h.php" title=" " alt="" coords="2209,304,2275,331"/>
<area shape="rect" href="Duff_8h.php" title=" " alt="" coords="2680,80,2735,107"/>
<area shape="rect" title=" " alt="" coords="2780,379,2835,405"/>
<area shape="rect" title=" " alt="" coords="2859,379,2921,405"/>
<area shape="rect" title=" " alt="" coords="2945,379,3019,405"/>
<area shape="rect" title=" " alt="" coords="3043,379,3094,405"/>
<area shape="rect" title=" " alt="" coords="3118,379,3179,405"/>
<area shape="rect" title=" " alt="" coords="3204,379,3269,405"/>
<area shape="rect" title=" " alt="" coords="3294,379,3353,405"/>
<area shape="rect" title=" " alt="" coords="3377,379,3435,405"/>
<area shape="rect" title=" " alt="" coords="3460,379,3525,405"/>
<area shape="rect" title=" " alt="" coords="3549,379,3607,405"/>
<area shape="rect" title=" " alt="" coords="3631,379,3698,405"/>
<area shape="rect" title=" " alt="" coords="3723,379,3801,405"/>
<area shape="rect" title=" " alt="" coords="5,379,60,405"/>
<area shape="rect" title=" " alt="" coords="85,379,151,405"/>
<area shape="rect" title=" " alt="" coords="175,379,247,405"/>
<area shape="rect" title=" " alt="" coords="272,379,335,405"/>
<area shape="rect" title=" " alt="" coords="359,379,413,405"/>
<area shape="rect" title=" " alt="" coords="437,379,476,405"/>
<area shape="rect" title=" " alt="" coords="501,379,639,405"/>
<area shape="rect" title=" " alt="" coords="663,379,719,405"/>
<area shape="rect" title=" " alt="" coords="744,379,791,405"/>
<area shape="rect" title=" " alt="" coords="815,379,883,405"/>
<area shape="rect" title=" " alt="" coords="907,379,988,405"/>
<area shape="rect" title=" " alt="" coords="1013,379,1111,405"/>
<area shape="rect" title=" " alt="" coords="1136,379,1201,405"/>
<area shape="rect" title=" " alt="" coords="1225,379,1265,405"/>
<area shape="rect" title=" " alt="" coords="1289,379,1339,405"/>
<area shape="rect" title=" " alt="" coords="1363,379,1430,405"/>
<area shape="rect" title=" " alt="" coords="1454,379,1534,405"/>
<area shape="rect" title=" " alt="" coords="1558,379,1627,405"/>
<area shape="rect" title=" " alt="" coords="1651,379,1715,405"/>
<area shape="rect" title=" " alt="" coords="3909,379,3964,405"/>
<area shape="rect" title=" " alt="" coords="1739,379,1803,405"/>
<area shape="rect" title=" " alt="" coords="1827,379,1915,405"/>
<area shape="rect" title=" " alt="" coords="3988,379,4099,405"/>
<area shape="rect" title=" " alt="" coords="4123,379,4175,405"/>
<area shape="rect" title=" " alt="" coords="3826,379,3885,405"/>
<area shape="rect" title=" " alt="" coords="1939,379,2094,405"/>
<area shape="rect" title=" " alt="" coords="2118,379,2225,405"/>
<area shape="rect" title=" " alt="" coords="2249,379,2379,405"/>
<area shape="rect" title=" " alt="" coords="2404,379,2451,405"/>
<area shape="rect" title=" " alt="" coords="2475,379,2529,405"/>
<area shape="rect" title=" " alt="" coords="2553,379,2653,405"/>
<area shape="rect" title=" " alt="" coords="2677,379,2756,405"/>
<area shape="rect" href="LookupTable_8h.php" title=" " alt="" coords="3463,155,3570,181"/>
<area shape="rect" href="Util_8h.php" title=" " alt="" coords="3869,229,3921,256"/>
</map>
</div>
</div>
<p><a href="Duff_8cpp_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:namespacefirestarr"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr.php">firestarr</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:namespacefirestarr_1_1fuel"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1fuel.php">firestarr::fuel</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
