<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>FireSTARR: FireSTARR/src/Environment.cpp File Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">FireSTARR
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.php');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_4d88195d9c9596897c1a7e6e6c1a3b9e.php">FireSTARR</a></li><li class="navelem"><a class="el" href="dir_fee61d26c5aa45e5f9c842f18eee2357.php">src</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#namespaces">Namespaces</a> &#124;
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">Environment.cpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="stdafx_8h_source.php">stdafx.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="Environment_8h_source.php">Environment.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="EnvironmentInfo_8h_source.php">EnvironmentInfo.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="FuelLookup_8h_source.php">FuelLookup.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="ProbabilityMap_8h_source.php">ProbabilityMap.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="Scenario_8h_source.php">Scenario.h</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Environment.cpp:</div>
<div class="dyncontent">
<div class="center"><img src="Environment_8cpp__incl.png" border="0" usemap="#aFireSTARR_2src_2Environment_8cpp" alt=""/></div>
<map name="aFireSTARR_2src_2Environment_8cpp" id="aFireSTARR_2src_2Environment_8cpp">
<area shape="rect" title=" " alt="" coords="3709,5,3920,32"/>
<area shape="rect" href="stdafx_8h.php" title=" " alt="" coords="2156,155,2223,181"/>
<area shape="rect" href="Environment_8h.php" title=" " alt="" coords="3731,155,3835,181"/>
<area shape="rect" href="EnvironmentInfo_8h.php" title=" " alt="" coords="3802,80,3929,107"/>
<area shape="rect" href="FuelLookup_8h.php" title=" " alt="" coords="3910,155,4010,181"/>
<area shape="rect" href="ProbabilityMap_8h.php" title=" " alt="" coords="4085,155,4203,181"/>
<area shape="rect" href="Scenario_8h.php" title=" " alt="" coords="3624,155,3707,181"/>
<area shape="rect" title=" " alt="" coords="1261,229,1315,256"/>
<area shape="rect" title=" " alt="" coords="1340,229,1401,256"/>
<area shape="rect" title=" " alt="" coords="3603,229,3677,256"/>
<area shape="rect" title=" " alt="" coords="1425,229,1476,256"/>
<area shape="rect" title=" " alt="" coords="1500,229,1561,256"/>
<area shape="rect" title=" " alt="" coords="1586,229,1651,256"/>
<area shape="rect" title=" " alt="" coords="1676,229,1735,256"/>
<area shape="rect" title=" " alt="" coords="1759,229,1817,256"/>
<area shape="rect" title=" " alt="" coords="1842,229,1907,256"/>
<area shape="rect" title=" " alt="" coords="1931,229,1989,256"/>
<area shape="rect" title=" " alt="" coords="2013,229,2080,256"/>
<area shape="rect" title=" " alt="" coords="2105,229,2183,256"/>
<area shape="rect" title=" " alt="" coords="2207,229,2262,256"/>
<area shape="rect" title=" " alt="" coords="2287,229,2353,256"/>
<area shape="rect" title=" " alt="" coords="2377,229,2449,256"/>
<area shape="rect" title=" " alt="" coords="2474,229,2537,256"/>
<area shape="rect" title=" " alt="" coords="2561,229,2615,256"/>
<area shape="rect" title=" " alt="" coords="3541,229,3579,256"/>
<area shape="rect" title=" " alt="" coords="2639,229,2777,256"/>
<area shape="rect" title=" " alt="" coords="2801,229,2857,256"/>
<area shape="rect" title=" " alt="" coords="3470,229,3517,256"/>
<area shape="rect" title=" " alt="" coords="3926,229,3994,256"/>
<area shape="rect" title=" " alt="" coords="2882,229,2963,256"/>
<area shape="rect" title=" " alt="" coords="2988,229,3087,256"/>
<area shape="rect" title=" " alt="" coords="3111,229,3177,256"/>
<area shape="rect" title=" " alt="" coords="3779,229,3819,256"/>
<area shape="rect" title=" " alt="" coords="3201,229,3250,256"/>
<area shape="rect" title=" " alt="" coords="3275,229,3341,256"/>
<area shape="rect" title=" " alt="" coords="3365,229,3445,256"/>
<area shape="rect" title=" " alt="" coords="5,229,75,256"/>
<area shape="rect" title=" " alt="" coords="99,229,163,256"/>
<area shape="rect" title=" " alt="" coords="4018,229,4073,256"/>
<area shape="rect" title=" " alt="" coords="187,229,251,256"/>
<area shape="rect" title=" " alt="" coords="275,229,363,256"/>
<area shape="rect" title=" " alt="" coords="387,229,498,256"/>
<area shape="rect" title=" " alt="" coords="3702,229,3754,256"/>
<area shape="rect" title=" " alt="" coords="3843,229,3901,256"/>
<area shape="rect" title=" " alt="" coords="523,229,677,256"/>
<area shape="rect" title=" " alt="" coords="701,229,808,256"/>
<area shape="rect" title=" " alt="" coords="832,229,963,256"/>
<area shape="rect" title=" " alt="" coords="987,229,1034,256"/>
<area shape="rect" title=" " alt="" coords="1058,229,1113,256"/>
<area shape="rect" title=" " alt="" coords="1137,229,1237,256"/>
</map>
</div>
</div>
<p><a href="Environment_8cpp_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:namespacefirestarr"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr.php">firestarr</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:namespacefirestarr_1_1topo"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1topo.php">firestarr::topo</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a03d701e836ff628b6b907683e7ff656e"><td class="memTemplParams" colspan="2">template&lt;class V , class T  = V&gt; </td></tr>
<tr class="memitem:a03d701e836ff628b6b907683e7ff656e"><td class="memTemplItemLeft" align="right" valign="top">static V&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1topo.php#a03d701e836ff628b6b907683e7ff656e">firestarr::topo::read_tiff_point</a> (TIFF *tif, GTIF *gtif, const Point &amp;point, std::function&lt; T(int, int)&gt; convert)</td></tr>
<tr class="separator:a03d701e836ff628b6b907683e7ff656e"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a17f5d889fd9feaa0889498b7fb52e859"><td class="memTemplParams" colspan="2">template&lt;class V , class T  = V&gt; </td></tr>
<tr class="memitem:a17f5d889fd9feaa0889498b7fb52e859"><td class="memTemplItemLeft" align="right" valign="top">static V&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1topo.php#a17f5d889fd9feaa0889498b7fb52e859">firestarr::topo::read_tiff_point</a> (const string &amp;filename, const Point &amp;point, std::function&lt; T(int, int)&gt; convert)</td></tr>
<tr class="separator:a17f5d889fd9feaa0889498b7fb52e859"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5781653e1bc7a9e0730ee9373ed29569"><td class="memTemplParams" colspan="2">template&lt;class T &gt; </td></tr>
<tr class="memitem:a5781653e1bc7a9e0730ee9373ed29569"><td class="memTemplItemLeft" align="right" valign="top">static T&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1topo.php#a5781653e1bc7a9e0730ee9373ed29569">firestarr::topo::read_tiff_point</a> (const string &amp;filename, const Point &amp;point)</td></tr>
<tr class="separator:a5781653e1bc7a9e0730ee9373ed29569"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
