<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>FireSTARR: FireSTARR/src/Environment.h File Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">FireSTARR
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.php');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_4d88195d9c9596897c1a7e6e6c1a3b9e.php">FireSTARR</a></li><li class="navelem"><a class="el" href="dir_fee61d26c5aa45e5f9c842f18eee2357.php">src</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#namespaces">Namespaces</a> &#124;
<a href="#typedef-members">Typedefs</a>  </div>
  <div class="headertitle">
<div class="title">Environment.h File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &lt;algorithm&gt;</code><br />
<code>#include &lt;execution&gt;</code><br />
<code>#include &lt;memory&gt;</code><br />
<code>#include &lt;string&gt;</code><br />
<code>#include &lt;utility&gt;</code><br />
<code>#include &lt;vector&gt;</code><br />
<code>#include &quot;<a class="el" href="Cell_8h_source.php">Cell.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="ConstantGrid_8h_source.php">ConstantGrid.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="Event_8h_source.php">Event.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="FuelType_8h_source.php">FuelType.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="GridMap_8h_source.php">GridMap.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="IntensityMap_8h_source.php">IntensityMap.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="Point_8h_source.php">Point.h</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Environment.h:</div>
<div class="dyncontent">
<div class="center"><img src="Environment_8h__incl.png" border="0" usemap="#aFireSTARR_2src_2Environment_8h" alt=""/></div>
<map name="aFireSTARR_2src_2Environment_8h" id="aFireSTARR_2src_2Environment_8h">
<area shape="rect" title=" " alt="" coords="2223,5,2419,32"/>
<area shape="rect" title=" " alt="" coords="98,528,173,555"/>
<area shape="rect" title=" " alt="" coords="3067,80,3145,107"/>
<area shape="rect" title=" " alt="" coords="5,528,73,555"/>
<area shape="rect" title=" " alt="" coords="2604,528,2659,555"/>
<area shape="rect" title=" " alt="" coords="2683,528,2735,555"/>
<area shape="rect" title=" " alt="" coords="2895,528,2954,555"/>
<area shape="rect" href="Cell_8h.php" title=" " alt="" coords="1955,229,2009,256"/>
<area shape="rect" href="ConstantGrid_8h.php" title=" " alt="" coords="2359,155,2467,181"/>
<area shape="rect" href="Point_8h.php" title=" " alt="" coords="2340,304,2403,331"/>
<area shape="rect" href="Event_8h.php" title=" " alt="" coords="1949,155,2015,181"/>
<area shape="rect" href="FuelType_8h.php" title=" " alt="" coords="3017,379,3102,405"/>
<area shape="rect" href="GridMap_8h.php" title=" " alt="" coords="1648,155,1729,181"/>
<area shape="rect" href="IntensityMap_8h.php" title=" " alt="" coords="1635,80,1742,107"/>
<area shape="rect" title=" " alt="" coords="259,528,313,555"/>
<area shape="rect" href="Location_8h.php" title=" " alt="" coords="1979,304,2062,331"/>
<area shape="rect" href="Util_8h.php" title=" " alt="" coords="2129,379,2181,405"/>
<area shape="rect" href="stdafx_8h.php" title=" " alt="" coords="1689,453,1755,480"/>
<area shape="rect" title=" " alt="" coords="2469,528,2580,555"/>
<area shape="rect" title=" " alt="" coords="1352,528,1407,555"/>
<area shape="rect" title=" " alt="" coords="1431,528,1493,555"/>
<area shape="rect" title=" " alt="" coords="1517,528,1567,555"/>
<area shape="rect" title=" " alt="" coords="1591,528,1653,555"/>
<area shape="rect" title=" " alt="" coords="1677,528,1743,555"/>
<area shape="rect" title=" " alt="" coords="1767,528,1826,555"/>
<area shape="rect" title=" " alt="" coords="1850,528,1909,555"/>
<area shape="rect" title=" " alt="" coords="1933,528,1999,555"/>
<area shape="rect" title=" " alt="" coords="2023,528,2080,555"/>
<area shape="rect" title=" " alt="" coords="2105,528,2171,555"/>
<area shape="rect" title=" " alt="" coords="2196,528,2275,555"/>
<area shape="rect" title=" " alt="" coords="2299,528,2353,555"/>
<area shape="rect" title=" " alt="" coords="2378,528,2445,555"/>
<area shape="rect" title=" " alt="" coords="337,528,409,555"/>
<area shape="rect" title=" " alt="" coords="433,528,496,555"/>
<area shape="rect" title=" " alt="" coords="196,528,235,555"/>
<area shape="rect" title=" " alt="" coords="521,528,659,555"/>
<area shape="rect" title=" " alt="" coords="683,528,739,555"/>
<area shape="rect" title=" " alt="" coords="2824,528,2871,555"/>
<area shape="rect" title=" " alt="" coords="764,528,845,555"/>
<area shape="rect" title=" " alt="" coords="870,528,969,555"/>
<area shape="rect" title=" " alt="" coords="993,528,1059,555"/>
<area shape="rect" title=" " alt="" coords="2759,528,2799,555"/>
<area shape="rect" title=" " alt="" coords="1083,528,1132,555"/>
<area shape="rect" title=" " alt="" coords="1157,528,1223,555"/>
<area shape="rect" title=" " alt="" coords="1247,528,1327,555"/>
<area shape="rect" href="Grid_8h.php" title=" " alt="" coords="2223,229,2279,256"/>
<area shape="rect" href="Log_8h.php" title=" " alt="" coords="2979,528,3033,555"/>
<area shape="rect" href="Duff_8h.php" title=" " alt="" coords="3032,453,3087,480"/>
<area shape="rect" href="FireWeather_8h.php" title=" " alt="" coords="2796,453,2899,480"/>
<area shape="rect" title=" " alt="" coords="1569,155,1624,181"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="Environment_8h__dep__incl.png" border="0" usemap="#aFireSTARR_2src_2Environment_8hdep" alt=""/></div>
<map name="aFireSTARR_2src_2Environment_8hdep" id="aFireSTARR_2src_2Environment_8hdep">
<area shape="rect" title=" " alt="" coords="157,5,353,32"/>
<area shape="rect" href="Environment_8cpp.php" title=" " alt="" coords="150,259,361,285"/>
<area shape="rect" href="EnvironmentInfo_8cpp.php" title=" " alt="" coords="31,169,218,211"/>
<area shape="rect" href="EnvironmentInfo_8h.php" title=" " alt="" coords="162,80,349,121"/>
<area shape="rect" href="Model_8h.php" title=" " alt="" coords="487,87,645,114"/>
<area shape="rect" href="Perimeter_8cpp.php" title=" " alt="" coords="670,87,865,114"/>
<area shape="rect" href="IntensityMap_8cpp.php" title=" " alt="" coords="292,177,504,203"/>
<area shape="rect" href="Main_8cpp.php" title=" " alt="" coords="543,259,709,285"/>
<area shape="rect" href="Model_8cpp.php" title=" " alt="" coords="661,333,834,360"/>
<area shape="rect" href="ProbabilityMap_8cpp.php" title=" " alt="" coords="629,169,804,211"/>
<area shape="rect" href="Scenario_8h.php" title=" " alt="" coords="900,177,1075,203"/>
<area shape="rect" href="Test_8cpp.php" title=" " alt="" coords="1456,333,1620,360"/>
<area shape="rect" href="FireSpread_8cpp.php" title=" " alt="" coords="785,259,987,285"/>
<area shape="rect" href="Iteration_8cpp.php" title=" " alt="" coords="1264,259,1449,285"/>
<area shape="rect" href="Observer_8cpp.php" title=" " alt="" coords="953,333,1144,360"/>
<area shape="rect" href="Observer_8h.php" title=" " alt="" coords="1063,259,1240,285"/>
<area shape="rect" href="Scenario_8cpp.php" title=" " alt="" coords="1194,333,1383,360"/>
</map>
</div>
</div>
<p><a href="Environment_8h_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1topo_1_1Environment.php">firestarr::topo::Environment</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">The area that a Model is run for, with Fuel, Slope, and Aspect grids.  <a href="classfirestarr_1_1topo_1_1Environment.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:namespacefirestarr"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr.php">firestarr</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:namespacefirestarr_1_1topo"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1topo.php">firestarr::topo</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="typedef-members"></a>
Typedefs</h2></td></tr>
<tr class="memitem:a2780a801cb8082fe3771ece093a709fd"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1topo.php#a2780a801cb8082fe3771ece093a709fd">firestarr::topo::FuelGrid</a> = data::ConstantGrid&lt; const fuel::FuelType *, FuelSize &gt;</td></tr>
<tr class="separator:a2780a801cb8082fe3771ece093a709fd"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a74ca51e8ab237ba6e4cb990468d9a9ce"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1topo.php#a74ca51e8ab237ba6e4cb990468d9a9ce">firestarr::topo::SlopeGrid</a> = data::ConstantGrid&lt; SlopeSize &gt;</td></tr>
<tr class="separator:a74ca51e8ab237ba6e4cb990468d9a9ce"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a539e522def0c3e7819340f160b909742"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1topo.php#a539e522def0c3e7819340f160b909742">firestarr::topo::AspectGrid</a> = data::ConstantGrid&lt; AspectSize &gt;</td></tr>
<tr class="separator:a539e522def0c3e7819340f160b909742"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a2beaace21c7fe97e8ffd89aa02fe09bf"><td class="memItemLeft" align="right" valign="top">using&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1topo.php#a2beaace21c7fe97e8ffd89aa02fe09bf">firestarr::topo::ElevationGrid</a> = data::ConstantGrid&lt; ElevationSize &gt;</td></tr>
<tr class="separator:a2beaace21c7fe97e8ffd89aa02fe09bf"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
