<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>FireSTARR: FireSTARR/src/Event.h File Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">FireSTARR
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.php');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_4d88195d9c9596897c1a7e6e6c1a3b9e.php">FireSTARR</a></li><li class="navelem"><a class="el" href="dir_fee61d26c5aa45e5f9c842f18eee2357.php">src</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#namespaces">Namespaces</a>  </div>
  <div class="headertitle">
<div class="title">Event.h File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="stdafx_8h_source.php">stdafx.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="Cell_8h_source.php">Cell.h</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Event.h:</div>
<div class="dyncontent">
<div class="center"><img src="Event_8h__incl.png" border="0" usemap="#aFireSTARR_2src_2Event_8h" alt=""/></div>
<map name="aFireSTARR_2src_2Event_8h" id="aFireSTARR_2src_2Event_8h">
<area shape="rect" title=" " alt="" coords="1881,5,2039,32"/>
<area shape="rect" href="stdafx_8h.php" title=" " alt="" coords="2016,304,2083,331"/>
<area shape="rect" href="Cell_8h.php" title=" " alt="" coords="2885,80,2939,107"/>
<area shape="rect" title=" " alt="" coords="83,379,138,405"/>
<area shape="rect" title=" " alt="" coords="163,379,224,405"/>
<area shape="rect" title=" " alt="" coords="248,379,323,405"/>
<area shape="rect" title=" " alt="" coords="347,379,397,405"/>
<area shape="rect" title=" " alt="" coords="421,379,483,405"/>
<area shape="rect" title=" " alt="" coords="507,379,573,405"/>
<area shape="rect" title=" " alt="" coords="597,379,656,405"/>
<area shape="rect" title=" " alt="" coords="680,379,739,405"/>
<area shape="rect" title=" " alt="" coords="763,379,829,405"/>
<area shape="rect" title=" " alt="" coords="853,379,910,405"/>
<area shape="rect" title=" " alt="" coords="935,379,1001,405"/>
<area shape="rect" title=" " alt="" coords="1026,379,1105,405"/>
<area shape="rect" title=" " alt="" coords="1129,379,1183,405"/>
<area shape="rect" title=" " alt="" coords="1208,379,1275,405"/>
<area shape="rect" title=" " alt="" coords="1299,379,1371,405"/>
<area shape="rect" title=" " alt="" coords="1395,379,1458,405"/>
<area shape="rect" title=" " alt="" coords="5,379,59,405"/>
<area shape="rect" title=" " alt="" coords="1482,379,1521,405"/>
<area shape="rect" title=" " alt="" coords="1545,379,1684,405"/>
<area shape="rect" title=" " alt="" coords="1708,379,1764,405"/>
<area shape="rect" title=" " alt="" coords="1789,379,1835,405"/>
<area shape="rect" title=" " alt="" coords="1859,379,1927,405"/>
<area shape="rect" title=" " alt="" coords="1951,379,2033,405"/>
<area shape="rect" title=" " alt="" coords="2057,379,2156,405"/>
<area shape="rect" title=" " alt="" coords="2181,379,2246,405"/>
<area shape="rect" title=" " alt="" coords="2269,379,2309,405"/>
<area shape="rect" title=" " alt="" coords="2334,379,2383,405"/>
<area shape="rect" title=" " alt="" coords="2408,379,2475,405"/>
<area shape="rect" title=" " alt="" coords="2499,379,2579,405"/>
<area shape="rect" title=" " alt="" coords="2603,379,2672,405"/>
<area shape="rect" title=" " alt="" coords="2696,379,2760,405"/>
<area shape="rect" title=" " alt="" coords="3825,379,3879,405"/>
<area shape="rect" title=" " alt="" coords="2784,379,2848,405"/>
<area shape="rect" title=" " alt="" coords="2872,379,2960,405"/>
<area shape="rect" title=" " alt="" coords="3903,379,4014,405"/>
<area shape="rect" title=" " alt="" coords="4038,379,4090,405"/>
<area shape="rect" title=" " alt="" coords="4115,379,4173,405"/>
<area shape="rect" title=" " alt="" coords="2984,379,3139,405"/>
<area shape="rect" title=" " alt="" coords="3163,379,3269,405"/>
<area shape="rect" title=" " alt="" coords="3293,379,3424,405"/>
<area shape="rect" title=" " alt="" coords="3449,379,3495,405"/>
<area shape="rect" title=" " alt="" coords="3519,379,3574,405"/>
<area shape="rect" title=" " alt="" coords="3598,379,3698,405"/>
<area shape="rect" title=" " alt="" coords="3722,379,3801,405"/>
<area shape="rect" href="Location_8h.php" title=" " alt="" coords="3044,155,3127,181"/>
<area shape="rect" href="Util_8h.php" title=" " alt="" coords="3826,229,3878,256"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="Event_8h__dep__incl.png" border="0" usemap="#aFireSTARR_2src_2Event_8hdep" alt=""/></div>
<map name="aFireSTARR_2src_2Event_8hdep" id="aFireSTARR_2src_2Event_8hdep">
<area shape="rect" title=" " alt="" coords="1430,5,1587,32"/>
<area shape="rect" href="Environment_8h.php" title=" " alt="" coords="1411,80,1607,107"/>
<area shape="rect" href="Observer_8cpp.php" title=" " alt="" coords="1325,408,1516,435"/>
<area shape="rect" href="Observer_8h.php" title=" " alt="" coords="1269,333,1447,360"/>
<area shape="rect" href="Scenario_8cpp.php" title=" " alt="" coords="1541,408,1730,435"/>
<area shape="rect" href="EventCompare_8h.php" title=" " alt="" coords="992,80,1201,107"/>
<area shape="rect" href="Environment_8cpp.php" title=" " alt="" coords="1573,333,1783,360"/>
<area shape="rect" href="EnvironmentInfo_8cpp.php" title=" " alt="" coords="1426,244,1613,285"/>
<area shape="rect" href="EnvironmentInfo_8h.php" title=" " alt="" coords="1546,155,1733,196"/>
<area shape="rect" href="Model_8h.php" title=" " alt="" coords="424,162,583,189"/>
<area shape="rect" href="Perimeter_8cpp.php" title=" " alt="" coords="1277,162,1471,189"/>
<area shape="rect" href="IntensityMap_8cpp.php" title=" " alt="" coords="204,251,416,278"/>
<area shape="rect" href="Main_8cpp.php" title=" " alt="" coords="541,333,708,360"/>
<area shape="rect" href="Model_8cpp.php" title=" " alt="" coords="587,408,761,435"/>
<area shape="rect" href="ProbabilityMap_8cpp.php" title=" " alt="" coords="5,244,180,285"/>
<area shape="rect" href="Scenario_8h.php" title=" " alt="" coords="1009,251,1184,278"/>
<area shape="rect" href="Test_8cpp.php" title=" " alt="" coords="785,408,949,435"/>
<area shape="rect" href="FireSpread_8cpp.php" title=" " alt="" coords="835,333,1036,360"/>
<area shape="rect" href="Iteration_8cpp.php" title=" " alt="" coords="1060,333,1245,360"/>
</map>
</div>
</div>
<p><a href="Event_8h_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1sim_1_1Event.php">firestarr::sim::Event</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">A specific <a class="el" href="classfirestarr_1_1sim_1_1Event.php" title="A specific Event scheduled in a specific Scenario.">Event</a> scheduled in a specific <a class="el" href="classfirestarr_1_1sim_1_1Scenario.php" title="A single Scenario in an Iteration using a specific FireWeather stream.">Scenario</a>.  <a href="classfirestarr_1_1sim_1_1Event.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:namespacefirestarr"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr.php">firestarr</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:namespacefirestarr_1_1sim"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1sim.php">firestarr::sim</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
