<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>FireSTARR: FireSTARR/src/FireSpread.h File Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">FireSTARR
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.php');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_4d88195d9c9596897c1a7e6e6c1a3b9e.php">FireSTARR</a></li><li class="navelem"><a class="el" href="dir_fee61d26c5aa45e5f9c842f18eee2357.php">src</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#namespaces">Namespaces</a> &#124;
<a href="#enum-members">Enumerations</a> &#124;
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">FireSpread.h File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="Cell_8h_source.php">Cell.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="FWI_8h_source.php">FWI.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="Point_8h_source.php">Point.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="Settings_8h_source.php">Settings.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="Util_8h_source.php">Util.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="InnerPos_8h_source.php">InnerPos.h</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for FireSpread.h:</div>
<div class="dyncontent">
<div class="center"><img src="FireSpread_8h__incl.png" border="0" usemap="#aFireSTARR_2src_2FireSpread_8h" alt=""/></div>
<map name="aFireSTARR_2src_2FireSpread_8h" id="aFireSTARR_2src_2FireSpread_8h">
<area shape="rect" title=" " alt="" coords="2627,5,2813,32"/>
<area shape="rect" href="Cell_8h.php" title=" " alt="" coords="2477,80,2531,107"/>
<area shape="rect" href="Util_8h.php" title=" " alt="" coords="2525,229,2577,256"/>
<area shape="rect" href="FWI_8h.php" title=" " alt="" coords="2651,80,2707,107"/>
<area shape="rect" href="Point_8h.php" title=" " alt="" coords="2731,80,2794,107"/>
<area shape="rect" href="Settings_8h.php" title=" " alt="" coords="2872,155,2952,181"/>
<area shape="rect" href="InnerPos_8h.php" title=" " alt="" coords="2870,80,2954,107"/>
<area shape="rect" title=" " alt="" coords="5,379,59,405"/>
<area shape="rect" href="Location_8h.php" title=" " alt="" coords="2431,155,2513,181"/>
<area shape="rect" href="stdafx_8h.php" title=" " alt="" coords="1816,304,1883,331"/>
<area shape="rect" title=" " alt="" coords="3505,379,3559,405"/>
<area shape="rect" title=" " alt="" coords="83,379,194,405"/>
<area shape="rect" title=" " alt="" coords="218,379,270,405"/>
<area shape="rect" title=" " alt="" coords="3584,379,3643,405"/>
<area shape="rect" title=" " alt="" coords="2654,379,2709,405"/>
<area shape="rect" title=" " alt="" coords="2733,379,2795,405"/>
<area shape="rect" title=" " alt="" coords="2819,379,2893,405"/>
<area shape="rect" title=" " alt="" coords="2917,379,2968,405"/>
<area shape="rect" title=" " alt="" coords="2992,379,3053,405"/>
<area shape="rect" title=" " alt="" coords="3078,379,3143,405"/>
<area shape="rect" title=" " alt="" coords="3168,379,3227,405"/>
<area shape="rect" title=" " alt="" coords="3251,379,3309,405"/>
<area shape="rect" title=" " alt="" coords="3334,379,3399,405"/>
<area shape="rect" title=" " alt="" coords="3423,379,3481,405"/>
<area shape="rect" title=" " alt="" coords="295,379,361,405"/>
<area shape="rect" title=" " alt="" coords="386,379,465,405"/>
<area shape="rect" title=" " alt="" coords="489,379,543,405"/>
<area shape="rect" title=" " alt="" coords="568,379,635,405"/>
<area shape="rect" title=" " alt="" coords="659,379,731,405"/>
<area shape="rect" title=" " alt="" coords="755,379,818,405"/>
<area shape="rect" title=" " alt="" coords="842,379,881,405"/>
<area shape="rect" title=" " alt="" coords="905,379,1044,405"/>
<area shape="rect" title=" " alt="" coords="1068,379,1124,405"/>
<area shape="rect" title=" " alt="" coords="1149,379,1195,405"/>
<area shape="rect" title=" " alt="" coords="1219,379,1287,405"/>
<area shape="rect" title=" " alt="" coords="1311,379,1393,405"/>
<area shape="rect" title=" " alt="" coords="1417,379,1516,405"/>
<area shape="rect" title=" " alt="" coords="1541,379,1606,405"/>
<area shape="rect" title=" " alt="" coords="1629,379,1669,405"/>
<area shape="rect" title=" " alt="" coords="1694,379,1743,405"/>
<area shape="rect" title=" " alt="" coords="1768,379,1835,405"/>
<area shape="rect" title=" " alt="" coords="1859,379,1939,405"/>
<area shape="rect" title=" " alt="" coords="1963,379,2032,405"/>
<area shape="rect" title=" " alt="" coords="2056,379,2120,405"/>
<area shape="rect" title=" " alt="" coords="2144,379,2208,405"/>
<area shape="rect" title=" " alt="" coords="2232,379,2320,405"/>
<area shape="rect" title=" " alt="" coords="2344,379,2499,405"/>
<area shape="rect" title=" " alt="" coords="2523,379,2629,405"/>
<area shape="rect" href="Weather_8h.php" title=" " alt="" coords="2639,155,2719,181"/>
<area shape="rect" href="Index_8h.php" title=" " alt="" coords="2647,229,2710,256"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="FireSpread_8h__dep__incl.png" border="0" usemap="#aFireSTARR_2src_2FireSpread_8hdep" alt=""/></div>
<map name="aFireSTARR_2src_2FireSpread_8hdep" id="aFireSTARR_2src_2FireSpread_8hdep">
<area shape="rect" title=" " alt="" coords="673,5,860,32"/>
<area shape="rect" href="FBP45_8h.php" title=" " alt="" coords="257,155,421,181"/>
<area shape="rect" href="FBP45_8cpp.php" title=" " alt="" coords="5,237,184,263"/>
<area shape="rect" href="Model_8cpp.php" title=" " alt="" coords="639,237,812,263"/>
<area shape="rect" href="FireSpread_8cpp.php" title=" " alt="" coords="735,80,937,107"/>
<area shape="rect" href="FuelType_8cpp.php" title=" " alt="" coords="961,80,1151,107"/>
<area shape="rect" href="Scenario_8cpp.php" title=" " alt="" coords="1176,80,1365,107"/>
<area shape="rect" href="StandardFuel_8h.php" title=" " alt="" coords="451,80,653,107"/>
<area shape="rect" href="Test_8cpp.php" title=" " alt="" coords="1390,80,1554,107"/>
<area shape="rect" href="FuelLookup_8cpp.php" title=" " alt="" coords="209,237,415,263"/>
<area shape="rect" href="ProbabilityMap_8cpp.php" title=" " alt="" coords="439,229,614,271"/>
<area shape="rect" href="StandardFuel_8cpp.php" title=" " alt="" coords="445,155,659,181"/>
</map>
</div>
</div>
<p><a href="FireSpread_8h_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1sim_1_1SpreadInfo.php">firestarr::sim::SpreadInfo</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">Information regarding spread within a Cell for a specific <a class="el" href="classfirestarr_1_1sim_1_1Scenario.php" title="A single Scenario in an Iteration using a specific FireWeather stream.">Scenario</a> and time.  <a href="classfirestarr_1_1sim_1_1SpreadInfo.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:namespacefirestarr"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr.php">firestarr</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:namespacefirestarr_1_1sim"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1sim.php">firestarr::sim</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="enum-members"></a>
Enumerations</h2></td></tr>
<tr class="memitem:a27c10565108fd02a3ec98401f407b932"><td class="memItemLeft" align="right" valign="top">enum &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1sim.php#a27c10565108fd02a3ec98401f407b932">firestarr::sim::SpreadResult</a> { <a class="el" href="namespacefirestarr_1_1sim.php#a27c10565108fd02a3ec98401f407b932aac1523966475703c0dbf47776bbf3fde">firestarr::sim::SPREAD_TOO_SLOW</a>
, <a class="el" href="namespacefirestarr_1_1sim.php#a27c10565108fd02a3ec98401f407b932aef518491b1206f23a50b11bf84f4f287">firestarr::sim::SPREAD_IMPOSSIBLE</a>
, <a class="el" href="namespacefirestarr_1_1sim.php#a27c10565108fd02a3ec98401f407b932a2fb03a78ff7e4e6b5ab756bfbcdc0cff">firestarr::sim::SPREAD_SCHEDULED</a>
 }</td></tr>
<tr class="memdesc:a27c10565108fd02a3ec98401f407b932"><td class="mdescLeft">&#160;</td><td class="mdescRight">Possible results of an attempt to spread.  <a href="namespacefirestarr_1_1sim.php#a27c10565108fd02a3ec98401f407b932">More...</a><br /></td></tr>
<tr class="separator:a27c10565108fd02a3ec98401f407b932"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a5e215bc8442d09bf23c8ee207d7d65dc"><td class="memItemLeft" align="right" valign="top">int&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1sim.php#a5e215bc8442d09bf23c8ee207d7d65dc">firestarr::sim::calculate_nd_for_point</a> (const int elevation, const topo::Point &amp;point) noexcept</td></tr>
<tr class="separator:a5e215bc8442d09bf23c8ee207d7d65dc"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
