<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>FireSTARR: Class Members - Functions</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">FireSTARR
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.php');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a id="index_r"></a>- r -</h3><ul>
<li>ran()
: <a class="el" href="classfirestarr_1_1sim_1_1Scenario.php#a8a4130a712e3836120bacf3bfca11ca3">firestarr::sim::Scenario</a>
</li>
<li>rasterRoot()
: <a class="el" href="classfirestarr_1_1sim_1_1Settings.php#aa7be3424b3e0f31a9af5f6a047055878">firestarr::sim::Settings</a>
, <a class="el" href="classfirestarr_1_1sim_1_1SettingsImplementation.php#a78fd346d09161684a77488de8028c938">firestarr::sim::SettingsImplementation</a>
</li>
<li>ratioConifer()
: <a class="el" href="classfirestarr_1_1fuel_1_1FuelMixed.php#a4d7ee66483e7cf1946c38cf857ec3167">firestarr::fuel::FuelMixed&lt; A, B, C, Bui0, RosMultiplier, PercentMixed, BulkDensity, InorganicPercent, DuffDepth &gt;</a>
</li>
<li>ratioDeciduous()
: <a class="el" href="classfirestarr_1_1fuel_1_1FuelMixed.php#ab4fb76034d7a147501a998921d2271ba">firestarr::fuel::FuelMixed&lt; A, B, C, Bui0, RosMultiplier, PercentMixed, BulkDensity, InorganicPercent, DuffDepth &gt;</a>
</li>
<li>readScenarios()
: <a class="el" href="classfirestarr_1_1sim_1_1Model.php#a22f74c1f1eb45cfa11de77774ae4b5d9">firestarr::sim::Model</a>
</li>
<li>readTiff()
: <a class="el" href="classfirestarr_1_1data_1_1ConstantGrid.php#acb83ad8fd5645c39fd501c1f361bed8b">firestarr::data::ConstantGrid&lt; T, V &gt;</a>
</li>
<li>readWeather()
: <a class="el" href="classfirestarr_1_1sim_1_1Model.php#acc76ae427ef30745a022b23628560b30">firestarr::sim::Model</a>
</li>
<li>registerObserver()
: <a class="el" href="classfirestarr_1_1sim_1_1Scenario.php#ac8d7b10803f69f75dd84576b7e519f70">firestarr::sim::Scenario</a>
</li>
<li>release()
: <a class="el" href="classfirestarr_1_1util_1_1MemoryPool.php#ac83590bb8563771c5609d6b146305c4e">firestarr::util::MemoryPool&lt; T &gt;</a>
</li>
<li>releaseBurnedVector()
: <a class="el" href="classfirestarr_1_1sim_1_1Model.php#a649fb06b0b8f1b005b3d22a5a0ba0c13">firestarr::sim::Model</a>
</li>
<li>reset()
: <a class="el" href="classfirestarr_1_1sim_1_1IntensityObserver.php#afd3d81c7ce87051c22479eb2a82573f2">firestarr::sim::IntensityObserver</a>
, <a class="el" href="classfirestarr_1_1sim_1_1IObserver.php#a0ead26168ce15cc6a9f8c04835bba111">firestarr::sim::IObserver</a>
, <a class="el" href="classfirestarr_1_1sim_1_1Iteration.php#a89e3d6b9f08c1024d0e85f2b269e7505">firestarr::sim::Iteration</a>
, <a class="el" href="classfirestarr_1_1sim_1_1MapObserver.php#aafd8d358b23ae450f904a7ae285ceb10">firestarr::sim::MapObserver&lt; T &gt;</a>
, <a class="el" href="classfirestarr_1_1sim_1_1Scenario.php#a9d787b7294930f8adf68d5b79b649b0b">firestarr::sim::Scenario</a>
</li>
<li>resetBurnedData()
: <a class="el" href="classfirestarr_1_1topo_1_1Environment.php#aa91cea9bbe32366f59cc9b86b372a42d">firestarr::topo::Environment</a>
</li>
<li>rh()
: <a class="el" href="classfirestarr_1_1wx_1_1Weather.php#a3fd85062c272289ff819277f87f7fc11">firestarr::wx::Weather</a>
</li>
<li>rho()
: <a class="el" href="classfirestarr_1_1fuel_1_1DuffType.php#a6b570f3b2569394d0abc72d393f1f1a8">firestarr::fuel::DuffType&lt; Ash, Rho, B0, B1, B2, B3 &gt;</a>
</li>
<li>rosBasic()
: <a class="el" href="classfirestarr_1_1fuel_1_1StandardFuel.php#aaa463dcf481b83ea32fe3ad6ff366d80">firestarr::fuel::StandardFuel&lt; A, B, C, Bui0, Cbh, Cfl, BulkDensity, InorganicPercent, DuffDepth &gt;</a>
</li>
<li>rosMultiplier()
: <a class="el" href="classfirestarr_1_1fuel_1_1FuelMixed.php#a6a97f32603cbc5cfde5392627b2959e7">firestarr::fuel::FuelMixed&lt; A, B, C, Bui0, RosMultiplier, PercentMixed, BulkDensity, InorganicPercent, DuffDepth &gt;</a>
</li>
<li>row()
: <a class="el" href="classfirestarr_1_1topo_1_1Location.php#a95eede212209b6a602433b821a265984">firestarr::topo::Location</a>
</li>
<li>rows()
: <a class="el" href="classfirestarr_1_1data_1_1GridBase.php#ab4265834a03aa8678bc1af3906fb181d">firestarr::data::GridBase</a>
, <a class="el" href="classfirestarr_1_1sim_1_1IntensityMap.php#a7976517845638f5dff13a8ca7775648d">firestarr::sim::IntensityMap</a>
, <a class="el" href="classfirestarr_1_1sim_1_1Model.php#a3ccafc17080e8d693d96744258094101">firestarr::sim::Model</a>
, <a class="el" href="classfirestarr_1_1sim_1_1Scenario.php#a50cbb9eaf1755005b96548874016c8f1">firestarr::sim::Scenario</a>
, <a class="el" href="classfirestarr_1_1topo_1_1Environment.php#afaca143b23e81a2e9f696fa8d7911c9e">firestarr::topo::Environment</a>
, <a class="el" href="classfirestarr_1_1topo_1_1EnvironmentInfo.php#a6688ab056079017cdb88dad69f2f11d2">firestarr::topo::EnvironmentInfo</a>
</li>
<li>run()
: <a class="el" href="classfirestarr_1_1sim_1_1Scenario.php#a6c27d631ec97664e71dcc8af8653fdf6">firestarr::sim::Scenario</a>
</li>
<li>runAsync()
: <a class="el" href="classfirestarr_1_1sim_1_1Settings.php#a435f63a417f7f0d081390fd72cc96b39">firestarr::sim::Settings</a>
</li>
<li>runIterations()
: <a class="el" href="classfirestarr_1_1sim_1_1Model.php#ad73313aead546785538f27f53fe0f914">firestarr::sim::Model</a>
</li>
<li>runScenarios()
: <a class="el" href="classfirestarr_1_1sim_1_1Model.php#a198b3a0ff8f350f80b61142c2cde3d5f">firestarr::sim::Model</a>
</li>
<li>runsRequired()
: <a class="el" href="classfirestarr_1_1util_1_1Statistics.php#a93daac57a9b465d8823994c9b563e7cf">firestarr::util::Statistics</a>
</li>
</ul>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
