<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>FireSTARR: Class Members - Functions</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">FireSTARR
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.php');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="contents">
&#160;

<h3><a id="index_i"></a>- i -</h3><ul>
<li>id()
: <a class="el" href="classfirestarr_1_1sim_1_1Scenario.php#aa7028e7a34efaeef6d0f3eb6ec4ddfe7">firestarr::sim::Scenario</a>
</li>
<li>increaseLogLevel()
: <a class="el" href="classfirestarr_1_1logging_1_1Log.php#a754395053c108ce52922eaee737584b7">firestarr::logging::Log</a>
</li>
<li>Index()
: <a class="el" href="classfirestarr_1_1data_1_1Index.php#a5119b473ce89bc2c41839937aa0d354c">firestarr::data::Index&lt; T &gt;</a>
</li>
<li>initializeNotBurnable()
: <a class="el" href="classfirestarr_1_1topo_1_1Environment.php#a467a589e96d6176501d86e322a41a759">firestarr::topo::Environment</a>
</li>
<li>InnerPos()
: <a class="el" href="structfirestarr_1_1sim_1_1InnerPos.php#a0ce638892bbe3eb150835680ec9023ef">firestarr::sim::InnerPos</a>
</li>
<li>inorganicPercent()
: <a class="el" href="classfirestarr_1_1fuel_1_1FuelBase.php#abf5880ab684b8eaf925dba9b36edf1c7">firestarr::fuel::FuelBase&lt; BulkDensity, InorganicPercent, DuffDepth &gt;</a>
</li>
<li>instance()
: <a class="el" href="classfirestarr_1_1sim_1_1SettingsImplementation.php#a230bb0270a6af6f854d3ac24d3c9998e">firestarr::sim::SettingsImplementation</a>
</li>
<li>intensity()
: <a class="el" href="classfirestarr_1_1sim_1_1Event.php#a32d8dca5bcd899898aed398a07ac14f8">firestarr::sim::Event</a>
</li>
<li>IntensityMap()
: <a class="el" href="classfirestarr_1_1sim_1_1IntensityMap.php#a68bb580e305d972176a867c5c313b163">firestarr::sim::IntensityMap</a>
</li>
<li>intensityMaxLow()
: <a class="el" href="classfirestarr_1_1sim_1_1Settings.php#a8d19c37bc8ac80dfa27eb0907c168395">firestarr::sim::Settings</a>
, <a class="el" href="classfirestarr_1_1sim_1_1SettingsImplementation.php#a249538a4b4a146395847a15ffb6692ed">firestarr::sim::SettingsImplementation</a>
</li>
<li>intensityMaxModerate()
: <a class="el" href="classfirestarr_1_1sim_1_1Settings.php#a69a2b5e31ab37f4e3b4e1b0750153189">firestarr::sim::Settings</a>
, <a class="el" href="classfirestarr_1_1sim_1_1SettingsImplementation.php#a76ab173330b9dad98a191011fb35082f">firestarr::sim::SettingsImplementation</a>
</li>
<li>IntensityObserver()
: <a class="el" href="classfirestarr_1_1sim_1_1IntensityObserver.php#a8850cb49d7972c1fe1d5206ca0fbf540">firestarr::sim::IntensityObserver</a>
</li>
<li>intToFuel()
: <a class="el" href="classfirestarr_1_1fuel_1_1FuelLookup.php#aae22b7cff2089da7da54b47b32003dda">firestarr::fuel::FuelLookup</a>
, <a class="el" href="classfirestarr_1_1fuel_1_1FuelLookupImpl.php#a67ba2b84409515beb048feaf8f6e884c">firestarr::fuel::FuelLookupImpl</a>
</li>
<li>InvalidFuel()
: <a class="el" href="classfirestarr_1_1fuel_1_1InvalidFuel.php#a72ad63bb4b79c05a437b3ded5babb701">firestarr::fuel::InvalidFuel</a>
</li>
<li>IObserver()
: <a class="el" href="classfirestarr_1_1sim_1_1IObserver.php#a71bc9553ec42b6bb0fb131ce878da43f">firestarr::sim::IObserver</a>
</li>
<li>isAtNight()
: <a class="el" href="classfirestarr_1_1sim_1_1Scenario.php#a504abe4ccf7ca0a362d7f3c952bde738">firestarr::sim::Scenario</a>
</li>
<li>isConfident()
: <a class="el" href="classfirestarr_1_1util_1_1Statistics.php#ae5f08a94ac7fa8f555ef3871ac2b2086">firestarr::util::Statistics</a>
</li>
<li>isCrown()
: <a class="el" href="classfirestarr_1_1fuel_1_1FuelType.php#ad9b29752ccfe987931c141043c46b70e">firestarr::fuel::FuelType</a>
</li>
<li>isfD1()
: <a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelD1.php#a9287c2b2b8ff44d835d5820d8a5ffab0">firestarr::fuel::fbp::FuelD1</a>
, <a class="el" href="classfirestarr_1_1fuel_1_1FuelMixed.php#a647efb3229650c2dca4ff810ce9825ae">firestarr::fuel::FuelMixed&lt; A, B, C, Bui0, RosMultiplier, PercentMixed, BulkDensity, InorganicPercent, DuffDepth &gt;</a>
</li>
<li>isi()
: <a class="el" href="classfirestarr_1_1wx_1_1FwiWeather.php#a6cdd0a32aa4f35138f815d8ffb64a627">firestarr::wx::FwiWeather</a>
</li>
<li>Isi()
: <a class="el" href="classfirestarr_1_1wx_1_1Isi.php#ac51cb2b627bfe5335fee38e1d105dbdb">firestarr::wx::Isi</a>
</li>
<li>isInvalid()
: <a class="el" href="classfirestarr_1_1sim_1_1SpreadInfo.php#ac0872d45e40f4e07f145a1874da1db21">firestarr::sim::SpreadInfo</a>
</li>
<li>isNotSpreading()
: <a class="el" href="classfirestarr_1_1sim_1_1SpreadInfo.php#a31e0108ebbb594dadb4350bac098c880">firestarr::sim::SpreadInfo</a>
</li>
<li>isOutOfTime()
: <a class="el" href="classfirestarr_1_1sim_1_1Model.php#a8b4ebb3d086021de26161d460e54f91f">firestarr::sim::Model</a>
</li>
<li>isOverridden()
: <a class="el" href="classfirestarr_1_1wx_1_1Startup.php#ab6caab829a7c2294894be34e63360c93">firestarr::wx::Startup</a>
</li>
<li>isSurrounded()
: <a class="el" href="classfirestarr_1_1sim_1_1IntensityMap.php#a9c24dbd41b96c1bbdf93c62725f4c0f2">firestarr::sim::IntensityMap</a>
, <a class="el" href="classfirestarr_1_1sim_1_1Scenario.php#a6739b3fcc4e346746e164714cf7d575b">firestarr::sim::Scenario</a>
</li>
<li>Iteration()
: <a class="el" href="classfirestarr_1_1sim_1_1Iteration.php#ac0d131badf011e4b89f24031f96e3b8a">firestarr::sim::Iteration</a>
</li>
</ul>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
