<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>FireSTARR: Class Hierarchy</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">FireSTARR
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.php');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
</div><!-- top -->
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div class="header">
  <div class="headertitle">
<div class="title">Class Hierarchy</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock">
<p><a href="hierarchy.php">Go to the textual class hierarchy</a></p>
</div><table border="0" cellspacing="10" cellpadding="0">
<tr><td><img src="inherit_graph_0.png" border="0" usemap="#afirestarr_1_1data_1_1GridBase" alt=""/>
<map name="afirestarr_1_1data_1_1GridBase" id="afirestarr_1_1data_1_1GridBase">
<area shape="rect" href="classfirestarr_1_1data_1_1GridBase.php" title="The base class with information for a grid of data with geographic coordinates." alt="" coords="5,173,161,199"/>
<area shape="rect" href="classfirestarr_1_1data_1_1Grid.php" title=" " alt="" coords="209,129,336,171"/>
<area shape="rect" href="classfirestarr_1_1data_1_1Grid.php" title="A GridBase with an associated type of data." alt="" coords="209,197,336,239"/>
<area shape="rect" href="classfirestarr_1_1data_1_1GridData.php" title="A Grid that defines the data structure used for storing values." alt="" coords="395,100,548,141"/>
<area shape="rect" href="classfirestarr_1_1data_1_1ConstantGrid.php" title=" " alt="" coords="607,5,777,47"/>
<area shape="rect" href="classfirestarr_1_1data_1_1GridMap.php" title=" " alt="" coords="617,71,767,112"/>
<area shape="rect" href="classfirestarr_1_1data_1_1GridMap.php" title=" " alt="" coords="617,136,767,177"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1BurnedMap.php" title="A map of locations which have burned in a Scenario." alt="" coords="825,143,993,170"/>
<area shape="rect" href="classfirestarr_1_1data_1_1GridData.php" title=" " alt="" coords="391,190,551,246"/>
<area shape="rect" href="classfirestarr_1_1data_1_1GridData.php" title=" " alt="" coords="384,269,559,311"/>
<area shape="rect" href="classfirestarr_1_1data_1_1GridMap.php" title="A GridData that uses an unordered_map for storage." alt="" coords="617,201,767,243"/>
<area shape="rect" href="classfirestarr_1_1data_1_1ConstantGrid.php" title="A GridData&lt;T, V, const vector&lt;T&gt;&gt; that cannot change once initialized." alt="" coords="615,269,769,311"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_1.png" border="0" usemap="#afirestarr_1_1data_1_1Index_3_01AccumulatedPrecipitation_01_4" alt=""/>
<map name="afirestarr_1_1data_1_1Index_3_01AccumulatedPrecipitation_01_4" id="afirestarr_1_1data_1_1Index_3_01AccumulatedPrecipitation_01_4">
<area shape="rect" href="classfirestarr_1_1data_1_1Index.php" title=" " alt="" coords="5,5,197,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_2.png" border="0" usemap="#afirestarr_1_1data_1_1Index_3_01Bui_01_4" alt=""/>
<map name="afirestarr_1_1data_1_1Index_3_01Bui_01_4" id="afirestarr_1_1data_1_1Index_3_01Bui_01_4">
<area shape="rect" href="classfirestarr_1_1data_1_1Index.php" title=" " alt="" coords="5,5,139,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_3.png" border="0" usemap="#afirestarr_1_1data_1_1Index_3_01Dc_01_4" alt=""/>
<map name="afirestarr_1_1data_1_1Index_3_01Dc_01_4" id="afirestarr_1_1data_1_1Index_3_01Dc_01_4">
<area shape="rect" href="classfirestarr_1_1data_1_1Index.php" title=" " alt="" coords="5,5,139,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_4.png" border="0" usemap="#afirestarr_1_1data_1_1Index_3_01Direction_01_4" alt=""/>
<map name="afirestarr_1_1data_1_1Index_3_01Direction_01_4" id="afirestarr_1_1data_1_1Index_3_01Direction_01_4">
<area shape="rect" href="classfirestarr_1_1data_1_1Index.php" title=" " alt="" coords="5,5,139,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_5.png" border="0" usemap="#afirestarr_1_1data_1_1Index_3_01Dmc_01_4" alt=""/>
<map name="afirestarr_1_1data_1_1Index_3_01Dmc_01_4" id="afirestarr_1_1data_1_1Index_3_01Dmc_01_4">
<area shape="rect" href="classfirestarr_1_1data_1_1Index.php" title=" " alt="" coords="5,5,139,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_6.png" border="0" usemap="#afirestarr_1_1data_1_1Index_3_01Dsr_01_4" alt=""/>
<map name="afirestarr_1_1data_1_1Index_3_01Dsr_01_4" id="afirestarr_1_1data_1_1Index_3_01Dsr_01_4">
<area shape="rect" href="classfirestarr_1_1data_1_1Index.php" title=" " alt="" coords="5,5,139,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_7.png" border="0" usemap="#afirestarr_1_1data_1_1Index_3_01Ffmc_01_4" alt=""/>
<map name="afirestarr_1_1data_1_1Index_3_01Ffmc_01_4" id="afirestarr_1_1data_1_1Index_3_01Ffmc_01_4">
<area shape="rect" href="classfirestarr_1_1data_1_1Index.php" title=" " alt="" coords="5,5,139,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_8.png" border="0" usemap="#afirestarr_1_1data_1_1Index_3_01Fwi_01_4" alt=""/>
<map name="afirestarr_1_1data_1_1Index_3_01Fwi_01_4" id="afirestarr_1_1data_1_1Index_3_01Fwi_01_4">
<area shape="rect" href="classfirestarr_1_1data_1_1Index.php" title=" " alt="" coords="5,5,139,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_9.png" border="0" usemap="#afirestarr_1_1data_1_1Index_3_01Isi_01_4" alt=""/>
<map name="afirestarr_1_1data_1_1Index_3_01Isi_01_4" id="afirestarr_1_1data_1_1Index_3_01Isi_01_4">
<area shape="rect" href="classfirestarr_1_1data_1_1Index.php" title=" " alt="" coords="5,5,139,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_10.png" border="0" usemap="#afirestarr_1_1data_1_1Index_3_01LogValue_01_4" alt=""/>
<map name="afirestarr_1_1data_1_1Index_3_01LogValue_01_4" id="afirestarr_1_1data_1_1Index_3_01LogValue_01_4">
<area shape="rect" href="classfirestarr_1_1data_1_1Index.php" title=" " alt="" coords="5,5,139,47"/>
<area shape="rect" href="classfirestarr_1_1data_1_1LogValue.php" title="A result of calling log(x) for some value of x, pre&#45;calculated at compile time." alt="" coords="187,13,344,39"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_11.png" border="0" usemap="#afirestarr_1_1data_1_1Index_3_01RelativeHumidity_01_4" alt=""/>
<map name="afirestarr_1_1data_1_1Index_3_01RelativeHumidity_01_4" id="afirestarr_1_1data_1_1Index_3_01RelativeHumidity_01_4">
<area shape="rect" href="classfirestarr_1_1data_1_1Index.php" title=" " alt="" coords="5,5,148,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_12.png" border="0" usemap="#afirestarr_1_1data_1_1Index_3_01Speed_01_4" alt=""/>
<map name="afirestarr_1_1data_1_1Index_3_01Speed_01_4" id="afirestarr_1_1data_1_1Index_3_01Speed_01_4">
<area shape="rect" href="classfirestarr_1_1data_1_1Index.php" title=" " alt="" coords="5,5,139,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_13.png" border="0" usemap="#afirestarr_1_1data_1_1Index_3_01T_01_4" alt=""/>
<map name="afirestarr_1_1data_1_1Index_3_01T_01_4" id="afirestarr_1_1data_1_1Index_3_01T_01_4">
<area shape="rect" href="classfirestarr_1_1data_1_1Index.php" title="A wrapper around a double to ensure correct types are used." alt="" coords="5,299,168,326"/>
<area shape="rect" href="classfirestarr_1_1wx_1_1AccumulatedPrecipitation.php" title="Accumulated precipitation in mm." alt="" coords="227,5,396,47"/>
<area shape="rect" href="classfirestarr_1_1wx_1_1Bui.php" title="Build&#45;up Index value." alt="" coords="255,71,367,98"/>
<area shape="rect" href="classfirestarr_1_1wx_1_1Dc.php" title="Drought Code value." alt="" coords="257,122,366,149"/>
<area shape="rect" href="classfirestarr_1_1wx_1_1Direction.php" title="Direction with access to degrees or radians." alt="" coords="239,173,383,199"/>
<area shape="rect" href="classfirestarr_1_1wx_1_1Dmc.php" title="Duff Moisture Code value." alt="" coords="251,223,371,250"/>
<area shape="rect" href="classfirestarr_1_1wx_1_1Dsr.php" title="Danger Severity Rating value." alt="" coords="255,274,368,301"/>
<area shape="rect" href="classfirestarr_1_1wx_1_1Ffmc.php" title="Fine Fuel Moisture Code value." alt="" coords="250,325,373,351"/>
<area shape="rect" href="classfirestarr_1_1wx_1_1Fwi.php" title="Fire Weather Index value." alt="" coords="254,375,369,402"/>
<area shape="rect" href="classfirestarr_1_1wx_1_1Isi.php" title="Initial Spread Index value." alt="" coords="258,426,365,453"/>
<area shape="rect" href="classfirestarr_1_1wx_1_1RelativeHumidity.php" title="Relative humidity as a percentage." alt="" coords="216,477,407,503"/>
<area shape="rect" href="classfirestarr_1_1wx_1_1Speed.php" title="Speed in kilometers per hour." alt="" coords="246,527,377,554"/>
<area shape="rect" href="classfirestarr_1_1wx_1_1Temperature.php" title="Temperature in degrees Celsius." alt="" coords="228,578,395,605"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_14.png" border="0" usemap="#afirestarr_1_1data_1_1Index_3_01Temperature_01_4" alt=""/>
<map name="afirestarr_1_1data_1_1Index_3_01Temperature_01_4" id="afirestarr_1_1data_1_1Index_3_01Temperature_01_4">
<area shape="rect" href="classfirestarr_1_1data_1_1Index.php" title=" " alt="" coords="5,5,139,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_15.png" border="0" usemap="#afirestarr_1_1fuel_1_1Duff" alt=""/>
<map name="afirestarr_1_1fuel_1_1Duff" id="afirestarr_1_1fuel_1_1Duff">
<area shape="rect" href="classfirestarr_1_1fuel_1_1Duff.php" title="Base class for DuffType." alt="" coords="5,340,127,367"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title=" " alt="" coords="179,5,360,61"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title=" " alt="" coords="179,85,360,141"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title=" " alt="" coords="187,165,351,221"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title=" " alt="" coords="179,245,360,301"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title=" " alt="" coords="187,325,351,381"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title=" " alt="" coords="180,405,359,461"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title=" " alt="" coords="186,485,353,541"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title=" " alt="" coords="189,565,349,621"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1DuffType.php" title="A specific type of Duff layer, and the associated smouldering coefficients." alt="" coords="175,645,364,686"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_16.png" border="0" usemap="#afirestarr_1_1fuel_1_1FuelLookup" alt=""/>
<map name="afirestarr_1_1fuel_1_1FuelLookup" id="afirestarr_1_1fuel_1_1FuelLookup">
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelLookup.php" title="Provides ability to look up a fuel type based on name or code." alt="" coords="5,5,172,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_17.png" border="0" usemap="#afirestarr_1_1fuel_1_1FuelLookupImpl" alt=""/>
<map name="afirestarr_1_1fuel_1_1FuelLookupImpl" id="afirestarr_1_1fuel_1_1FuelLookupImpl">
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelLookupImpl.php" title="Implementation class for FuelLookup." alt="" coords="5,5,196,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_18.png" border="0" usemap="#afirestarr_1_1fuel_1_1FuelType" alt=""/>
<map name="afirestarr_1_1fuel_1_1FuelType" id="afirestarr_1_1fuel_1_1FuelType">
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelType.php" title="An FBP fuel type." alt="" coords="5,351,156,377"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelVariable.php" title=" " alt="" coords="206,148,413,204"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelVariable.php" title=" " alt="" coords="208,228,411,284"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelVariable.php" title=" " alt="" coords="224,307,395,349"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelBase.php" title="Base class for all FuelTypes." alt="" coords="204,372,415,428"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelVariable.php" title="A fuel type that changes based on the season." alt="" coords="216,451,403,493"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1InvalidFuel.php" title="Placeholder fuel that throws exceptions if it ever gets used." alt="" coords="229,517,390,544"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM3M4.php" title="FBP fuel type M&#45;3/M&#45;4." alt="" coords="475,155,676,197"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM1M2.php" title="FBP fuel type M&#45;1/M&#45;2." alt="" coords="477,234,674,275"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelD1D2.php" title="FBP fuel type D&#45;1/D&#45;2." alt="" coords="517,299,633,341"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1StandardFuel.php" title=" " alt="" coords="463,365,687,435"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1StandardFuel.php" title=" " alt="" coords="470,485,681,555"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1StandardFuel.php" title="A FuelBase made of a standard fuel type." alt="" coords="463,687,688,758"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelMixed.php" title=" " alt="" coords="748,125,941,181"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelMixed.php" title=" " alt="" coords="736,284,953,340"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelMixed.php" title="A mixedwood fuel type." alt="" coords="745,365,944,435"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelMixedDead.php" title=" " alt="" coords="1030,5,1195,61"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelMixedDead.php" title=" " alt="" coords="1030,85,1195,141"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelMixedDead.php" title="A fuel made of dead fir and D1." alt="" coords="1001,165,1224,221"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM4.php" title="FBP fuel type M&#45;4." alt="" coords="1272,13,1455,54"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM3.php" title="FBP fuel type M&#45;3." alt="" coords="1272,93,1455,134"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelMixedWood.php" title=" " alt="" coords="1021,245,1205,286"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelMixedWood.php" title=" " alt="" coords="1024,310,1201,351"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelMixedWood.php" title="A fuel composed of C2 and D1 mixed." alt="" coords="1001,375,1224,417"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM1.php" title="FBP fuel type M&#45;1." alt="" coords="1274,245,1453,286"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM2.php" title="FBP fuel type M&#45;2." alt="" coords="1274,310,1453,351"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelGrass.php" title=" " alt="" coords="765,459,924,501"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelGrass.php" title=" " alt="" coords="765,525,924,566"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelGrass.php" title="A grass fuel type." alt="" coords="765,590,924,631"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelO1A.php" title="FBP fuel type O&#45;1a." alt="" coords="1055,459,1171,501"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelO1B.php" title="FBP fuel type O&#45;1b." alt="" coords="1055,525,1171,566"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php" title=" " alt="" coords="767,655,922,711"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php" title=" " alt="" coords="763,735,926,791"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelNonMixed.php" title="A StandardFuel that is not made of multiple fuels." alt="" coords="745,979,944,1050"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelD2.php" title="FBP fuel type D&#45;2." alt="" coords="1055,662,1171,703"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelD1.php" title="FBP fuel type D&#45;1." alt="" coords="1055,734,1171,775"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelConifer.php" title=" " alt="" coords="1031,799,1195,855"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelConifer.php" title=" " alt="" coords="1005,879,1220,935"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelConifer.php" title=" " alt="" coords="1031,987,1195,1043"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelConifer.php" title=" " alt="" coords="1027,1067,1198,1123"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelConifer.php" title=" " alt="" coords="1017,1259,1208,1315"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelConifer.php" title="A conifer fuel type." alt="" coords="1011,1339,1214,1410"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC1.php" title="FBP fuel type C&#45;1." alt="" coords="1305,625,1421,666"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelSlash.php" title=" " alt="" coords="1285,689,1441,745"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelSlash.php" title=" " alt="" coords="1285,769,1441,825"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelSlash.php" title=" " alt="" coords="1285,849,1441,905"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelSlash.php" title="A slash fuel type." alt="" coords="1272,929,1455,985"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelS2.php" title="FBP fuel type S&#45;2." alt="" coords="1503,697,1619,738"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelS3.php" title="FBP fuel type S&#45;3." alt="" coords="1503,777,1619,818"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelS1.php" title="FBP fuel type S&#45;1." alt="" coords="1503,857,1619,898"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC7.php" title="FBP fuel type C&#45;7." alt="" coords="1305,1009,1421,1050"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php" title="FBP fuel type C&#45;2." alt="" coords="1305,1074,1421,1115"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelJackpine.php" title=" " alt="" coords="1275,1139,1452,1195"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelJackpine.php" title=" " alt="" coords="1275,1219,1452,1275"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelPine.php" title=" " alt="" coords="1289,1299,1438,1355"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelPine.php" title=" " alt="" coords="1289,1379,1438,1435"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelJackpine.php" title="A fuel with jackpine as base fuel type." alt="" coords="1276,1459,1451,1515"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1FuelPine.php" title="A fuel with pine as the base fuel type." alt="" coords="1279,1539,1448,1595"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC4.php" title="FBP fuel type C&#45;4." alt="" coords="1503,1146,1619,1187"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC3.php" title="FBP fuel type C&#45;3." alt="" coords="1503,1226,1619,1267"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC6.php" title="FBP fuel type C&#45;6." alt="" coords="1503,1306,1619,1347"/>
<area shape="rect" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC5.php" title="FBP fuel type C&#45;5." alt="" coords="1503,1386,1619,1427"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_19.png" border="0" usemap="#afirestarr_1_1logging_1_1Log" alt=""/>
<map name="afirestarr_1_1logging_1_1Log" id="afirestarr_1_1logging_1_1Log">
<area shape="rect" href="classfirestarr_1_1logging_1_1Log.php" title="Provides logging functionality." alt="" coords="5,5,145,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_20.png" border="0" usemap="#afirestarr_1_1sim_1_1CriticalSection" alt=""/>
<map name="afirestarr_1_1sim_1_1CriticalSection" id="afirestarr_1_1sim_1_1CriticalSection">
<area shape="rect" href="classfirestarr_1_1sim_1_1CriticalSection.php" title="Indicates a section of code that is limited to a certain number of threads running at once." alt="" coords="5,5,144,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_21.png" border="0" usemap="#afirestarr_1_1sim_1_1Event" alt=""/>
<map name="afirestarr_1_1sim_1_1Event" id="afirestarr_1_1sim_1_1Event">
<area shape="rect" href="classfirestarr_1_1sim_1_1Event.php" title="A specific Event scheduled in a specific Scenario." alt="" coords="5,5,136,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_22.png" border="0" usemap="#afirestarr_1_1sim_1_1EventCompare" alt=""/>
<map name="afirestarr_1_1sim_1_1EventCompare" id="afirestarr_1_1sim_1_1EventCompare">
<area shape="rect" href="structfirestarr_1_1sim_1_1EventCompare.php" title="Defines how Events are compared for sorting." alt="" coords="5,5,188,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_23.png" border="0" usemap="#afirestarr_1_1sim_1_1InnerPos" alt=""/>
<map name="afirestarr_1_1sim_1_1InnerPos" id="afirestarr_1_1sim_1_1InnerPos">
<area shape="rect" href="structfirestarr_1_1sim_1_1InnerPos.php" title="The position within a Cell that a spreading point has." alt="" coords="5,5,156,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_24.png" border="0" usemap="#afirestarr_1_1sim_1_1IntensityMap" alt=""/>
<map name="afirestarr_1_1sim_1_1IntensityMap" id="afirestarr_1_1sim_1_1IntensityMap">
<area shape="rect" href="classfirestarr_1_1sim_1_1IntensityMap.php" title="Represents a map of intensities that cells have burned at for a single Scenario." alt="" coords="5,5,177,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_25.png" border="0" usemap="#afirestarr_1_1sim_1_1IObserver" alt=""/>
<map name="afirestarr_1_1sim_1_1IObserver" id="afirestarr_1_1sim_1_1IObserver">
<area shape="rect" href="classfirestarr_1_1sim_1_1IObserver.php" title="Interface for observers that get notified when cells burn so they can track things." alt="" coords="5,111,160,138"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1MapObserver.php" title=" " alt="" coords="223,5,399,47"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1MapObserver.php" title=" " alt="" coords="223,71,399,112"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1IntensityObserver.php" title="Tracks the intensity that Cells burn at." alt="" coords="238,136,385,177"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1MapObserver.php" title="An IObserver that tracks notification data using a GridMap." alt="" coords="208,202,415,229"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1ArrivalObserver.php" title="Tracks when fire initially arrives in a Cell." alt="" coords="465,13,653,39"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1SourceObserver.php" title="Tracks source Cell that fire arrived in Cell from." alt="" coords="463,78,655,105"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_26.png" border="0" usemap="#afirestarr_1_1sim_1_1IObserver__deleter" alt=""/>
<map name="afirestarr_1_1sim_1_1IObserver__deleter" id="afirestarr_1_1sim_1_1IObserver__deleter">
<area shape="rect" href="structfirestarr_1_1sim_1_1IObserver__deleter.php" title="Deleter for IObserver to get around incomplete class with unique_ptr." alt="" coords="5,5,160,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_27.png" border="0" usemap="#afirestarr_1_1sim_1_1Iteration" alt=""/>
<map name="afirestarr_1_1sim_1_1Iteration" id="afirestarr_1_1sim_1_1Iteration">
<area shape="rect" href="classfirestarr_1_1sim_1_1Iteration.php" title="Represents a full set of simulations using all available weather streams." alt="" coords="5,5,151,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_28.png" border="0" usemap="#afirestarr_1_1sim_1_1Model" alt=""/>
<map name="afirestarr_1_1sim_1_1Model" id="afirestarr_1_1sim_1_1Model">
<area shape="rect" href="classfirestarr_1_1sim_1_1Model.php" title="Contains all the immutable information regarding a simulation that is common between Scenarios." alt="" coords="5,5,139,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_29.png" border="0" usemap="#afirestarr_1_1sim_1_1ProbabilityMap" alt=""/>
<map name="afirestarr_1_1sim_1_1ProbabilityMap" id="afirestarr_1_1sim_1_1ProbabilityMap">
<area shape="rect" href="classfirestarr_1_1sim_1_1ProbabilityMap.php" title="Map of the percentage of simulations in which a Cell burned in each intensity category." alt="" coords="5,5,188,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_30.png" border="0" usemap="#afirestarr_1_1sim_1_1Scenario" alt=""/>
<map name="afirestarr_1_1sim_1_1Scenario" id="afirestarr_1_1sim_1_1Scenario">
<area shape="rect" href="classfirestarr_1_1sim_1_1Scenario.php" title="A single Scenario in an Iteration using a specific FireWeather stream." alt="" coords="5,5,155,32"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1TestScenario.php" title="A Scenario run with constant fuel, weather, and topography." alt="" coords="203,5,377,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_31.png" border="0" usemap="#afirestarr_1_1sim_1_1Semaphore" alt=""/>
<map name="afirestarr_1_1sim_1_1Semaphore" id="afirestarr_1_1sim_1_1Semaphore">
<area shape="rect" href="classfirestarr_1_1sim_1_1Semaphore.php" title="Provides the ability to limit number of threads running at once." alt="" coords="5,5,169,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_32.png" border="0" usemap="#afirestarr_1_1sim_1_1Settings" alt=""/>
<map name="afirestarr_1_1sim_1_1Settings" id="afirestarr_1_1sim_1_1Settings">
<area shape="rect" href="classfirestarr_1_1sim_1_1Settings.php" title="Reads and provides access to settings for the simulation." alt="" coords="5,5,152,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_33.png" border="0" usemap="#afirestarr_1_1sim_1_1SettingsImplementation" alt=""/>
<map name="afirestarr_1_1sim_1_1SettingsImplementation" id="afirestarr_1_1sim_1_1SettingsImplementation">
<area shape="rect" href="classfirestarr_1_1sim_1_1SettingsImplementation.php" title="Settings implementation class." alt="" coords="5,5,152,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_34.png" border="0" usemap="#afirestarr_1_1sim_1_1SpreadInfo" alt=""/>
<map name="afirestarr_1_1sim_1_1SpreadInfo" id="afirestarr_1_1sim_1_1SpreadInfo">
<area shape="rect" href="classfirestarr_1_1sim_1_1SpreadInfo.php" title="Information regarding spread within a Cell for a specific Scenario and time." alt="" coords="5,5,167,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_35.png" border="0" usemap="#afirestarr_1_1topo_1_1Environment" alt=""/>
<map name="afirestarr_1_1topo_1_1Environment" id="afirestarr_1_1topo_1_1Environment">
<area shape="rect" href="classfirestarr_1_1topo_1_1Environment.php" title="The area that a Model is run for, with Fuel, Slope, and Aspect grids." alt="" coords="5,5,180,32"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1TestEnvironment.php" title="An Environment with no elevation and the same value in every Cell." alt="" coords="228,5,424,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_36.png" border="0" usemap="#afirestarr_1_1topo_1_1EnvironmentInfo" alt=""/>
<map name="afirestarr_1_1topo_1_1EnvironmentInfo" id="afirestarr_1_1topo_1_1EnvironmentInfo">
<area shape="rect" href="classfirestarr_1_1topo_1_1EnvironmentInfo.php" title="Information regarding an Environment, such as grids to read and location." alt="" coords="5,5,201,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_37.png" border="0" usemap="#afirestarr_1_1topo_1_1Location" alt=""/>
<map name="afirestarr_1_1topo_1_1Location" id="afirestarr_1_1topo_1_1Location">
<area shape="rect" href="classfirestarr_1_1topo_1_1Location.php" title="A location with a row and column." alt="" coords="5,5,157,32"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1Cell.php" title="A Location with a Slope, Aspect, and Fuel." alt="" coords="205,5,329,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_38.png" border="0" usemap="#afirestarr_1_1topo_1_1Perimeter" alt=""/>
<map name="afirestarr_1_1topo_1_1Perimeter" id="afirestarr_1_1topo_1_1Perimeter">
<area shape="rect" href="classfirestarr_1_1topo_1_1Perimeter.php" title="Perimeter for an existing fire to initialize a simulation with." alt="" coords="5,5,164,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_39.png" border="0" usemap="#afirestarr_1_1topo_1_1Point" alt=""/>
<map name="afirestarr_1_1topo_1_1Point" id="afirestarr_1_1topo_1_1Point">
<area shape="rect" href="classfirestarr_1_1topo_1_1Point.php" title="A geographic location in lat/long coordinates." alt="" coords="5,5,137,32"/>
<area shape="rect" href="classfirestarr_1_1topo_1_1StartPoint.php" title="A Point that has sunrise and sunset times for each day." alt="" coords="185,5,345,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_40.png" border="0" usemap="#afirestarr_1_1util_1_1LookupTable_3_01Fct_00_01IndexDigits_00_01Precision_01_4" alt=""/>
<map name="afirestarr_1_1util_1_1LookupTable_3_01Fct_00_01IndexDigits_00_01Precision_01_4" id="afirestarr_1_1util_1_1LookupTable_3_01Fct_00_01IndexDigits_00_01Precision_01_4">
<area shape="rect" href="classfirestarr_1_1util_1_1LookupTable.php" title="A table initialized using the given function ranging over the number of digits and precision." alt="" coords="5,5,200,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_41.png" border="0" usemap="#afirestarr_1_1util_1_1LookupTable_3_6duffFunction_01_4" alt=""/>
<map name="afirestarr_1_1util_1_1LookupTable_3_6duffFunction_01_4" id="afirestarr_1_1util_1_1LookupTable_3_6duffFunction_01_4">
<area shape="rect" href="classfirestarr_1_1util_1_1LookupTable.php" title=" " alt="" coords="5,5,175,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_42.png" border="0" usemap="#afirestarr_1_1util_1_1MemoryPool_3_01T_01_4" alt=""/>
<map name="afirestarr_1_1util_1_1MemoryPool_3_01T_01_4" id="afirestarr_1_1util_1_1MemoryPool_3_01T_01_4">
<area shape="rect" href="classfirestarr_1_1util_1_1MemoryPool.php" title="Keeps track of data structures so they can be reused instead of freeing and reacquiring them." alt="" coords="5,5,201,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_43.png" border="0" usemap="#afirestarr_1_1util_1_1SafeVector" alt=""/>
<map name="afirestarr_1_1util_1_1SafeVector" id="afirestarr_1_1util_1_1SafeVector">
<area shape="rect" href="classfirestarr_1_1util_1_1SafeVector.php" title="A vector with added thread safety." alt="" coords="5,5,164,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_44.png" border="0" usemap="#afirestarr_1_1util_1_1Statistics" alt=""/>
<map name="afirestarr_1_1util_1_1Statistics" id="afirestarr_1_1util_1_1Statistics">
<area shape="rect" href="classfirestarr_1_1util_1_1Statistics.php" title="Provides statistics calculation for vectors of values." alt="" coords="5,5,155,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_45.png" border="0" usemap="#afirestarr_1_1util_1_1UsageCount" alt=""/>
<map name="afirestarr_1_1util_1_1UsageCount" id="afirestarr_1_1util_1_1UsageCount">
<area shape="rect" href="classfirestarr_1_1util_1_1UsageCount.php" title="Provides the ability to determine how many times something is used during a simulation." alt="" coords="5,5,172,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_46.png" border="0" usemap="#afirestarr_1_1wx_1_1FireWeather" alt=""/>
<map name="afirestarr_1_1wx_1_1FireWeather" id="afirestarr_1_1wx_1_1FireWeather">
<area shape="rect" href="classfirestarr_1_1wx_1_1FireWeather.php" title="A stream of weather that gets used by a Scenario every Iteration." alt="" coords="5,5,168,32"/>
<area shape="rect" href="classfirestarr_1_1sim_1_1TestWeather.php" title="A FireWeather stream with the same value for every date and time." alt="" coords="216,5,388,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_47.png" border="0" usemap="#afirestarr_1_1wx_1_1FwiStream" alt=""/>
<map name="afirestarr_1_1wx_1_1FwiStream" id="afirestarr_1_1wx_1_1FwiStream">
<area shape="rect" href="classfirestarr_1_1wx_1_1FwiStream.php" title="A stream of FwiWeather values used for a Scenario." alt="" coords="5,5,161,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_48.png" border="0" usemap="#afirestarr_1_1wx_1_1ModelCompare" alt=""/>
<map name="afirestarr_1_1wx_1_1ModelCompare" id="afirestarr_1_1wx_1_1ModelCompare">
<area shape="rect" href="structfirestarr_1_1wx_1_1ModelCompare.php" title="Provides ordering for WeatherModel comparison." alt="" coords="5,5,185,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_49.png" border="0" usemap="#afirestarr_1_1wx_1_1Score" alt=""/>
<map name="afirestarr_1_1wx_1_1Score" id="afirestarr_1_1wx_1_1Score">
<area shape="rect" href="classfirestarr_1_1wx_1_1Score.php" title="The WeatherSHIELD score for a specific year." alt="" coords="5,5,132,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_50.png" border="0" usemap="#afirestarr_1_1wx_1_1Startup" alt=""/>
<map name="afirestarr_1_1wx_1_1Startup" id="afirestarr_1_1wx_1_1Startup">
<area shape="rect" href="classfirestarr_1_1wx_1_1Startup.php" title="Startup values to initialize a weather stream calculation with." alt="" coords="5,5,140,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_51.png" border="0" usemap="#afirestarr_1_1wx_1_1Weather" alt=""/>
<map name="afirestarr_1_1wx_1_1Weather" id="afirestarr_1_1wx_1_1Weather">
<area shape="rect" href="classfirestarr_1_1wx_1_1Weather.php" title="Collection of weather indices used for calculating FwiWeather." alt="" coords="5,5,147,32"/>
<area shape="rect" href="classfirestarr_1_1wx_1_1FwiWeather.php" title="A Weather value with calculated FWI indices." alt="" coords="195,5,357,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_52.png" border="0" usemap="#afirestarr_1_1wx_1_1WeatherModel" alt=""/>
<map name="afirestarr_1_1wx_1_1WeatherModel" id="afirestarr_1_1wx_1_1WeatherModel">
<area shape="rect" href="classfirestarr_1_1wx_1_1WeatherModel.php" title="A model within the WxSHIELD ensemble set." alt="" coords="5,5,181,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_53.png" border="0" usemap="#afirestarr_1_1wx_1_1Wind" alt=""/>
<map name="afirestarr_1_1wx_1_1Wind" id="afirestarr_1_1wx_1_1Wind">
<area shape="rect" href="classfirestarr_1_1wx_1_1Wind.php" title="Wind with a Speed and Direction." alt="" coords="5,5,128,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_54.png" border="0" usemap="#aobject" alt=""/>
<map name="aobject" id="aobject">
<area shape="rect" href="classobject.php" title=" " alt="" coords="5,5,63,32"/>
<area shape="rect" href="classfirestarr__gis_1_1Extent.php" title=" " alt="" coords="111,5,239,32"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_55.png" border="0" usemap="#astd_1_1hash_3_01firestarr_1_1topo_1_1Cell_01_4" alt=""/>
<map name="astd_1_1hash_3_01firestarr_1_1topo_1_1Cell_01_4" id="astd_1_1hash_3_01firestarr_1_1topo_1_1Cell_01_4">
<area shape="rect" href="structstd_1_1hash_3_01firestarr_1_1topo_1_1Cell_01_4.php" title="Provides hashing of Cell objects." alt="" coords="5,5,133,47"/>
</map>
</td></tr>
<tr><td><img src="inherit_graph_56.png" border="0" usemap="#astd_1_1hash_3_01Location_01_4" alt=""/>
<map name="astd_1_1hash_3_01Location_01_4" id="astd_1_1hash_3_01Location_01_4">
<area shape="rect" href="structstd_1_1hash_3_01Location_01_4.php" title="Provides hash function for Location." alt="" coords="5,5,152,32"/>
</map>
</td></tr>
</table>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
