<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>FireSTARR: FireSTARR/src/MemoryPool.h Source File</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">FireSTARR
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.php');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_4d88195d9c9596897c1a7e6e6c1a3b9e.php">FireSTARR</a></li><li class="navelem"><a class="el" href="dir_fee61d26c5aa45e5f9c842f18eee2357.php">src</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">MemoryPool.h</div>  </div>
</div><!--header-->
<div class="contents">
<a href="MemoryPool_8h.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;<span class="comment">// Copyright (c) 2020-2021, Queen&#39;s Printer for Ontario.</span></div>
<div class="line"><a name="l00002"></a><span class="lineno">    2</span>&#160;<span class="comment">//</span></div>
<div class="line"><a name="l00003"></a><span class="lineno">    3</span>&#160;<span class="comment">// This program is free software: you can redistribute it and/or modify</span></div>
<div class="line"><a name="l00004"></a><span class="lineno">    4</span>&#160;<span class="comment">// it under the terms of the GNU Affero General Public License as</span></div>
<div class="line"><a name="l00005"></a><span class="lineno">    5</span>&#160;<span class="comment">// published by the Free Software Foundation, either version 3 of the</span></div>
<div class="line"><a name="l00006"></a><span class="lineno">    6</span>&#160;<span class="comment">// License, or (at your option) any later version.</span></div>
<div class="line"><a name="l00007"></a><span class="lineno">    7</span>&#160;<span class="comment">//</span></div>
<div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;<span class="comment">// This program is distributed in the hope that it will be useful,</span></div>
<div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;<span class="comment">// but WITHOUT ANY WARRANTY; without even the implied warranty of</span></div>
<div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="comment">// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the</span></div>
<div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="comment">// GNU Affero General Public License for more details.</span></div>
<div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="comment">//</span></div>
<div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="comment">// You should have received a copy of the GNU Affero General Public License</span></div>
<div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="comment">// along with this program.  If not, see &lt;https://www.gnu.org/licenses/&gt;.</span></div>
<div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160; </div>
<div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="preprocessor">#pragma once</span></div>
<div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="keyword">namespace </span><a class="code" href="namespacefirestarr.php">firestarr</a></div>
<div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;{</div>
<div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;<span class="keyword">namespace </span>util</div>
<div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;{</div>
<div class="line"><a name="l00025"></a><span class="lineno">   25</span>&#160;<span class="keyword">template</span> &lt;<span class="keyword">class</span> T&gt;</div>
<div class="line"><a name="l00026"></a><span class="lineno"><a class="line" href="classfirestarr_1_1util_1_1MemoryPool.php">   26</a></span>&#160;<span class="keyword">class </span><a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php">MemoryPool</a></div>
<div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;{</div>
<div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;<span class="keyword">public</span>:</div>
<div class="line"><a name="l00029"></a><span class="lineno"><a class="line" href="classfirestarr_1_1util_1_1MemoryPool.php#a95419652599d39262c7aa8097f3ebb42">   29</a></span>&#160;  <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#a95419652599d39262c7aa8097f3ebb42">~MemoryPool</a>() = <span class="keywordflow">default</span>;</div>
<div class="line"><a name="l00030"></a><span class="lineno"><a class="line" href="classfirestarr_1_1util_1_1MemoryPool.php#a74352dfcdbb25b7702e6199b7bcbbdd4">   30</a></span>&#160;  <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#a74352dfcdbb25b7702e6199b7bcbbdd4">MemoryPool</a>() = <span class="keywordflow">default</span>;</div>
<div class="line"><a name="l00031"></a><span class="lineno"><a class="line" href="classfirestarr_1_1util_1_1MemoryPool.php#a91c508777b53026f670ea2c1cb6b60b8">   31</a></span>&#160;  <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#a91c508777b53026f670ea2c1cb6b60b8">MemoryPool</a>(<span class="keyword">const</span> <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php">MemoryPool</a>&amp; rhs) = <span class="keyword">delete</span>;</div>
<div class="line"><a name="l00032"></a><span class="lineno"><a class="line" href="classfirestarr_1_1util_1_1MemoryPool.php#aed8df0fbea68f8ab0a95736a4e050e29">   32</a></span>&#160;  <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#aed8df0fbea68f8ab0a95736a4e050e29">MemoryPool</a>(<a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php">MemoryPool</a>&amp;&amp; rhs) = <span class="keyword">delete</span>;</div>
<div class="line"><a name="l00033"></a><span class="lineno"><a class="line" href="classfirestarr_1_1util_1_1MemoryPool.php#ae5aa27002f4d92b4a12e9475dc5c8dc2">   33</a></span>&#160;  <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php">MemoryPool</a>&amp; <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#ae5aa27002f4d92b4a12e9475dc5c8dc2">operator=</a>(<span class="keyword">const</span> <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php">MemoryPool</a>&amp; rhs) = <span class="keyword">delete</span>;</div>
<div class="line"><a name="l00034"></a><span class="lineno"><a class="line" href="classfirestarr_1_1util_1_1MemoryPool.php#a12a2946fbb7b73d666bcbefde8240276">   34</a></span>&#160;  <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php">MemoryPool</a>&amp; <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#a12a2946fbb7b73d666bcbefde8240276">operator=</a>(<a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php">MemoryPool</a>&amp;&amp; rhs) = <span class="keyword">delete</span>;</div>
<div class="line"><a name="l00039"></a><span class="lineno"><a class="line" href="classfirestarr_1_1util_1_1MemoryPool.php#acf99b34a6727535b696f3b215b7063af">   39</a></span>&#160;  T* <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#acf99b34a6727535b696f3b215b7063af">acquire</a>()</div>
<div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;  {</div>
<div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;    <span class="keywordflow">if</span> (!<a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#a94bba142e59e9dc871b44a934fd94a60">assets_</a>.empty())</div>
<div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;    {</div>
<div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;      lock_guard&lt;mutex&gt; lock(<a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#acb09f49cddc847f6fd8fba772519d6dc">mutex_</a>);</div>
<div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;      <span class="comment">// check again once we have the mutex</span></div>
<div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;      <span class="keywordflow">if</span> (!<a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#a94bba142e59e9dc871b44a934fd94a60">assets_</a>.empty())</div>
<div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;      {</div>
<div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;        <span class="keyword">const</span> <span class="keyword">auto</span> v = std::move(<a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#a94bba142e59e9dc871b44a934fd94a60">assets_</a>.back()).release();</div>
<div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;        <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#a94bba142e59e9dc871b44a934fd94a60">assets_</a>.pop_back();</div>
<div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;        <span class="comment">// this is already reset before it was given back</span></div>
<div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;        <span class="keywordflow">return</span> v;</div>
<div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;      }</div>
<div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;    }</div>
<div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;    <span class="keywordflow">return</span> <span class="keyword">new</span> T();</div>
<div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;  }</div>
<div class="line"><a name="l00059"></a><span class="lineno"><a class="line" href="classfirestarr_1_1util_1_1MemoryPool.php#ac83590bb8563771c5609d6b146305c4e">   59</a></span>&#160;  <span class="keywordtype">void</span> <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#ac83590bb8563771c5609d6b146305c4e">release</a>(T* asset)</div>
<div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;  {</div>
<div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;    <span class="keywordflow">if</span> (<span class="keyword">nullptr</span> == asset)</div>
<div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;    {</div>
<div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;      <span class="keywordflow">return</span>;</div>
<div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;    }</div>
<div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;    lock_guard&lt;mutex&gt; lock(<a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#acb09f49cddc847f6fd8fba772519d6dc">mutex_</a>);</div>
<div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;    <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#a94bba142e59e9dc871b44a934fd94a60">assets_</a>.push_back(unique_ptr&lt;T&gt;(asset));</div>
<div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;  }</div>
<div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;<span class="keyword">private</span>:</div>
<div class="line"><a name="l00072"></a><span class="lineno"><a class="line" href="classfirestarr_1_1util_1_1MemoryPool.php#acb09f49cddc847f6fd8fba772519d6dc">   72</a></span>&#160;  <span class="keyword">mutable</span> mutex <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#acb09f49cddc847f6fd8fba772519d6dc">mutex_</a>{};</div>
<div class="line"><a name="l00076"></a><span class="lineno"><a class="line" href="classfirestarr_1_1util_1_1MemoryPool.php#a94bba142e59e9dc871b44a934fd94a60">   76</a></span>&#160;  vector&lt;unique_ptr&lt;T&gt;&gt; <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#a94bba142e59e9dc871b44a934fd94a60">assets_</a>{};</div>
<div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;};</div>
<div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;<span class="keyword">template</span> &lt;<span class="keyword">typename</span> T&gt;</div>
<div class="line"><a name="l00086"></a><span class="lineno"><a class="line" href="namespacefirestarr_1_1util.php#a6f23a72b7933be345d11f86771f22904">   86</a></span>&#160;T* <a class="code" href="namespacefirestarr_1_1util.php#a6f23a72b7933be345d11f86771f22904">check_clear</a>(T* t, <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php">MemoryPool&lt;T&gt;</a>&amp; pool)</div>
<div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;{</div>
<div class="line"><a name="l00088"></a><span class="lineno">   88</span>&#160;  <span class="keywordflow">if</span> (<span class="keyword">nullptr</span> != t)</div>
<div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;  {</div>
<div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;    t-&gt;clear();</div>
<div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;    pool.<a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#ac83590bb8563771c5609d6b146305c4e">release</a>(t);</div>
<div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;  }</div>
<div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;  <span class="keywordflow">return</span> <span class="keyword">nullptr</span>;</div>
<div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;}</div>
<div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;<span class="keyword">template</span> &lt;<span class="keyword">typename</span> T&gt;</div>
<div class="line"><a name="l00103"></a><span class="lineno"><a class="line" href="namespacefirestarr_1_1util.php#a3fc953966435ba2dba4c247032dd5e41">  103</a></span>&#160;T* <a class="code" href="namespacefirestarr_1_1util.php#a3fc953966435ba2dba4c247032dd5e41">check_reset</a>(T* t, <a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php">MemoryPool&lt;T&gt;</a>&amp; pool)</div>
<div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;{</div>
<div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;  <span class="keywordflow">if</span> (<span class="keyword">nullptr</span> != t)</div>
<div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;  {</div>
<div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;    t-&gt;reset();</div>
<div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;    pool.<a class="code" href="classfirestarr_1_1util_1_1MemoryPool.php#ac83590bb8563771c5609d6b146305c4e">release</a>(t);</div>
<div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;  }</div>
<div class="line"><a name="l00110"></a><span class="lineno">  110</span>&#160;  <span class="keywordflow">return</span> <span class="keyword">nullptr</span>;</div>
<div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;}</div>
<div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;}</div>
<div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;}</div>
<div class="ttc" id="aclassfirestarr_1_1util_1_1MemoryPool_php"><div class="ttname"><a href="classfirestarr_1_1util_1_1MemoryPool.php">firestarr::util::MemoryPool</a></div><div class="ttdoc">Keeps track of data structures so they can be reused instead of freeing and reacquiring them.</div><div class="ttdef"><b>Definition:</b> <a href="MemoryPool_8h_source.php#l00026">MemoryPool.h:27</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1util_1_1MemoryPool_php_a12a2946fbb7b73d666bcbefde8240276"><div class="ttname"><a href="classfirestarr_1_1util_1_1MemoryPool.php#a12a2946fbb7b73d666bcbefde8240276">firestarr::util::MemoryPool::operator=</a></div><div class="ttdeci">MemoryPool &amp; operator=(MemoryPool &amp;&amp;rhs)=delete</div></div>
<div class="ttc" id="aclassfirestarr_1_1util_1_1MemoryPool_php_a74352dfcdbb25b7702e6199b7bcbbdd4"><div class="ttname"><a href="classfirestarr_1_1util_1_1MemoryPool.php#a74352dfcdbb25b7702e6199b7bcbbdd4">firestarr::util::MemoryPool::MemoryPool</a></div><div class="ttdeci">MemoryPool()=default</div></div>
<div class="ttc" id="aclassfirestarr_1_1util_1_1MemoryPool_php_a91c508777b53026f670ea2c1cb6b60b8"><div class="ttname"><a href="classfirestarr_1_1util_1_1MemoryPool.php#a91c508777b53026f670ea2c1cb6b60b8">firestarr::util::MemoryPool::MemoryPool</a></div><div class="ttdeci">MemoryPool(const MemoryPool &amp;rhs)=delete</div></div>
<div class="ttc" id="aclassfirestarr_1_1util_1_1MemoryPool_php_a94bba142e59e9dc871b44a934fd94a60"><div class="ttname"><a href="classfirestarr_1_1util_1_1MemoryPool.php#a94bba142e59e9dc871b44a934fd94a60">firestarr::util::MemoryPool::assets_</a></div><div class="ttdeci">vector&lt; unique_ptr&lt; T &gt; &gt; assets_</div><div class="ttdoc">Available assets that can be acquired.</div><div class="ttdef"><b>Definition:</b> <a href="MemoryPool_8h_source.php#l00076">MemoryPool.h:76</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1util_1_1MemoryPool_php_a95419652599d39262c7aa8097f3ebb42"><div class="ttname"><a href="classfirestarr_1_1util_1_1MemoryPool.php#a95419652599d39262c7aa8097f3ebb42">firestarr::util::MemoryPool::~MemoryPool</a></div><div class="ttdeci">~MemoryPool()=default</div></div>
<div class="ttc" id="aclassfirestarr_1_1util_1_1MemoryPool_php_ac83590bb8563771c5609d6b146305c4e"><div class="ttname"><a href="classfirestarr_1_1util_1_1MemoryPool.php#ac83590bb8563771c5609d6b146305c4e">firestarr::util::MemoryPool::release</a></div><div class="ttdeci">void release(T *asset)</div><div class="ttdoc">Add a T* to the pool of available T*s.</div><div class="ttdef"><b>Definition:</b> <a href="MemoryPool_8h_source.php#l00059">MemoryPool.h:59</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1util_1_1MemoryPool_php_acb09f49cddc847f6fd8fba772519d6dc"><div class="ttname"><a href="classfirestarr_1_1util_1_1MemoryPool.php#acb09f49cddc847f6fd8fba772519d6dc">firestarr::util::MemoryPool::mutex_</a></div><div class="ttdeci">mutex mutex_</div><div class="ttdoc">Mutex for parallel access.</div><div class="ttdef"><b>Definition:</b> <a href="MemoryPool_8h_source.php#l00072">MemoryPool.h:72</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1util_1_1MemoryPool_php_acf99b34a6727535b696f3b215b7063af"><div class="ttname"><a href="classfirestarr_1_1util_1_1MemoryPool.php#acf99b34a6727535b696f3b215b7063af">firestarr::util::MemoryPool::acquire</a></div><div class="ttdeci">T * acquire()</div><div class="ttdoc">Acquire a new T either by returning an unused one or allocating a new one.</div><div class="ttdef"><b>Definition:</b> <a href="MemoryPool_8h_source.php#l00039">MemoryPool.h:39</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1util_1_1MemoryPool_php_ae5aa27002f4d92b4a12e9475dc5c8dc2"><div class="ttname"><a href="classfirestarr_1_1util_1_1MemoryPool.php#ae5aa27002f4d92b4a12e9475dc5c8dc2">firestarr::util::MemoryPool::operator=</a></div><div class="ttdeci">MemoryPool &amp; operator=(const MemoryPool &amp;rhs)=delete</div></div>
<div class="ttc" id="aclassfirestarr_1_1util_1_1MemoryPool_php_aed8df0fbea68f8ab0a95736a4e050e29"><div class="ttname"><a href="classfirestarr_1_1util_1_1MemoryPool.php#aed8df0fbea68f8ab0a95736a4e050e29">firestarr::util::MemoryPool::MemoryPool</a></div><div class="ttdeci">MemoryPool(MemoryPool &amp;&amp;rhs)=delete</div></div>
<div class="ttc" id="anamespacefirestarr_1_1util_php_a3fc953966435ba2dba4c247032dd5e41"><div class="ttname"><a href="namespacefirestarr_1_1util.php#a3fc953966435ba2dba4c247032dd5e41">firestarr::util::check_reset</a></div><div class="ttdeci">T * check_reset(T *t, MemoryPool&lt; T &gt; &amp;pool)</div><div class="ttdoc">Call reset on T before releasing it.</div><div class="ttdef"><b>Definition:</b> <a href="MemoryPool_8h_source.php#l00103">MemoryPool.h:103</a></div></div>
<div class="ttc" id="anamespacefirestarr_1_1util_php_a6f23a72b7933be345d11f86771f22904"><div class="ttname"><a href="namespacefirestarr_1_1util.php#a6f23a72b7933be345d11f86771f22904">firestarr::util::check_clear</a></div><div class="ttdeci">T * check_clear(T *t, MemoryPool&lt; T &gt; &amp;pool)</div><div class="ttdoc">Call clear on T before releasing it.</div><div class="ttdef"><b>Definition:</b> <a href="MemoryPool_8h_source.php#l00086">MemoryPool.h:86</a></div></div>
<div class="ttc" id="anamespacefirestarr_php"><div class="ttname"><a href="namespacefirestarr.php">firestarr</a></div><div class="ttdef"><b>Definition:</b> <a href="firestarr_8py_source.php#l00001">firestarr.py:1</a></div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
