<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>FireSTARR: firestarr::fuel::fbp Namespace Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">FireSTARR
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.php');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="namespacefirestarr.php">firestarr</a></li><li class="navelem"><a class="el" href="namespacefirestarr_1_1fuel.php">fuel</a></li><li class="navelem"><a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php">fbp</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">firestarr::fuel::fbp Namespace Reference</div>  </div>
</div><!--header-->
<div class="contents">
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelD1.php">FuelD1</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type D-1.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelD1.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC1.php">FuelC1</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type C-1.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC1.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php">FuelC2</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type C-2.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC2.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC3.php">FuelC3</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type C-3.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC3.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC4.php">FuelC4</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type C-4.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC4.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC5.php">FuelC5</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type C-5.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC5.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC6.php">FuelC6</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type C-6.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC6.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC7.php">FuelC7</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type C-7.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelC7.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelD2.php">FuelD2</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type D-2.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelD2.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM1.php">FuelM1</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type M-1.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM1.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM2.php">FuelM2</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type M-2.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM2.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM3.php">FuelM3</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type M-3.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM3.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM4.php">FuelM4</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type M-4.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM4.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelO1A.php">FuelO1A</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type O-1a.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelO1A.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelO1B.php">FuelO1B</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type O-1b.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelO1B.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelS1.php">FuelS1</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type S-1.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelS1.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelS2.php">FuelS2</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type S-2.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelS2.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelS3.php">FuelS3</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type S-3.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelS3.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelD1D2.php">FuelD1D2</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type D-1/D-2.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelD1D2.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM1M2.php">FuelM1M2</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type M-1/M-2.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM1M2.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM3M4.php">FuelM3M4</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">FBP fuel type M-3/M-4.  <a href="classfirestarr_1_1fuel_1_1fbp_1_1FuelM3M4.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a522eef77877da4c6554426c20d51d791"><td class="memItemLeft" align="right" valign="top">static double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php#a522eef77877da4c6554426c20d51d791">calculate_surface_fuel_consumption_c1</a> (const double ffmc) noexcept</td></tr>
<tr class="memdesc:a522eef77877da4c6554426c20d51d791"><td class="mdescLeft">&#160;</td><td class="mdescRight">Surface Fuel Consumption (SFC) (kg/m^2) [GLC-X-10 eq 9a/9b].  <a href="namespacefirestarr_1_1fuel_1_1fbp.php#a522eef77877da4c6554426c20d51d791">More...</a><br /></td></tr>
<tr class="separator:a522eef77877da4c6554426c20d51d791"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ab5a8c60cfa690c21d161304b9a22aad8"><td class="memItemLeft" align="right" valign="top">static double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php#ab5a8c60cfa690c21d161304b9a22aad8">calculate_surface_fuel_consumption_c7_ffmc</a> (const double ffmc) noexcept</td></tr>
<tr class="memdesc:ab5a8c60cfa690c21d161304b9a22aad8"><td class="mdescLeft">&#160;</td><td class="mdescRight">Forest Floor Consumption (FFC) (kg/m^2) [ST-X-3 eq 13].  <a href="namespacefirestarr_1_1fuel_1_1fbp.php#ab5a8c60cfa690c21d161304b9a22aad8">More...</a><br /></td></tr>
<tr class="separator:ab5a8c60cfa690c21d161304b9a22aad8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aefca9d0440bac0ca5a05593dc7ac3ae7"><td class="memItemLeft" align="right" valign="top">static double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php#aefca9d0440bac0ca5a05593dc7ac3ae7">calculate_surface_fuel_consumption_c7_bui</a> (const double bui) noexcept</td></tr>
<tr class="memdesc:aefca9d0440bac0ca5a05593dc7ac3ae7"><td class="mdescLeft">&#160;</td><td class="mdescRight">Woody Fuel Consumption (WFC) (kg/m^2) [ST-X-3 eq 14].  <a href="namespacefirestarr_1_1fuel_1_1fbp.php#aefca9d0440bac0ca5a05593dc7ac3ae7">More...</a><br /></td></tr>
<tr class="separator:aefca9d0440bac0ca5a05593dc7ac3ae7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aac31d594fcabfcdc7b41397f917d805f"><td class="memItemLeft" align="right" valign="top">static double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php#aac31d594fcabfcdc7b41397f917d805f">calculate_surface_fuel_consumption_d2</a> (const double bui) noexcept</td></tr>
<tr class="separator:aac31d594fcabfcdc7b41397f917d805f"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:a2165bf5053f4d2567457447170d4e0fb"><td class="memItemLeft" align="right" valign="top">static <a class="el" href="classfirestarr_1_1util_1_1LookupTable.php">LookupTable</a>&lt;&amp;<a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php#a522eef77877da4c6554426c20d51d791">calculate_surface_fuel_consumption_c1</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php#a2165bf5053f4d2567457447170d4e0fb">SURFACE_FUEL_CONSUMPTION_C1</a> {}</td></tr>
<tr class="memdesc:a2165bf5053f4d2567457447170d4e0fb"><td class="mdescLeft">&#160;</td><td class="mdescRight">Surface Fuel Consumption (SFC) (kg/m^2) [GLC-X-10 eq 9a/9b].  <a href="namespacefirestarr_1_1fuel_1_1fbp.php#a2165bf5053f4d2567457447170d4e0fb">More...</a><br /></td></tr>
<tr class="separator:a2165bf5053f4d2567457447170d4e0fb"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a81fc0576a8eecc54791f6748c3fefd0f"><td class="memItemLeft" align="right" valign="top">static <a class="el" href="classfirestarr_1_1util_1_1LookupTable.php">LookupTable</a>&lt;&amp;<a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php#ab5a8c60cfa690c21d161304b9a22aad8">calculate_surface_fuel_consumption_c7_ffmc</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php#a81fc0576a8eecc54791f6748c3fefd0f">SURFACE_FUEL_CONSUMPTION_C7_FFMC</a> {}</td></tr>
<tr class="memdesc:a81fc0576a8eecc54791f6748c3fefd0f"><td class="mdescLeft">&#160;</td><td class="mdescRight">Forest Floor Consumption (FFC) (kg/m^2) [ST-X-3 eq 13].  <a href="namespacefirestarr_1_1fuel_1_1fbp.php#a81fc0576a8eecc54791f6748c3fefd0f">More...</a><br /></td></tr>
<tr class="separator:a81fc0576a8eecc54791f6748c3fefd0f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a18298805c87843e02303bdf957858016"><td class="memItemLeft" align="right" valign="top">static <a class="el" href="classfirestarr_1_1util_1_1LookupTable.php">LookupTable</a>&lt;&amp;<a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php#aefca9d0440bac0ca5a05593dc7ac3ae7">calculate_surface_fuel_consumption_c7_bui</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php#a18298805c87843e02303bdf957858016">SURFACE_FUEL_CONSUMPTION_C7_BUI</a> {}</td></tr>
<tr class="memdesc:a18298805c87843e02303bdf957858016"><td class="mdescLeft">&#160;</td><td class="mdescRight">Woody Fuel Consumption (WFC) (kg/m^2) [ST-X-3 eq 14].  <a href="namespacefirestarr_1_1fuel_1_1fbp.php#a18298805c87843e02303bdf957858016">More...</a><br /></td></tr>
<tr class="separator:a18298805c87843e02303bdf957858016"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:acc590668f50c8052cb305bd032e9fb6e"><td class="memItemLeft" align="right" valign="top">static <a class="el" href="classfirestarr_1_1util_1_1LookupTable.php">LookupTable</a>&lt;&amp;<a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php#aac31d594fcabfcdc7b41397f917d805f">calculate_surface_fuel_consumption_d2</a> &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php#acc590668f50c8052cb305bd032e9fb6e">SURFACE_FUEL_CONSUMPTION_D2</a> {}</td></tr>
<tr class="separator:acc590668f50c8052cb305bd032e9fb6e"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Function Documentation</h2>
<a id="a522eef77877da4c6554426c20d51d791"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a522eef77877da4c6554426c20d51d791">&#9670;&nbsp;</a></span>calculate_surface_fuel_consumption_c1()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static double firestarr::fuel::fbp::calculate_surface_fuel_consumption_c1 </td>
          <td>(</td>
          <td class="paramtype">const double&#160;</td>
          <td class="paramname"><em>ffmc</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span><span class="mlabel">noexcept</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Surface Fuel Consumption (SFC) (kg/m^2) [GLC-X-10 eq 9a/9b]. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ffmc</td><td>Fine Fuel Moisture Code </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Surface Fuel Consumption (SFC) (kg/m^2) [GLC-X-10 eq 9a/9b] </dd></dl>

<p class="definition">Definition at line <a class="el" href="FBP45_8cpp_source.php#l00039">39</a> of file <a class="el" href="FBP45_8cpp_source.php">FBP45.cpp</a>.</p>

</div>
</div>
<a id="aefca9d0440bac0ca5a05593dc7ac3ae7"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aefca9d0440bac0ca5a05593dc7ac3ae7">&#9670;&nbsp;</a></span>calculate_surface_fuel_consumption_c7_bui()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static double firestarr::fuel::fbp::calculate_surface_fuel_consumption_c7_bui </td>
          <td>(</td>
          <td class="paramtype">const double&#160;</td>
          <td class="paramname"><em>bui</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span><span class="mlabel">noexcept</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Woody Fuel Consumption (WFC) (kg/m^2) [ST-X-3 eq 14]. </p>
<dl class="section return"><dt>Returns</dt><dd>Woody Fuel Consumption (WFC) (kg/m^2) [ST-X-3 eq 14] </dd></dl>

<p class="definition">Definition at line <a class="el" href="FBP45_8cpp_source.php#l00083">83</a> of file <a class="el" href="FBP45_8cpp_source.php">FBP45.cpp</a>.</p>

</div>
</div>
<a id="ab5a8c60cfa690c21d161304b9a22aad8"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ab5a8c60cfa690c21d161304b9a22aad8">&#9670;&nbsp;</a></span>calculate_surface_fuel_consumption_c7_ffmc()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static double firestarr::fuel::fbp::calculate_surface_fuel_consumption_c7_ffmc </td>
          <td>(</td>
          <td class="paramtype">const double&#160;</td>
          <td class="paramname"><em>ffmc</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span><span class="mlabel">noexcept</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Forest Floor Consumption (FFC) (kg/m^2) [ST-X-3 eq 13]. </p>
<dl class="params"><dt>Parameters</dt><dd>
  <table class="params">
    <tr><td class="paramname">ffmc</td><td>Fine Fuel Moisture Code </td></tr>
  </table>
  </dd>
</dl>
<dl class="section return"><dt>Returns</dt><dd>Forest Floor Consumption (FFC) (kg/m^2) [ST-X-3 eq 13] </dd></dl>

<p class="definition">Definition at line <a class="el" href="FBP45_8cpp_source.php#l00069">69</a> of file <a class="el" href="FBP45_8cpp_source.php">FBP45.cpp</a>.</p>

</div>
</div>
<a id="aac31d594fcabfcdc7b41397f917d805f"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aac31d594fcabfcdc7b41397f917d805f">&#9670;&nbsp;</a></span>calculate_surface_fuel_consumption_d2()</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname">static double firestarr::fuel::fbp::calculate_surface_fuel_consumption_d2 </td>
          <td>(</td>
          <td class="paramtype">const double&#160;</td>
          <td class="paramname"><em>bui</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span><span class="mlabel">noexcept</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="FBP45_8cpp_source.php#l00097">97</a> of file <a class="el" href="FBP45_8cpp_source.php">FBP45.cpp</a>.</p>

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a id="a2165bf5053f4d2567457447170d4e0fb"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a2165bf5053f4d2567457447170d4e0fb">&#9670;&nbsp;</a></span>SURFACE_FUEL_CONSUMPTION_C1</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classfirestarr_1_1util_1_1LookupTable.php">LookupTable</a>&lt;&amp;<a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php#a522eef77877da4c6554426c20d51d791">calculate_surface_fuel_consumption_c1</a>&gt; firestarr::fuel::fbp::SURFACE_FUEL_CONSUMPTION_C1 {}</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Surface Fuel Consumption (SFC) (kg/m^2) [GLC-X-10 eq 9a/9b]. </p>
<dl class="section return"><dt>Returns</dt><dd>Surface Fuel Consumption (SFC) (kg/m^2) [GLC-X-10 eq 9a/9b] </dd></dl>

<p class="definition">Definition at line <a class="el" href="FBP45_8cpp_source.php#l00048">48</a> of file <a class="el" href="FBP45_8cpp_source.php">FBP45.cpp</a>.</p>

</div>
</div>
<a id="a18298805c87843e02303bdf957858016"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a18298805c87843e02303bdf957858016">&#9670;&nbsp;</a></span>SURFACE_FUEL_CONSUMPTION_C7_BUI</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classfirestarr_1_1util_1_1LookupTable.php">LookupTable</a>&lt;&amp;<a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php#aefca9d0440bac0ca5a05593dc7ac3ae7">calculate_surface_fuel_consumption_c7_bui</a>&gt; firestarr::fuel::fbp::SURFACE_FUEL_CONSUMPTION_C7_BUI {}</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Woody Fuel Consumption (WFC) (kg/m^2) [ST-X-3 eq 14]. </p>
<dl class="section return"><dt>Returns</dt><dd>Woody Fuel Consumption (WFC) (kg/m^2) [ST-X-3 eq 14] </dd></dl>

<p class="definition">Definition at line <a class="el" href="FBP45_8cpp_source.php#l00092">92</a> of file <a class="el" href="FBP45_8cpp_source.php">FBP45.cpp</a>.</p>

</div>
</div>
<a id="a81fc0576a8eecc54791f6748c3fefd0f"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a81fc0576a8eecc54791f6748c3fefd0f">&#9670;&nbsp;</a></span>SURFACE_FUEL_CONSUMPTION_C7_FFMC</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classfirestarr_1_1util_1_1LookupTable.php">LookupTable</a>&lt;&amp;<a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php#ab5a8c60cfa690c21d161304b9a22aad8">calculate_surface_fuel_consumption_c7_ffmc</a>&gt; firestarr::fuel::fbp::SURFACE_FUEL_CONSUMPTION_C7_FFMC {}</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p>Forest Floor Consumption (FFC) (kg/m^2) [ST-X-3 eq 13]. </p>
<dl class="section return"><dt>Returns</dt><dd>Forest Floor Consumption (FFC) (kg/m^2) [ST-X-3 eq 13] </dd></dl>

<p class="definition">Definition at line <a class="el" href="FBP45_8cpp_source.php#l00078">78</a> of file <a class="el" href="FBP45_8cpp_source.php">FBP45.cpp</a>.</p>

</div>
</div>
<a id="acc590668f50c8052cb305bd032e9fb6e"></a>
<h2 class="memtitle"><span class="permalink"><a href="#acc590668f50c8052cb305bd032e9fb6e">&#9670;&nbsp;</a></span>SURFACE_FUEL_CONSUMPTION_D2</h2>

<div class="memitem">
<div class="memproto">
<table class="mlabels">
  <tr>
  <td class="mlabels-left">
      <table class="memname">
        <tr>
          <td class="memname"><a class="el" href="classfirestarr_1_1util_1_1LookupTable.php">LookupTable</a>&lt;&amp;<a class="el" href="namespacefirestarr_1_1fuel_1_1fbp.php#aac31d594fcabfcdc7b41397f917d805f">calculate_surface_fuel_consumption_d2</a>&gt; firestarr::fuel::fbp::SURFACE_FUEL_CONSUMPTION_D2 {}</td>
        </tr>
      </table>
  </td>
  <td class="mlabels-right">
<span class="mlabels"><span class="mlabel">static</span></span>  </td>
  </tr>
</table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="FBP45_8cpp_source.php#l00101">101</a> of file <a class="el" href="FBP45_8cpp_source.php">FBP45.cpp</a>.</p>

</div>
</div>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
