<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>FireSTARR: get_fgmj Namespace Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">FireSTARR
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.php');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">get_fgmj Namespace Reference</div>  </div>
</div><!--header-->
<div class="contents">
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:ab37548f75d7db35f112c22a9fd7a380c"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceget__fgmj.php#ab37548f75d7db35f112c22a9fd7a380c">getPage</a> (url)</td></tr>
<tr class="separator:ab37548f75d7db35f112c22a9fd7a380c"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:af14131bd8102b6677b92df99bfc4e100"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceget__fgmj.php#af14131bd8102b6677b92df99bfc4e100">run_fires</a> (site, region)</td></tr>
<tr class="separator:af14131bd8102b6677b92df99bfc4e100"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:ae36875b5de73af362caaf372b95df26b"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceget__fgmj.php#ae36875b5de73af362caaf372b95df26b">merge_dir</a> (dir_input)</td></tr>
<tr class="separator:ae36875b5de73af362caaf372b95df26b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a17f26388721ad74ef208ce8408263eec"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceget__fgmj.php#a17f26388721ad74ef208ce8408263eec">merge_dirs</a> (dir_input, <a class="el" href="namespaceget__fgmj.php#a0ced49cd42fc3a133fb10e4d3d6328e3">dates</a>=None)</td></tr>
<tr class="separator:a17f26388721ad74ef208ce8408263eec"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:afe6279115693adfe5b79b98ff7ab9c27"><td class="memItemLeft" align="right" valign="top">def&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceget__fgmj.php#afe6279115693adfe5b79b98ff7ab9c27">run_all_fires</a> ()</td></tr>
<tr class="separator:afe6279115693adfe5b79b98ff7ab9c27"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:ab58b204e7f02c890a6007c272620139f"><td class="memItemLeft" align="right" valign="top">string&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceget__fgmj.php#ab58b204e7f02c890a6007c272620139f">DIR</a> = '/FireGUARD/data/fgmj/'</td></tr>
<tr class="separator:ab58b204e7f02c890a6007c272620139f"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a70a5f664bb94b2f22012c2a8154acd1b"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceget__fgmj.php#a70a5f664bb94b2f22012c2a8154acd1b">EXT_DIR</a> = os.path.abspath(os.path.join(<a class="el" href="namespaceget__fgmj.php#ab58b204e7f02c890a6007c272620139f">DIR</a>, '../extracted/fgmj'))</td></tr>
<tr class="separator:a70a5f664bb94b2f22012c2a8154acd1b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:aa1ad1666be054513e10ac949375135a8"><td class="memItemLeft" align="right" valign="top">list&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceget__fgmj.php#aa1ad1666be054513e10ac949375135a8">CREATION_OPTIONS</a> = ['COMPRESS=LZW', 'TILED=YES']</td></tr>
<tr class="separator:aa1ad1666be054513e10ac949375135a8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a91028bbbd25110e32842874cde2dfcad"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceget__fgmj.php#a91028bbbd25110e32842874cde2dfcad">simtimes</a></td></tr>
<tr class="separator:a91028bbbd25110e32842874cde2dfcad"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a478676f2f52124d59030378e6dce264b"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceget__fgmj.php#a478676f2f52124d59030378e6dce264b">totaltime</a></td></tr>
<tr class="separator:a478676f2f52124d59030378e6dce264b"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a0ced49cd42fc3a133fb10e4d3d6328e3"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceget__fgmj.php#a0ced49cd42fc3a133fb10e4d3d6328e3">dates</a></td></tr>
<tr class="separator:a0ced49cd42fc3a133fb10e4d3d6328e3"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:affc735751ba46f79e5db0b23753992ee"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespaceget__fgmj.php#affc735751ba46f79e5db0b23753992ee">n</a> = len(<a class="el" href="namespaceget__fgmj.php#a91028bbbd25110e32842874cde2dfcad">simtimes</a>)</td></tr>
<tr class="separator:affc735751ba46f79e5db0b23753992ee"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Function Documentation</h2>
<a id="ab37548f75d7db35f112c22a9fd7a380c"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ab37548f75d7db35f112c22a9fd7a380c">&#9670;&nbsp;</a></span>getPage()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def get_fgmj.getPage </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>url</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="get__fgmj_8py_source.php#l00026">26</a> of file <a class="el" href="get__fgmj_8py_source.php">get_fgmj.py</a>.</p>
<div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceget__fgmj_ab37548f75d7db35f112c22a9fd7a380c_icgraph.png" border="0" usemap="#anamespaceget__fgmj_ab37548f75d7db35f112c22a9fd7a380c_icgraph" alt=""/></div>
<map name="anamespaceget__fgmj_ab37548f75d7db35f112c22a9fd7a380c_icgraph" id="anamespaceget__fgmj_ab37548f75d7db35f112c22a9fd7a380c_icgraph">
<area shape="rect" title=" " alt="" coords="369,5,492,32"/>
<area shape="rect" href="namespaceget__fgmj.php#af14131bd8102b6677b92df99bfc4e100" title=" " alt="" coords="197,5,321,32"/>
<area shape="rect" href="namespaceget__fgmj.php#afe6279115693adfe5b79b98ff7ab9c27" title=" " alt="" coords="5,5,149,32"/>
</map>
</div>

</div>
</div>
<a id="ae36875b5de73af362caaf372b95df26b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae36875b5de73af362caaf372b95df26b">&#9670;&nbsp;</a></span>merge_dir()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def get_fgmj.merge_dir </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>dir_input</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="get__fgmj_8py_source.php#l00083">83</a> of file <a class="el" href="get__fgmj_8py_source.php">get_fgmj.py</a>.</p>
<div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceget__fgmj_ae36875b5de73af362caaf372b95df26b_icgraph.png" border="0" usemap="#anamespaceget__fgmj_ae36875b5de73af362caaf372b95df26b_icgraph" alt=""/></div>
<map name="anamespaceget__fgmj_ae36875b5de73af362caaf372b95df26b_icgraph" id="anamespaceget__fgmj_ae36875b5de73af362caaf372b95df26b_icgraph">
<area shape="rect" title=" " alt="" coords="192,5,324,32"/>
<area shape="rect" href="namespaceget__fgmj.php#a17f26388721ad74ef208ce8408263eec" title=" " alt="" coords="5,5,144,32"/>
</map>
</div>

</div>
</div>
<a id="a17f26388721ad74ef208ce8408263eec"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a17f26388721ad74ef208ce8408263eec">&#9670;&nbsp;</a></span>merge_dirs()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def get_fgmj.merge_dirs </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>dir_input</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>dates</em> = <code>None</code>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="get__fgmj_8py_source.php#l00115">115</a> of file <a class="el" href="get__fgmj_8py_source.php">get_fgmj.py</a>.</p>
<div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceget__fgmj_a17f26388721ad74ef208ce8408263eec_cgraph.png" border="0" usemap="#anamespaceget__fgmj_a17f26388721ad74ef208ce8408263eec_cgraph" alt=""/></div>
<map name="anamespaceget__fgmj_a17f26388721ad74ef208ce8408263eec_cgraph" id="anamespaceget__fgmj_a17f26388721ad74ef208ce8408263eec_cgraph">
<area shape="rect" title=" " alt="" coords="5,5,144,32"/>
<area shape="rect" href="namespaceget__fgmj.php#ae36875b5de73af362caaf372b95df26b" title=" " alt="" coords="192,5,324,32"/>
</map>
</div>

</div>
</div>
<a id="afe6279115693adfe5b79b98ff7ab9c27"></a>
<h2 class="memtitle"><span class="permalink"><a href="#afe6279115693adfe5b79b98ff7ab9c27">&#9670;&nbsp;</a></span>run_all_fires()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def get_fgmj.run_all_fires </td>
          <td>(</td>
          <td class="paramname"></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="get__fgmj_8py_source.php#l00129">129</a> of file <a class="el" href="get__fgmj_8py_source.php">get_fgmj.py</a>.</p>
<div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceget__fgmj_afe6279115693adfe5b79b98ff7ab9c27_cgraph.png" border="0" usemap="#anamespaceget__fgmj_afe6279115693adfe5b79b98ff7ab9c27_cgraph" alt=""/></div>
<map name="anamespaceget__fgmj_afe6279115693adfe5b79b98ff7ab9c27_cgraph" id="anamespaceget__fgmj_afe6279115693adfe5b79b98ff7ab9c27_cgraph">
<area shape="rect" title=" " alt="" coords="5,206,149,233"/>
<area shape="rect" href="namespaceget__fgmj.php#af14131bd8102b6677b92df99bfc4e100" title=" " alt="" coords="197,206,321,233"/>
<area shape="rect" href="namespacefirestarr.php#ab05e9efc98d66338840327d32b403d69" title=" " alt="" coords="377,181,484,207"/>
<area shape="rect" href="namespaceget__fgmj.php#ab37548f75d7db35f112c22a9fd7a380c" title=" " alt="" coords="369,231,492,258"/>
<area shape="rect" href="namespacefirestarr__gis.php#ae4268a1560b326fead2944b9b0f11013" title=" " alt="" coords="551,75,681,116"/>
<area shape="rect" href="namespacefirestarr__gis.php#a3830fbe88c36fa64b1bed8fcee80ad73" title="Convert a perimeter to a raster." alt="" coords="545,140,687,181"/>
<area shape="rect" href="namespacefirestarr.php#a5cbb738c875feb8b86cedaaac5d15997" title=" " alt="" coords="559,205,673,247"/>
<area shape="rect" href="namespacefirestarr.php#a0efb0beffb72d0bc39e536b008aeec00" title=" " alt="" coords="540,271,692,298"/>
<area shape="rect" href="namespacefirestarr__gis.php#a61140139e025dae3b25e6332836a823d" title="Delete the given shapefile." alt="" coords="960,118,1089,145"/>
<area shape="rect" href="namespacefirestarr__gis.php#acf598aa5acbc2b849c100448bcf04f68" title="Find the raster with the closest meridian." alt="" coords="764,5,876,47"/>
<area shape="rect" href="namespacefirestarr__gis.php#a87e6400887f84960a937c6d0de31f179" title="Determine cell size for a raster and ensure pixels are square." alt="" coords="740,122,900,149"/>
<area shape="rect" href="namespacefirestarr__gis.php#a2d63d933a89aa5404f879689a726ed40" title="Determine spatial reference from a source file." alt="" coords="948,216,1101,257"/>
<area shape="rect" href="namespacefirestarr__gis.php#a1f002dd2296988f9ba5c7baf8341077a" title="Project to given spatial reference." alt="" coords="753,173,887,199"/>
<area shape="rect" href="namespacefirestarr__gis.php#a21927b16d626c6821a4cc0f686df9d5c" title="Convert a shapefile into a raster with the given spatial reference." alt="" coords="747,274,893,301"/>
<area shape="rect" href="namespacefirestarr__gis.php#a5795a5941584413583d73787a64b7752" title="Find the meridians of input rasters for the given year." alt="" coords="962,5,1087,47"/>
</map>
</div>

</div>
</div>
<a id="af14131bd8102b6677b92df99bfc4e100"></a>
<h2 class="memtitle"><span class="permalink"><a href="#af14131bd8102b6677b92df99bfc4e100">&#9670;&nbsp;</a></span>run_fires()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">def get_fgmj.run_fires </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>site</em>, </td>
        </tr>
        <tr>
          <td class="paramkey"></td>
          <td></td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>region</em>&#160;</td>
        </tr>
        <tr>
          <td></td>
          <td>)</td>
          <td></td><td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="get__fgmj_8py_source.php#l00033">33</a> of file <a class="el" href="get__fgmj_8py_source.php">get_fgmj.py</a>.</p>
<div class="dynheader">
Here is the call graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceget__fgmj_af14131bd8102b6677b92df99bfc4e100_cgraph.png" border="0" usemap="#anamespaceget__fgmj_af14131bd8102b6677b92df99bfc4e100_cgraph" alt=""/></div>
<map name="anamespaceget__fgmj_af14131bd8102b6677b92df99bfc4e100_cgraph" id="anamespaceget__fgmj_af14131bd8102b6677b92df99bfc4e100_cgraph">
<area shape="rect" title=" " alt="" coords="5,206,129,233"/>
<area shape="rect" href="namespacefirestarr.php#ab05e9efc98d66338840327d32b403d69" title=" " alt="" coords="185,181,292,207"/>
<area shape="rect" href="namespaceget__fgmj.php#ab37548f75d7db35f112c22a9fd7a380c" title=" " alt="" coords="177,231,300,258"/>
<area shape="rect" href="namespacefirestarr__gis.php#ae4268a1560b326fead2944b9b0f11013" title=" " alt="" coords="359,75,489,116"/>
<area shape="rect" href="namespacefirestarr__gis.php#a3830fbe88c36fa64b1bed8fcee80ad73" title="Convert a perimeter to a raster." alt="" coords="353,140,495,181"/>
<area shape="rect" href="namespacefirestarr.php#a5cbb738c875feb8b86cedaaac5d15997" title=" " alt="" coords="367,205,481,247"/>
<area shape="rect" href="namespacefirestarr.php#a0efb0beffb72d0bc39e536b008aeec00" title=" " alt="" coords="348,271,500,298"/>
<area shape="rect" href="namespacefirestarr__gis.php#a61140139e025dae3b25e6332836a823d" title="Delete the given shapefile." alt="" coords="768,118,897,145"/>
<area shape="rect" href="namespacefirestarr__gis.php#acf598aa5acbc2b849c100448bcf04f68" title="Find the raster with the closest meridian." alt="" coords="572,5,684,47"/>
<area shape="rect" href="namespacefirestarr__gis.php#a87e6400887f84960a937c6d0de31f179" title="Determine cell size for a raster and ensure pixels are square." alt="" coords="548,122,708,149"/>
<area shape="rect" href="namespacefirestarr__gis.php#a2d63d933a89aa5404f879689a726ed40" title="Determine spatial reference from a source file." alt="" coords="756,216,909,257"/>
<area shape="rect" href="namespacefirestarr__gis.php#a1f002dd2296988f9ba5c7baf8341077a" title="Project to given spatial reference." alt="" coords="561,173,695,199"/>
<area shape="rect" href="namespacefirestarr__gis.php#a21927b16d626c6821a4cc0f686df9d5c" title="Convert a shapefile into a raster with the given spatial reference." alt="" coords="555,274,701,301"/>
<area shape="rect" href="namespacefirestarr__gis.php#a5795a5941584413583d73787a64b7752" title="Find the meridians of input rasters for the given year." alt="" coords="770,5,895,47"/>
</map>
</div>
<div class="dynheader">
Here is the caller graph for this function:</div>
<div class="dyncontent">
<div class="center"><img src="namespaceget__fgmj_af14131bd8102b6677b92df99bfc4e100_icgraph.png" border="0" usemap="#anamespaceget__fgmj_af14131bd8102b6677b92df99bfc4e100_icgraph" alt=""/></div>
<map name="anamespaceget__fgmj_af14131bd8102b6677b92df99bfc4e100_icgraph" id="anamespaceget__fgmj_af14131bd8102b6677b92df99bfc4e100_icgraph">
<area shape="rect" title=" " alt="" coords="197,5,321,32"/>
<area shape="rect" href="namespaceget__fgmj.php#afe6279115693adfe5b79b98ff7ab9c27" title=" " alt="" coords="5,5,149,32"/>
</map>
</div>

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a id="aa1ad1666be054513e10ac949375135a8"></a>
<h2 class="memtitle"><span class="permalink"><a href="#aa1ad1666be054513e10ac949375135a8">&#9670;&nbsp;</a></span>CREATION_OPTIONS</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">list get_fgmj.CREATION_OPTIONS = ['COMPRESS=LZW', 'TILED=YES']</td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="get__fgmj_8py_source.php#l00024">24</a> of file <a class="el" href="get__fgmj_8py_source.php">get_fgmj.py</a>.</p>

</div>
</div>
<a id="a0ced49cd42fc3a133fb10e4d3d6328e3"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a0ced49cd42fc3a133fb10e4d3d6328e3">&#9670;&nbsp;</a></span>dates</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">get_fgmj.dates</td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="get__fgmj_8py_source.php#l00146">146</a> of file <a class="el" href="get__fgmj_8py_source.php">get_fgmj.py</a>.</p>

</div>
</div>
<a id="ab58b204e7f02c890a6007c272620139f"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ab58b204e7f02c890a6007c272620139f">&#9670;&nbsp;</a></span>DIR</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">string get_fgmj.DIR = '/FireGUARD/data/fgmj/'</td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="get__fgmj_8py_source.php#l00021">21</a> of file <a class="el" href="get__fgmj_8py_source.php">get_fgmj.py</a>.</p>

</div>
</div>
<a id="a70a5f664bb94b2f22012c2a8154acd1b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a70a5f664bb94b2f22012c2a8154acd1b">&#9670;&nbsp;</a></span>EXT_DIR</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">get_fgmj.EXT_DIR = os.path.abspath(os.path.join(<a class="el" href="namespaceget__fgmj.php#ab58b204e7f02c890a6007c272620139f">DIR</a>, '../extracted/fgmj'))</td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="get__fgmj_8py_source.php#l00022">22</a> of file <a class="el" href="get__fgmj_8py_source.php">get_fgmj.py</a>.</p>

</div>
</div>
<a id="affc735751ba46f79e5db0b23753992ee"></a>
<h2 class="memtitle"><span class="permalink"><a href="#affc735751ba46f79e5db0b23753992ee">&#9670;&nbsp;</a></span>n</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">get_fgmj.n = len(<a class="el" href="namespaceget__fgmj.php#a91028bbbd25110e32842874cde2dfcad">simtimes</a>)</td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="get__fgmj_8py_source.php#l00147">147</a> of file <a class="el" href="get__fgmj_8py_source.php">get_fgmj.py</a>.</p>

</div>
</div>
<a id="a91028bbbd25110e32842874cde2dfcad"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a91028bbbd25110e32842874cde2dfcad">&#9670;&nbsp;</a></span>simtimes</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">get_fgmj.simtimes</td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="get__fgmj_8py_source.php#l00146">146</a> of file <a class="el" href="get__fgmj_8py_source.php">get_fgmj.py</a>.</p>

</div>
</div>
<a id="a478676f2f52124d59030378e6dce264b"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a478676f2f52124d59030378e6dce264b">&#9670;&nbsp;</a></span>totaltime</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">get_fgmj.totaltime</td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="get__fgmj_8py_source.php#l00146">146</a> of file <a class="el" href="get__fgmj_8py_source.php">get_fgmj.py</a>.</p>

</div>
</div>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
