<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>FireSTARR: FireSTARR/src/Observer.h File Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">FireSTARR
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.php');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_4d88195d9c9596897c1a7e6e6c1a3b9e.php">FireSTARR</a></li><li class="navelem"><a class="el" href="dir_fee61d26c5aa45e5f9c842f18eee2357.php">src</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#nested-classes">Classes</a> &#124;
<a href="#namespaces">Namespaces</a>  </div>
  <div class="headertitle">
<div class="title">Observer.h File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &lt;memory&gt;</code><br />
<code>#include &lt;string&gt;</code><br />
<code>#include &quot;<a class="el" href="Event_8h_source.php">Event.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="GridMap_8h_source.php">GridMap.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="Scenario_8h_source.php">Scenario.h</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for Observer.h:</div>
<div class="dyncontent">
<div class="center"><img src="Observer_8h__incl.png" border="0" usemap="#aFireSTARR_2src_2Observer_8h" alt=""/></div>
<map name="aFireSTARR_2src_2Observer_8h" id="aFireSTARR_2src_2Observer_8h">
<area shape="rect" title=" " alt="" coords="2452,5,2629,32"/>
<area shape="rect" title=" " alt="" coords="2776,379,2844,405"/>
<area shape="rect" title=" " alt="" coords="2697,379,2752,405"/>
<area shape="rect" href="Event_8h.php" title=" " alt="" coords="1891,229,1956,256"/>
<area shape="rect" href="GridMap_8h.php" title=" " alt="" coords="272,229,353,256"/>
<area shape="rect" href="Scenario_8h.php" title=" " alt="" coords="2861,80,2943,107"/>
<area shape="rect" href="stdafx_8h.php" title=" " alt="" coords="1749,304,1815,331"/>
<area shape="rect" href="Cell_8h.php" title=" " alt="" coords="1111,304,1165,331"/>
<area shape="rect" title=" " alt="" coords="2116,379,2171,405"/>
<area shape="rect" title=" " alt="" coords="2195,379,2257,405"/>
<area shape="rect" title=" " alt="" coords="217,379,291,405"/>
<area shape="rect" title=" " alt="" coords="2281,379,2331,405"/>
<area shape="rect" title=" " alt="" coords="2355,379,2417,405"/>
<area shape="rect" title=" " alt="" coords="2441,379,2507,405"/>
<area shape="rect" title=" " alt="" coords="2531,379,2590,405"/>
<area shape="rect" title=" " alt="" coords="2614,379,2673,405"/>
<area shape="rect" title=" " alt="" coords="456,379,521,405"/>
<area shape="rect" title=" " alt="" coords="2868,379,2925,405"/>
<area shape="rect" title=" " alt="" coords="546,379,613,405"/>
<area shape="rect" title=" " alt="" coords="637,379,716,405"/>
<area shape="rect" title=" " alt="" coords="2949,379,3004,405"/>
<area shape="rect" title=" " alt="" coords="741,379,807,405"/>
<area shape="rect" title=" " alt="" coords="831,379,903,405"/>
<area shape="rect" title=" " alt="" coords="928,379,991,405"/>
<area shape="rect" title=" " alt="" coords="378,379,431,405"/>
<area shape="rect" title=" " alt="" coords="315,379,353,405"/>
<area shape="rect" title=" " alt="" coords="1015,379,1154,405"/>
<area shape="rect" title=" " alt="" coords="1178,379,1234,405"/>
<area shape="rect" title=" " alt="" coords="3028,379,3075,405"/>
<area shape="rect" title=" " alt="" coords="1259,379,1340,405"/>
<area shape="rect" title=" " alt="" coords="1365,379,1463,405"/>
<area shape="rect" title=" " alt="" coords="1488,379,1553,405"/>
<area shape="rect" title=" " alt="" coords="3099,379,3139,405"/>
<area shape="rect" title=" " alt="" coords="1577,379,1627,405"/>
<area shape="rect" title=" " alt="" coords="1651,379,1718,405"/>
<area shape="rect" title=" " alt="" coords="1742,379,1822,405"/>
<area shape="rect" title=" " alt="" coords="1846,379,1915,405"/>
<area shape="rect" title=" " alt="" coords="1939,379,2003,405"/>
<area shape="rect" title=" " alt="" coords="2027,379,2091,405"/>
<area shape="rect" title=" " alt="" coords="81,379,192,405"/>
<area shape="rect" title=" " alt="" coords="5,379,57,405"/>
<area shape="rect" title=" " alt="" coords="3163,379,3222,405"/>
<area shape="rect" href="Grid_8h.php" title=" " alt="" coords="471,304,527,331"/>
<area shape="rect" href="EventCompare_8h.php" title=" " alt="" coords="2103,155,2221,181"/>
<area shape="rect" href="FireWeather_8h.php" title=" " alt="" coords="3003,304,3105,331"/>
<area shape="rect" href="IntensityMap_8h.php" title=" " alt="" coords="2578,155,2685,181"/>
<area shape="rect" href="Model_8h.php" title=" " alt="" coords="2861,304,2927,331"/>
<area shape="rect" href="Settings_8h.php" title=" " alt="" coords="3234,229,3314,256"/>
<area shape="rect" href="StartPoint_8h.php" title=" " alt="" coords="3015,155,3106,181"/>
<area shape="rect" href="InnerPos_8h.php" title=" " alt="" coords="3232,155,3316,181"/>
</map>
</div>
</div><div class="textblock"><div class="dynheader">
This graph shows which files directly or indirectly include this file:</div>
<div class="dyncontent">
<div class="center"><img src="Observer_8h__dep__incl.png" border="0" usemap="#aFireSTARR_2src_2Observer_8hdep" alt=""/></div>
<map name="aFireSTARR_2src_2Observer_8hdep" id="aFireSTARR_2src_2Observer_8hdep">
<area shape="rect" title=" " alt="" coords="317,5,494,32"/>
<area shape="rect" href="Model_8cpp.php" title=" " alt="" coords="5,80,179,107"/>
<area shape="rect" href="Observer_8cpp.php" title=" " alt="" coords="203,80,394,107"/>
<area shape="rect" href="Scenario_8cpp.php" title=" " alt="" coords="419,80,608,107"/>
<area shape="rect" href="Test_8cpp.php" title=" " alt="" coords="633,80,797,107"/>
</map>
</div>
</div>
<p><a href="Observer_8h_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="nested-classes"></a>
Classes</h2></td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1sim_1_1IObserver.php">firestarr::sim::IObserver</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">Interface for observers that get notified when cells burn so they can track things.  <a href="classfirestarr_1_1sim_1_1IObserver.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1sim_1_1MapObserver.php">firestarr::sim::MapObserver&lt; T &gt;</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">An <a class="el" href="classfirestarr_1_1sim_1_1IObserver.php" title="Interface for observers that get notified when cells burn so they can track things.">IObserver</a> that tracks notification data using a GridMap.  <a href="classfirestarr_1_1sim_1_1MapObserver.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1sim_1_1ArrivalObserver.php">firestarr::sim::ArrivalObserver</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">Tracks when fire initially arrives in a Cell.  <a href="classfirestarr_1_1sim_1_1ArrivalObserver.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1sim_1_1SourceObserver.php">firestarr::sim::SourceObserver</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">Tracks source Cell that fire arrived in Cell from.  <a href="classfirestarr_1_1sim_1_1SourceObserver.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:"><td class="memItemLeft" align="right" valign="top">class &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="classfirestarr_1_1sim_1_1IntensityObserver.php">firestarr::sim::IntensityObserver</a></td></tr>
<tr class="memdesc:"><td class="mdescLeft">&#160;</td><td class="mdescRight">Tracks the intensity that Cells burn at.  <a href="classfirestarr_1_1sim_1_1IntensityObserver.php#details">More...</a><br /></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:namespacefirestarr"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr.php">firestarr</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:namespacefirestarr_1_1sim"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1sim.php">firestarr::sim</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
