<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>FireSTARR: FireSTARR/src/Perimeter.cpp Source File</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">FireSTARR
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.php');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_4d88195d9c9596897c1a7e6e6c1a3b9e.php">FireSTARR</a></li><li class="navelem"><a class="el" href="dir_fee61d26c5aa45e5f9c842f18eee2357.php">src</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="headertitle">
<div class="title">Perimeter.cpp</div>  </div>
</div><!--header-->
<div class="contents">
<a href="Perimeter_8cpp.php">Go to the documentation of this file.</a><div class="fragment"><div class="line"><a name="l00001"></a><span class="lineno">    1</span>&#160;<span class="comment">// Copyright (c) 2020-2021, Queen&#39;s Printer for Ontario.</span></div>
<div class="line"><a name="l00002"></a><span class="lineno">    2</span>&#160;<span class="comment">//</span></div>
<div class="line"><a name="l00003"></a><span class="lineno">    3</span>&#160;<span class="comment">// This program is free software: you can redistribute it and/or modify</span></div>
<div class="line"><a name="l00004"></a><span class="lineno">    4</span>&#160;<span class="comment">// it under the terms of the GNU Affero General Public License as</span></div>
<div class="line"><a name="l00005"></a><span class="lineno">    5</span>&#160;<span class="comment">// published by the Free Software Foundation, either version 3 of the</span></div>
<div class="line"><a name="l00006"></a><span class="lineno">    6</span>&#160;<span class="comment">// License, or (at your option) any later version.</span></div>
<div class="line"><a name="l00007"></a><span class="lineno">    7</span>&#160;<span class="comment">//</span></div>
<div class="line"><a name="l00008"></a><span class="lineno">    8</span>&#160;<span class="comment">// This program is distributed in the hope that it will be useful,</span></div>
<div class="line"><a name="l00009"></a><span class="lineno">    9</span>&#160;<span class="comment">// but WITHOUT ANY WARRANTY; without even the implied warranty of</span></div>
<div class="line"><a name="l00010"></a><span class="lineno">   10</span>&#160;<span class="comment">// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the</span></div>
<div class="line"><a name="l00011"></a><span class="lineno">   11</span>&#160;<span class="comment">// GNU Affero General Public License for more details.</span></div>
<div class="line"><a name="l00012"></a><span class="lineno">   12</span>&#160;<span class="comment">//</span></div>
<div class="line"><a name="l00013"></a><span class="lineno">   13</span>&#160;<span class="comment">// You should have received a copy of the GNU Affero General Public License</span></div>
<div class="line"><a name="l00014"></a><span class="lineno">   14</span>&#160;<span class="comment">// along with this program.  If not, see &lt;https://www.gnu.org/licenses/&gt;.</span></div>
<div class="line"><a name="l00015"></a><span class="lineno">   15</span>&#160; </div>
<div class="line"><a name="l00016"></a><span class="lineno">   16</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="stdafx_8h.php">stdafx.h</a>&quot;</span></div>
<div class="line"><a name="l00017"></a><span class="lineno">   17</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="Perimeter_8h.php">Perimeter.h</a>&quot;</span></div>
<div class="line"><a name="l00018"></a><span class="lineno">   18</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="Environment_8h.php">Environment.h</a>&quot;</span></div>
<div class="line"><a name="l00019"></a><span class="lineno">   19</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="FuelLookup_8h.php">FuelLookup.h</a>&quot;</span></div>
<div class="line"><a name="l00020"></a><span class="lineno">   20</span>&#160;<span class="preprocessor">#include &quot;<a class="code" href="GridMap_8h.php">GridMap.h</a>&quot;</span></div>
<div class="line"><a name="l00021"></a><span class="lineno">   21</span>&#160;<span class="keyword">namespace </span><a class="code" href="namespacefirestarr_1_1topo.php">firestarr::topo</a></div>
<div class="line"><a name="l00022"></a><span class="lineno">   22</span>&#160;{</div>
<div class="line"><a name="l00026"></a><span class="lineno"><a class="line" href="classfirestarr_1_1topo_1_1BurnedMap.php">   26</a></span>&#160;<span class="keyword">class </span><a class="code" href="classfirestarr_1_1topo_1_1BurnedMap.php">BurnedMap</a> final</div>
<div class="line"><a name="l00027"></a><span class="lineno">   27</span>&#160;  : <span class="keyword">public</span> <a class="code" href="classfirestarr_1_1data_1_1GridMap.php">data::GridMap</a>&lt;unsigned char&gt;</div>
<div class="line"><a name="l00028"></a><span class="lineno">   28</span>&#160;{</div>
<div class="line"><a name="l00029"></a><span class="lineno">   29</span>&#160;<span class="keyword">public</span>:</div>
<div class="line"><a name="l00030"></a><span class="lineno">   30</span>&#160;  <span class="comment">// implement this class so that we can filter by fuel cells but not expose the members</span></div>
<div class="line"><a name="l00036"></a><span class="lineno"><a class="line" href="classfirestarr_1_1topo_1_1BurnedMap.php#a8775fc310860e0203977d750d96beab4">   36</a></span>&#160;<span class="comment"></span>  <a class="code" href="classfirestarr_1_1topo_1_1BurnedMap.php#a8775fc310860e0203977d750d96beab4">BurnedMap</a>(<span class="keyword">const</span> Grid&lt;unsigned char, unsigned char&gt;&amp; perim_grid, <span class="keyword">const</span> <a class="code" href="classfirestarr_1_1topo_1_1Environment.php">Environment</a>&amp; env)</div>
<div class="line"><a name="l00037"></a><span class="lineno">   37</span>&#160;    : <a class="code" href="classfirestarr_1_1data_1_1GridMap.php#a35d4cbc327c24295c246b8c37a9d2ed1">GridMap</a>&lt;unsigned char, unsigned char&gt;(</div>
<div class="line"><a name="l00038"></a><span class="lineno">   38</span>&#160;      *env.makeMap&lt;unsigned char&gt;(static_cast&lt;unsigned char&gt;(0)))</div>
<div class="line"><a name="l00039"></a><span class="lineno">   39</span>&#160;  {</div>
<div class="line"><a name="l00040"></a><span class="lineno">   40</span>&#160;    <span class="comment">// HACK: fix offset if the perimeter raster is different from this one</span></div>
<div class="line"><a name="l00041"></a><span class="lineno">   41</span>&#160;    <a class="code" href="namespacefirestarr_1_1logging.php#a7ecc8a94d5ffa708b378cfa37e8d4fe5">logging::check_fatal</a>(0 != strcmp(perim_grid.proj4().c_str(), this-&gt;proj4().c_str()),</div>
<div class="line"><a name="l00042"></a><span class="lineno">   42</span>&#160;                         <span class="stringliteral">&quot;Invalid projection for input perimeter raster - %s instead of %s&quot;</span>,</div>
<div class="line"><a name="l00043"></a><span class="lineno">   43</span>&#160;                         perim_grid.proj4().c_str(),</div>
<div class="line"><a name="l00044"></a><span class="lineno">   44</span>&#160;                         this-&gt;proj4().c_str());</div>
<div class="line"><a name="l00045"></a><span class="lineno">   45</span>&#160;    <a class="code" href="namespacefirestarr_1_1logging.php#a7ecc8a94d5ffa708b378cfa37e8d4fe5">logging::check_fatal</a>(perim_grid.cellSize() != this-&gt;cellSize(),</div>
<div class="line"><a name="l00046"></a><span class="lineno">   46</span>&#160;                         <span class="stringliteral">&quot;Invalid cell size for input perimeter raster - %f instead of %f&quot;</span>,</div>
<div class="line"><a name="l00047"></a><span class="lineno">   47</span>&#160;                         perim_grid.cellSize(),</div>
<div class="line"><a name="l00048"></a><span class="lineno">   48</span>&#160;                         this-&gt;cellSize());</div>
<div class="line"><a name="l00049"></a><span class="lineno">   49</span>&#160;    <span class="keyword">const</span> <span class="keyword">auto</span> offset_x = <span class="keyword">static_cast&lt;</span><a class="code" href="namespacefirestarr.php#a5202984444b8e149a7a00fc1fee9410e">Idx</a><span class="keyword">&gt;</span>((this-&gt;<a class="code" href="classfirestarr_1_1data_1_1GridBase.php#a453cd4c17e6e1a030f308378ce384100">xllcorner</a>() - perim_grid.xllcorner()) / this-&gt;<a class="code" href="classfirestarr_1_1data_1_1GridBase.php#a607fcdf301c03fabfa2cdff549a8ab90">cellSize</a>());</div>
<div class="line"><a name="l00050"></a><span class="lineno">   50</span>&#160;    <span class="keyword">const</span> <span class="keyword">auto</span> perim_origin = <span class="keyword">static_cast&lt;</span><a class="code" href="namespacefirestarr.php#a5202984444b8e149a7a00fc1fee9410e">Idx</a><span class="keyword">&gt;</span>(perim_grid.rows() + perim_grid.yllcorner() / this-&gt;<a class="code" href="classfirestarr_1_1data_1_1GridBase.php#a607fcdf301c03fabfa2cdff549a8ab90">cellSize</a>());</div>
<div class="line"><a name="l00051"></a><span class="lineno">   51</span>&#160;    <span class="keyword">const</span> <span class="keyword">auto</span> this_origin = <span class="keyword">static_cast&lt;</span><a class="code" href="namespacefirestarr.php#a5202984444b8e149a7a00fc1fee9410e">Idx</a><span class="keyword">&gt;</span>(this-&gt;<a class="code" href="classfirestarr_1_1data_1_1GridBase.php#ab4265834a03aa8678bc1af3906fb181d">rows</a>() + this-&gt;<a class="code" href="classfirestarr_1_1data_1_1GridBase.php#ada6e7b58b4d58418c6b29674a017c00b">yllcorner</a>() / this-&gt;<a class="code" href="classfirestarr_1_1data_1_1GridBase.php#a607fcdf301c03fabfa2cdff549a8ab90">cellSize</a>());</div>
<div class="line"><a name="l00052"></a><span class="lineno">   52</span>&#160;    <span class="keyword">const</span> <span class="keyword">auto</span> offset_y = <span class="keyword">static_cast&lt;</span><a class="code" href="namespacefirestarr.php#a5202984444b8e149a7a00fc1fee9410e">Idx</a><span class="keyword">&gt;</span>((perim_origin - this_origin));</div>
<div class="line"><a name="l00053"></a><span class="lineno">   53</span>&#160;    <span class="comment">// make sure we don&#39;t go out of bounds on grid</span></div>
<div class="line"><a name="l00054"></a><span class="lineno">   54</span>&#160;    <span class="keyword">const</span> <span class="keyword">auto</span> min_column = <span class="keyword">static_cast&lt;</span><a class="code" href="namespacefirestarr.php#a5202984444b8e149a7a00fc1fee9410e">Idx</a><span class="keyword">&gt;</span>(offset_x &lt; 0 ? abs(offset_x) : 0);</div>
<div class="line"><a name="l00055"></a><span class="lineno">   55</span>&#160;    <span class="keyword">const</span> <span class="keyword">auto</span> max_columns = min(this-&gt;<a class="code" href="classfirestarr_1_1data_1_1GridBase.php#ac5befea8588c3302924f74c2b3f37537">columns</a>(), perim_grid.columns());</div>
<div class="line"><a name="l00056"></a><span class="lineno">   56</span>&#160;    <span class="keyword">const</span> <span class="keyword">auto</span> min_row = <span class="keyword">static_cast&lt;</span><a class="code" href="namespacefirestarr.php#a5202984444b8e149a7a00fc1fee9410e">Idx</a><span class="keyword">&gt;</span>(offset_y &lt; 0 ? abs(offset_y) : 0);</div>
<div class="line"><a name="l00057"></a><span class="lineno">   57</span>&#160;    <span class="keyword">const</span> <span class="keyword">auto</span> max_rows = min(this-&gt;<a class="code" href="classfirestarr_1_1data_1_1GridBase.php#ab4265834a03aa8678bc1af3906fb181d">rows</a>(),</div>
<div class="line"><a name="l00058"></a><span class="lineno">   58</span>&#160;                              <span class="keyword">static_cast&lt;</span><a class="code" href="namespacefirestarr.php#a5202984444b8e149a7a00fc1fee9410e">Idx</a><span class="keyword">&gt;</span>(perim_grid.rows() - abs(offset_y)));</div>
<div class="line"><a name="l00059"></a><span class="lineno">   59</span>&#160;    <a class="code" href="namespacefirestarr_1_1logging.php#a0ce472ba500e288fc9ddce4fe754ff9a">logging::note</a>(<span class="stringliteral">&quot;Correcting perimeter raster offset by %dx%d cells&quot;</span>,</div>
<div class="line"><a name="l00060"></a><span class="lineno">   60</span>&#160;                  offset_x,</div>
<div class="line"><a name="l00061"></a><span class="lineno">   61</span>&#160;                  offset_y);</div>
<div class="line"><a name="l00062"></a><span class="lineno">   62</span>&#160;    <span class="keywordtype">size_t</span> count = 0;</div>
<div class="line"><a name="l00063"></a><span class="lineno">   63</span>&#160;    <span class="comment">// since it was read in as a vector we need to check all the cells</span></div>
<div class="line"><a name="l00064"></a><span class="lineno">   64</span>&#160;    <span class="keywordflow">for</span> (<span class="keyword">auto</span> r = min_row; r &lt; max_rows; ++r)</div>
<div class="line"><a name="l00065"></a><span class="lineno">   65</span>&#160;    {</div>
<div class="line"><a name="l00066"></a><span class="lineno">   66</span>&#160;      <span class="keywordflow">for</span> (<span class="keyword">auto</span> c = min_column; c &lt; max_columns; ++c)</div>
<div class="line"><a name="l00067"></a><span class="lineno">   67</span>&#160;      {</div>
<div class="line"><a name="l00068"></a><span class="lineno">   68</span>&#160;        <span class="keyword">const</span> <span class="keyword">auto</span> loc = env.<a class="code" href="classfirestarr_1_1topo_1_1Environment.php#a63fb262bd6d79947b40c24a1c413e173">cell</a>(r, c);</div>
<div class="line"><a name="l00069"></a><span class="lineno">   69</span>&#160;        <span class="keyword">const</span> <a class="code" href="classfirestarr_1_1topo_1_1Location.php">Location</a> fixed_loc(<span class="keyword">static_cast&lt;</span><a class="code" href="namespacefirestarr.php#a5202984444b8e149a7a00fc1fee9410e">Idx</a><span class="keyword">&gt;</span>(r + offset_y),</div>
<div class="line"><a name="l00070"></a><span class="lineno">   70</span>&#160;                                 <span class="keyword">static_cast&lt;</span><a class="code" href="namespacefirestarr.php#a5202984444b8e149a7a00fc1fee9410e">Idx</a><span class="keyword">&gt;</span>(c + offset_x));</div>
<div class="line"><a name="l00071"></a><span class="lineno">   71</span>&#160;        <span class="keyword">const</span> <span class="keyword">auto</span> value = perim_grid.at(fixed_loc);</div>
<div class="line"><a name="l00072"></a><span class="lineno">   72</span>&#160;        <span class="keywordflow">if</span> (value != perim_grid.noData() &amp;&amp; !<a class="code" href="namespacefirestarr_1_1fuel.php#aa4ed31c7956cc53b1e796260fe176c42">fuel::is_null_fuel</a>(loc))</div>
<div class="line"><a name="l00073"></a><span class="lineno">   73</span>&#160;        {</div>
<div class="line"><a name="l00074"></a><span class="lineno">   74</span>&#160;          this-&gt;GridMap&lt;unsigned char, unsigned char&gt;::set(loc, value);</div>
<div class="line"><a name="l00075"></a><span class="lineno">   75</span>&#160;          ++count;</div>
<div class="line"><a name="l00076"></a><span class="lineno">   76</span>&#160;        }</div>
<div class="line"><a name="l00077"></a><span class="lineno">   77</span>&#160;      }</div>
<div class="line"><a name="l00078"></a><span class="lineno">   78</span>&#160;    }</div>
<div class="line"><a name="l00079"></a><span class="lineno">   79</span>&#160;    <span class="keywordflow">for</span> (<span class="keyword">auto</span>&amp; kv : <a class="code" href="classfirestarr_1_1data_1_1GridData.php#a6e672182a1321a0ad69f312e4025c013">data</a>)</div>
<div class="line"><a name="l00080"></a><span class="lineno">   80</span>&#160;    {</div>
<div class="line"><a name="l00081"></a><span class="lineno">   81</span>&#160;      <a class="code" href="namespacefirestarr_1_1logging.php#a7ecc8a94d5ffa708b378cfa37e8d4fe5">logging::check_fatal</a>(<a class="code" href="namespacefirestarr_1_1fuel.php#aa4ed31c7956cc53b1e796260fe176c42">fuel::is_null_fuel</a>(env.<a class="code" href="classfirestarr_1_1topo_1_1Environment.php#a63fb262bd6d79947b40c24a1c413e173">cell</a>(kv.first)),</div>
<div class="line"><a name="l00082"></a><span class="lineno">   82</span>&#160;                           <span class="stringliteral">&quot;Null fuel in BurnedData&quot;</span>);</div>
<div class="line"><a name="l00083"></a><span class="lineno">   83</span>&#160;    }</div>
<div class="line"><a name="l00084"></a><span class="lineno">   84</span>&#160;    <a class="code" href="namespacefirestarr_1_1logging.php#ae505e6144c4c8127c9870e1dfa81039b">logging::info</a>(<span class="stringliteral">&quot;Loaded burned area of size %lu ha&quot;</span>,</div>
<div class="line"><a name="l00085"></a><span class="lineno">   85</span>&#160;                  <span class="keyword">static_cast&lt;</span><span class="keywordtype">size_t</span><span class="keyword">&gt;</span>(this-&gt;<a class="code" href="classfirestarr_1_1data_1_1GridBase.php#a607fcdf301c03fabfa2cdff549a8ab90">cellSize</a>() / 100.0 * count));</div>
<div class="line"><a name="l00086"></a><span class="lineno">   86</span>&#160;  }</div>
<div class="line"><a name="l00087"></a><span class="lineno">   87</span>&#160;};</div>
<div class="line"><a name="l00088"></a><span class="lineno"><a class="line" href="classfirestarr_1_1topo_1_1Perimeter.php#a68c886bbc16e8a8434668c3f2a1ba63f">   88</a></span>&#160;<a class="code" href="classfirestarr_1_1topo_1_1Perimeter.php#a68c886bbc16e8a8434668c3f2a1ba63f">Perimeter::Perimeter</a>(<span class="keyword">const</span> <span class="keywordtype">string</span>&amp; perim, <span class="keyword">const</span> <a class="code" href="classfirestarr_1_1topo_1_1Point.php">Point</a>&amp; point, <span class="keyword">const</span> <a class="code" href="classfirestarr_1_1topo_1_1Environment.php">Environment</a>&amp; env)</div>
<div class="line"><a name="l00089"></a><span class="lineno">   89</span>&#160;{</div>
<div class="line"><a name="l00090"></a><span class="lineno">   90</span>&#160;  <span class="keyword">const</span> <span class="keyword">auto</span> perim_grid = unique_ptr&lt;data::ConstantGrid&lt;unsigned char&gt;&gt;(</div>
<div class="line"><a name="l00091"></a><span class="lineno">   91</span>&#160;    <a class="code" href="classfirestarr_1_1data_1_1ConstantGrid.php#acb83ad8fd5645c39fd501c1f361bed8b">data::ConstantGrid&lt;unsigned char&gt;::readTiff</a>(perim, point));</div>
<div class="line"><a name="l00092"></a><span class="lineno">   92</span>&#160;  <span class="keyword">const</span> <a class="code" href="classfirestarr_1_1topo_1_1BurnedMap.php">BurnedMap</a> <a class="code" href="classfirestarr_1_1topo_1_1Perimeter.php#a575fb50a392fcc55ac64059cc05a8f59">burned</a>(*perim_grid, env);</div>
<div class="line"><a name="l00093"></a><span class="lineno">   93</span>&#160;  <a class="code" href="classfirestarr_1_1topo_1_1Perimeter.php#a429e06071a25ffed512fae57f683636d">burned_</a> = <a class="code" href="classfirestarr_1_1topo_1_1Perimeter.php#a575fb50a392fcc55ac64059cc05a8f59">burned</a>.makeList();</div>
<div class="line"><a name="l00094"></a><span class="lineno">   94</span>&#160;  <a class="code" href="classfirestarr_1_1topo_1_1Perimeter.php#aca0d81a6aa55598c63131771cec4862f">edge_</a> = <a class="code" href="classfirestarr_1_1topo_1_1Perimeter.php#a575fb50a392fcc55ac64059cc05a8f59">burned</a>.makeEdge();</div>
<div class="line"><a name="l00095"></a><span class="lineno">   95</span>&#160;  <span class="keywordflow">for</span> (<span class="keyword">auto</span> c : <a class="code" href="classfirestarr_1_1topo_1_1Perimeter.php#aca0d81a6aa55598c63131771cec4862f">edge_</a>)</div>
<div class="line"><a name="l00096"></a><span class="lineno">   96</span>&#160;  {</div>
<div class="line"><a name="l00097"></a><span class="lineno">   97</span>&#160;    <a class="code" href="namespacefirestarr_1_1logging.php#a7ecc8a94d5ffa708b378cfa37e8d4fe5">logging::check_fatal</a>(<a class="code" href="namespacefirestarr_1_1fuel.php#aa4ed31c7956cc53b1e796260fe176c42">fuel::is_null_fuel</a>(env.<a class="code" href="classfirestarr_1_1topo_1_1Environment.php#a63fb262bd6d79947b40c24a1c413e173">cell</a>(c)), <span class="stringliteral">&quot;Null fuel in perimeter edge&quot;</span>);</div>
<div class="line"><a name="l00098"></a><span class="lineno">   98</span>&#160;  }</div>
<div class="line"><a name="l00099"></a><span class="lineno">   99</span>&#160;}</div>
<div class="line"><a name="l00100"></a><span class="lineno"><a class="line" href="classfirestarr_1_1topo_1_1Perimeter.php#a9f31a946f932f6eea85bc1f936bfbe95">  100</a></span>&#160;<a class="code" href="classfirestarr_1_1topo_1_1Perimeter.php#a68c886bbc16e8a8434668c3f2a1ba63f">Perimeter::Perimeter</a>(<span class="keyword">const</span> <a class="code" href="classfirestarr_1_1topo_1_1Location.php">Location</a>&amp; location,</div>
<div class="line"><a name="l00101"></a><span class="lineno">  101</span>&#160;                     <span class="keyword">const</span> <span class="keywordtype">size_t</span> size,</div>
<div class="line"><a name="l00102"></a><span class="lineno">  102</span>&#160;                     <span class="keyword">const</span> <a class="code" href="classfirestarr_1_1wx_1_1FwiWeather.php">wx::FwiWeather</a>&amp;,</div>
<div class="line"><a name="l00103"></a><span class="lineno">  103</span>&#160;                     <span class="keyword">const</span> <a class="code" href="classfirestarr_1_1topo_1_1Environment.php">Environment</a>&amp; env)</div>
<div class="line"><a name="l00104"></a><span class="lineno">  104</span>&#160;{</div>
<div class="line"><a name="l00105"></a><span class="lineno">  105</span>&#160;  <span class="comment">// NOTE: FwiWeather is unused but could change this to try doing length to breadth ratio</span></div>
<div class="line"><a name="l00106"></a><span class="lineno">  106</span>&#160;  <span class="keyword">auto</span> perim_grid = env.<a class="code" href="classfirestarr_1_1topo_1_1Environment.php#a6e7d77e073c425d72ae865065856734c">makeMap</a>&lt;<span class="keywordtype">unsigned</span> <span class="keywordtype">char</span>&gt;(0);</div>
<div class="line"><a name="l00107"></a><span class="lineno">  107</span>&#160;  <span class="comment">// want to find cells in the area that fill up the size we&#39;re looking for</span></div>
<div class="line"><a name="l00108"></a><span class="lineno">  108</span>&#160;  <span class="keywordtype">size_t</span> count = 0;</div>
<div class="line"><a name="l00109"></a><span class="lineno">  109</span>&#160;  <span class="comment">// convert into number of cells</span></div>
<div class="line"><a name="l00110"></a><span class="lineno">  110</span>&#160;  <span class="keyword">const</span> <span class="keyword">auto</span> num_cells = size / (100.0 * 100.0 / (perim_grid-&gt;cellSize() * perim_grid-&gt;cellSize()));</div>
<div class="line"><a name="l00111"></a><span class="lineno">  111</span>&#160;  <span class="keyword">auto</span> max_distance = sqrt(num_cells / M_PI);</div>
<div class="line"><a name="l00112"></a><span class="lineno">  112</span>&#160;  perim_grid-&gt;set(location, 1);</div>
<div class="line"><a name="l00113"></a><span class="lineno">  113</span>&#160;  ++count;</div>
<div class="line"><a name="l00114"></a><span class="lineno">  114</span>&#160;  <span class="comment">// HACK: assume fuel for origin matches the rest of the fire</span></div>
<div class="line"><a name="l00115"></a><span class="lineno">  115</span>&#160;  <span class="keywordflow">while</span> (num_cells &gt; count)</div>
<div class="line"><a name="l00116"></a><span class="lineno">  116</span>&#160;  {</div>
<div class="line"><a name="l00117"></a><span class="lineno">  117</span>&#160;    <span class="keyword">const</span> <span class="keyword">auto</span> range = <span class="keyword">static_cast&lt;</span><a class="code" href="namespacefirestarr.php#a5202984444b8e149a7a00fc1fee9410e">Idx</a><span class="keyword">&gt;</span>(ceil(max_distance));</div>
<div class="line"><a name="l00118"></a><span class="lineno">  118</span>&#160;    <span class="keywordflow">for</span> (<span class="keyword">auto</span> x = -range; x &lt;= range &amp;&amp; num_cells &gt; count; ++x)</div>
<div class="line"><a name="l00119"></a><span class="lineno">  119</span>&#160;    {</div>
<div class="line"><a name="l00120"></a><span class="lineno">  120</span>&#160;      <span class="keywordflow">for</span> (<span class="keyword">auto</span> y = -range; y &lt;= range &amp;&amp; num_cells &gt; count; ++y)</div>
<div class="line"><a name="l00121"></a><span class="lineno">  121</span>&#160;      {</div>
<div class="line"><a name="l00122"></a><span class="lineno">  122</span>&#160;        <span class="comment">// look at any cell that&#39;s within the range</span></div>
<div class="line"><a name="l00123"></a><span class="lineno">  123</span>&#160;        <span class="keywordflow">if</span> (sqrt(util::pow_int&lt;2&gt;(x) + util::pow_int&lt;2&gt;(y)) &lt; max_distance)</div>
<div class="line"><a name="l00124"></a><span class="lineno">  124</span>&#160;        {</div>
<div class="line"><a name="l00125"></a><span class="lineno">  125</span>&#160;          <span class="keyword">const</span> <span class="keyword">auto</span> r = <span class="keyword">static_cast&lt;</span><a class="code" href="namespacefirestarr.php#a5202984444b8e149a7a00fc1fee9410e">Idx</a><span class="keyword">&gt;</span>(location.<a class="code" href="classfirestarr_1_1topo_1_1Location.php#a95eede212209b6a602433b821a265984">row</a>() + x);</div>
<div class="line"><a name="l00126"></a><span class="lineno">  126</span>&#160;          <span class="keyword">const</span> <span class="keyword">auto</span> c = <span class="keyword">static_cast&lt;</span><a class="code" href="namespacefirestarr.php#a5202984444b8e149a7a00fc1fee9410e">Idx</a><span class="keyword">&gt;</span>(location.<a class="code" href="classfirestarr_1_1topo_1_1Location.php#abe02c2fea1338a8351aead94a074cefe">column</a>() + y);</div>
<div class="line"><a name="l00127"></a><span class="lineno">  127</span>&#160;          <span class="keyword">const</span> <span class="keyword">auto</span> loc = env.<a class="code" href="classfirestarr_1_1topo_1_1Environment.php#a63fb262bd6d79947b40c24a1c413e173">cell</a>(r, c);</div>
<div class="line"><a name="l00128"></a><span class="lineno">  128</span>&#160;          <span class="keywordflow">if</span> (1 != perim_grid-&gt;at(loc) &amp;&amp; !<a class="code" href="namespacefirestarr_1_1fuel.php#aa4ed31c7956cc53b1e796260fe176c42">fuel::is_null_fuel</a>(loc))</div>
<div class="line"><a name="l00129"></a><span class="lineno">  129</span>&#160;          {</div>
<div class="line"><a name="l00130"></a><span class="lineno">  130</span>&#160;            perim_grid-&gt;set(loc, 1);</div>
<div class="line"><a name="l00131"></a><span class="lineno">  131</span>&#160;            ++count;</div>
<div class="line"><a name="l00132"></a><span class="lineno">  132</span>&#160;          }</div>
<div class="line"><a name="l00133"></a><span class="lineno">  133</span>&#160;        }</div>
<div class="line"><a name="l00134"></a><span class="lineno">  134</span>&#160;      }</div>
<div class="line"><a name="l00135"></a><span class="lineno">  135</span>&#160;    }</div>
<div class="line"><a name="l00136"></a><span class="lineno">  136</span>&#160;    max_distance += 0.1;</div>
<div class="line"><a name="l00137"></a><span class="lineno">  137</span>&#160;  }</div>
<div class="line"><a name="l00138"></a><span class="lineno">  138</span>&#160;  <span class="keyword">const</span> <a class="code" href="classfirestarr_1_1topo_1_1BurnedMap.php">BurnedMap</a> <a class="code" href="classfirestarr_1_1topo_1_1Perimeter.php#a575fb50a392fcc55ac64059cc05a8f59">burned</a>(*perim_grid, env);</div>
<div class="line"><a name="l00139"></a><span class="lineno">  139</span>&#160;  <a class="code" href="classfirestarr_1_1topo_1_1Perimeter.php#a429e06071a25ffed512fae57f683636d">burned_</a> = <a class="code" href="classfirestarr_1_1topo_1_1Perimeter.php#a575fb50a392fcc55ac64059cc05a8f59">burned</a>.makeList();</div>
<div class="line"><a name="l00140"></a><span class="lineno">  140</span>&#160;  <a class="code" href="classfirestarr_1_1topo_1_1Perimeter.php#aca0d81a6aa55598c63131771cec4862f">edge_</a> = <a class="code" href="classfirestarr_1_1topo_1_1Perimeter.php#a575fb50a392fcc55ac64059cc05a8f59">burned</a>.makeEdge();</div>
<div class="line"><a name="l00141"></a><span class="lineno">  141</span>&#160;}</div>
<div class="line"><a name="l00142"></a><span class="lineno"><a class="line" href="classfirestarr_1_1topo_1_1Perimeter.php#a575fb50a392fcc55ac64059cc05a8f59">  142</a></span>&#160;[[nodiscard]] <span class="keyword">const</span> list&lt;Location&gt;&amp; <a class="code" href="classfirestarr_1_1topo_1_1Perimeter.php#a575fb50a392fcc55ac64059cc05a8f59">Perimeter::burned</a>() const noexcept</div>
<div class="line"><a name="l00143"></a><span class="lineno">  143</span>&#160;{</div>
<div class="line"><a name="l00144"></a><span class="lineno">  144</span>&#160;  <span class="keywordflow">return</span> <a class="code" href="classfirestarr_1_1topo_1_1Perimeter.php#a429e06071a25ffed512fae57f683636d">burned_</a>;</div>
<div class="line"><a name="l00145"></a><span class="lineno">  145</span>&#160;}</div>
<div class="line"><a name="l00146"></a><span class="lineno"><a class="line" href="classfirestarr_1_1topo_1_1Perimeter.php#af6c22392bb8ad690229078a23bc4adc2">  146</a></span>&#160;[[nodiscard]] <span class="keyword">const</span> list&lt;Location&gt;&amp; <a class="code" href="classfirestarr_1_1topo_1_1Perimeter.php#af6c22392bb8ad690229078a23bc4adc2">Perimeter::edge</a>() const noexcept</div>
<div class="line"><a name="l00147"></a><span class="lineno">  147</span>&#160;{</div>
<div class="line"><a name="l00148"></a><span class="lineno">  148</span>&#160;  <span class="keywordflow">return</span> <a class="code" href="classfirestarr_1_1topo_1_1Perimeter.php#aca0d81a6aa55598c63131771cec4862f">edge_</a>;</div>
<div class="line"><a name="l00149"></a><span class="lineno">  149</span>&#160;}</div>
<div class="line"><a name="l00150"></a><span class="lineno">  150</span>&#160;}</div>
<div class="ttc" id="aEnvironment_8h_php"><div class="ttname"><a href="Environment_8h.php">Environment.h</a></div></div>
<div class="ttc" id="aFuelLookup_8h_php"><div class="ttname"><a href="FuelLookup_8h.php">FuelLookup.h</a></div></div>
<div class="ttc" id="aGridMap_8h_php"><div class="ttname"><a href="GridMap_8h.php">GridMap.h</a></div></div>
<div class="ttc" id="aPerimeter_8h_php"><div class="ttname"><a href="Perimeter_8h.php">Perimeter.h</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1data_1_1ConstantGrid_php_acb83ad8fd5645c39fd501c1f361bed8b"><div class="ttname"><a href="classfirestarr_1_1data_1_1ConstantGrid.php#acb83ad8fd5645c39fd501c1f361bed8b">firestarr::data::ConstantGrid::readTiff</a></div><div class="ttdeci">static ConstantGrid&lt; T, V &gt; * readTiff(const string &amp;filename, TIFF *tif, GTIF *gtif, const topo::Point &amp;point, std::function&lt; T(int, int)&gt; convert)</div><div class="ttdoc">Read a section of a TIFF into a ConstantGrid.</div><div class="ttdef"><b>Definition:</b> <a href="ConstantGrid_8h_source.php#l00143">ConstantGrid.h:143</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1data_1_1GridBase_php_a453cd4c17e6e1a030f308378ce384100"><div class="ttname"><a href="classfirestarr_1_1data_1_1GridBase.php#a453cd4c17e6e1a030f308378ce384100">firestarr::data::GridBase::xllcorner</a></div><div class="ttdeci">constexpr double xllcorner() const noexcept</div><div class="ttdoc">Lower left corner X coordinate in meters.</div><div class="ttdef"><b>Definition:</b> <a href="Grid_8h_source.php#l00112">Grid.h:112</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1data_1_1GridBase_php_a607fcdf301c03fabfa2cdff549a8ab90"><div class="ttname"><a href="classfirestarr_1_1data_1_1GridBase.php#a607fcdf301c03fabfa2cdff549a8ab90">firestarr::data::GridBase::cellSize</a></div><div class="ttdeci">constexpr double cellSize() const noexcept</div><div class="ttdoc">Cell size used for GridBase.</div><div class="ttdef"><b>Definition:</b> <a href="Grid_8h_source.php#l00080">Grid.h:80</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1data_1_1GridBase_php_ab4265834a03aa8678bc1af3906fb181d"><div class="ttname"><a href="classfirestarr_1_1data_1_1GridBase.php#ab4265834a03aa8678bc1af3906fb181d">firestarr::data::GridBase::rows</a></div><div class="ttdeci">constexpr Idx rows() const noexcept</div><div class="ttdoc">Number of rows in the GridBase.</div><div class="ttdef"><b>Definition:</b> <a href="Grid_8h_source.php#l00088">Grid.h:88</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1data_1_1GridBase_php_ac5befea8588c3302924f74c2b3f37537"><div class="ttname"><a href="classfirestarr_1_1data_1_1GridBase.php#ac5befea8588c3302924f74c2b3f37537">firestarr::data::GridBase::columns</a></div><div class="ttdeci">constexpr Idx columns() const noexcept</div><div class="ttdoc">Number of columns in the GridBase.</div><div class="ttdef"><b>Definition:</b> <a href="Grid_8h_source.php#l00096">Grid.h:96</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1data_1_1GridBase_php_ada6e7b58b4d58418c6b29674a017c00b"><div class="ttname"><a href="classfirestarr_1_1data_1_1GridBase.php#ada6e7b58b4d58418c6b29674a017c00b">firestarr::data::GridBase::yllcorner</a></div><div class="ttdeci">constexpr double yllcorner() const noexcept</div><div class="ttdoc">Lower left corner Y coordinate in meters.</div><div class="ttdef"><b>Definition:</b> <a href="Grid_8h_source.php#l00120">Grid.h:120</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1data_1_1GridData_php_a6e672182a1321a0ad69f312e4025c013"><div class="ttname"><a href="classfirestarr_1_1data_1_1GridData.php#a6e672182a1321a0ad69f312e4025c013">firestarr::data::GridData::data</a></div><div class="ttdeci">D data</div><div class="ttdoc">Structure that holds data represented by this GridData.</div><div class="ttdef"><b>Definition:</b> <a href="Grid_8h_source.php#l00408">Grid.h:408</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1data_1_1GridMap_php"><div class="ttname"><a href="classfirestarr_1_1data_1_1GridMap.php">firestarr::data::GridMap</a></div><div class="ttdoc">A GridData that uses an unordered_map for storage.</div><div class="ttdef"><b>Definition:</b> <a href="GridMap_8h_source.php#l00034">GridMap.h:36</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1data_1_1GridMap_php_a35d4cbc327c24295c246b8c37a9d2ed1"><div class="ttname"><a href="classfirestarr_1_1data_1_1GridMap.php#a35d4cbc327c24295c246b8c37a9d2ed1">firestarr::data::GridMap&lt; unsigned char &gt;::GridMap</a></div><div class="ttdeci">GridMap(const double cell_size, const Idx rows, const Idx columns, unsigned char no_data, const int nodata, const double xllcorner, const double yllcorner, string &amp;&amp;proj4)</div><div class="ttdoc">Constructor.</div><div class="ttdef"><b>Definition:</b> <a href="GridMap_8h_source.php#l00091">GridMap.h:91</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1topo_1_1BurnedMap_php"><div class="ttname"><a href="classfirestarr_1_1topo_1_1BurnedMap.php">firestarr::topo::BurnedMap</a></div><div class="ttdoc">A map of locations which have burned in a Scenario.</div><div class="ttdef"><b>Definition:</b> <a href="Perimeter_8cpp_source.php#l00026">Perimeter.cpp:28</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1topo_1_1BurnedMap_php_a8775fc310860e0203977d750d96beab4"><div class="ttname"><a href="classfirestarr_1_1topo_1_1BurnedMap.php#a8775fc310860e0203977d750d96beab4">firestarr::topo::BurnedMap::BurnedMap</a></div><div class="ttdeci">BurnedMap(const Grid&lt; unsigned char, unsigned char &gt; &amp;perim_grid, const Environment &amp;env)</div><div class="ttdoc">Constructor.</div><div class="ttdef"><b>Definition:</b> <a href="Perimeter_8cpp_source.php#l00036">Perimeter.cpp:36</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1topo_1_1Environment_php"><div class="ttname"><a href="classfirestarr_1_1topo_1_1Environment.php">firestarr::topo::Environment</a></div><div class="ttdoc">The area that a Model is run for, with Fuel, Slope, and Aspect grids.</div><div class="ttdef"><b>Definition:</b> <a href="Environment_8h_source.php#l00041">Environment.h:42</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1topo_1_1Environment_php_a63fb262bd6d79947b40c24a1c413e173"><div class="ttname"><a href="classfirestarr_1_1topo_1_1Environment.php#a63fb262bd6d79947b40c24a1c413e173">firestarr::topo::Environment::cell</a></div><div class="ttdeci">constexpr Cell cell(const Idx row, const Idx column) const</div><div class="ttdoc">Cell at given row and column.</div><div class="ttdef"><b>Definition:</b> <a href="Environment_8h_source.php#l00152">Environment.h:152</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1topo_1_1Environment_php_a6e7d77e073c425d72ae865065856734c"><div class="ttname"><a href="classfirestarr_1_1topo_1_1Environment.php#a6e7d77e073c425d72ae865065856734c">firestarr::topo::Environment::makeMap</a></div><div class="ttdeci">unique_ptr&lt; data::GridMap&lt; Other &gt; &gt; makeMap(const Other nodata) const</div><div class="ttdoc">Create a GridMap&lt;Other&gt; covering this Environment.</div><div class="ttdef"><b>Definition:</b> <a href="Environment_8h_source.php#l00213">Environment.h:213</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1topo_1_1Location_php"><div class="ttname"><a href="classfirestarr_1_1topo_1_1Location.php">firestarr::topo::Location</a></div><div class="ttdoc">A location with a row and column.</div><div class="ttdef"><b>Definition:</b> <a href="Location_8h_source.php#l00025">Location.h:26</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1topo_1_1Location_php_a95eede212209b6a602433b821a265984"><div class="ttname"><a href="classfirestarr_1_1topo_1_1Location.php#a95eede212209b6a602433b821a265984">firestarr::topo::Location::row</a></div><div class="ttdeci">constexpr Idx row() const noexcept</div><div class="ttdoc">Row.</div><div class="ttdef"><b>Definition:</b> <a href="Location_8h_source.php#l00050">Location.h:50</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1topo_1_1Location_php_abe02c2fea1338a8351aead94a074cefe"><div class="ttname"><a href="classfirestarr_1_1topo_1_1Location.php#abe02c2fea1338a8351aead94a074cefe">firestarr::topo::Location::column</a></div><div class="ttdeci">constexpr Idx column() const noexcept</div><div class="ttdoc">Column.</div><div class="ttdef"><b>Definition:</b> <a href="Location_8h_source.php#l00058">Location.h:58</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1topo_1_1Perimeter_php_a429e06071a25ffed512fae57f683636d"><div class="ttname"><a href="classfirestarr_1_1topo_1_1Perimeter.php#a429e06071a25ffed512fae57f683636d">firestarr::topo::Perimeter::burned_</a></div><div class="ttdeci">list&lt; Location &gt; burned_</div><div class="ttdoc">List of all burned Locations.</div><div class="ttdef"><b>Definition:</b> <a href="Perimeter_8h_source.php#l00068">Perimeter.h:68</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1topo_1_1Perimeter_php_a575fb50a392fcc55ac64059cc05a8f59"><div class="ttname"><a href="classfirestarr_1_1topo_1_1Perimeter.php#a575fb50a392fcc55ac64059cc05a8f59">firestarr::topo::Perimeter::burned</a></div><div class="ttdeci">const list&lt; Location &gt; &amp; burned() const noexcept</div><div class="ttdoc">List of all burned Locations.</div><div class="ttdef"><b>Definition:</b> <a href="Perimeter_8cpp_source.php#l00142">Perimeter.cpp:142</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1topo_1_1Perimeter_php_a68c886bbc16e8a8434668c3f2a1ba63f"><div class="ttname"><a href="classfirestarr_1_1topo_1_1Perimeter.php#a68c886bbc16e8a8434668c3f2a1ba63f">firestarr::topo::Perimeter::Perimeter</a></div><div class="ttdeci">Perimeter(const string &amp;perim, const Point &amp;point, const Environment &amp;env)</div><div class="ttdoc">Initialize perimeter from a file.</div><div class="ttdef"><b>Definition:</b> <a href="Perimeter_8cpp_source.php#l00088">Perimeter.cpp:88</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1topo_1_1Perimeter_php_aca0d81a6aa55598c63131771cec4862f"><div class="ttname"><a href="classfirestarr_1_1topo_1_1Perimeter.php#aca0d81a6aa55598c63131771cec4862f">firestarr::topo::Perimeter::edge_</a></div><div class="ttdeci">list&lt; Location &gt; edge_</div><div class="ttdoc">List of all Locations along the edge of this Perimeter.</div><div class="ttdef"><b>Definition:</b> <a href="Perimeter_8h_source.php#l00072">Perimeter.h:72</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1topo_1_1Perimeter_php_af6c22392bb8ad690229078a23bc4adc2"><div class="ttname"><a href="classfirestarr_1_1topo_1_1Perimeter.php#af6c22392bb8ad690229078a23bc4adc2">firestarr::topo::Perimeter::edge</a></div><div class="ttdeci">const list&lt; Location &gt; &amp; edge() const noexcept</div><div class="ttdoc">List of all Locations along the edge of this Perimeter.</div><div class="ttdef"><b>Definition:</b> <a href="Perimeter_8cpp_source.php#l00146">Perimeter.cpp:146</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1topo_1_1Point_php"><div class="ttname"><a href="classfirestarr_1_1topo_1_1Point.php">firestarr::topo::Point</a></div><div class="ttdoc">A geographic location in lat/long coordinates.</div><div class="ttdef"><b>Definition:</b> <a href="Point_8h_source.php#l00024">Point.h:25</a></div></div>
<div class="ttc" id="aclassfirestarr_1_1wx_1_1FwiWeather_php"><div class="ttname"><a href="classfirestarr_1_1wx_1_1FwiWeather.php">firestarr::wx::FwiWeather</a></div><div class="ttdoc">A Weather value with calculated FWI indices.</div><div class="ttdef"><b>Definition:</b> <a href="FWI_8h_source.php#l00212">FWI.h:214</a></div></div>
<div class="ttc" id="anamespacefirestarr_1_1fuel_php_aa4ed31c7956cc53b1e796260fe176c42"><div class="ttname"><a href="namespacefirestarr_1_1fuel.php#aa4ed31c7956cc53b1e796260fe176c42">firestarr::fuel::is_null_fuel</a></div><div class="ttdeci">constexpr bool is_null_fuel(const topo::Cell &amp;cell)</div><div class="ttdoc">Whether or not there is no fuel in the Cell.</div><div class="ttdef"><b>Definition:</b> <a href="FuelLookup_8h_source.php#l00121">FuelLookup.h:121</a></div></div>
<div class="ttc" id="anamespacefirestarr_1_1logging_php_a0ce472ba500e288fc9ddce4fe754ff9a"><div class="ttname"><a href="namespacefirestarr_1_1logging.php#a0ce472ba500e288fc9ddce4fe754ff9a">firestarr::logging::note</a></div><div class="ttdeci">void note(const char *format,...) noexcept</div><div class="ttdoc">Log with NOTE level.</div><div class="ttdef"><b>Definition:</b> <a href="Log_8cpp_source.php#l00100">Log.cpp:100</a></div></div>
<div class="ttc" id="anamespacefirestarr_1_1logging_php_a7ecc8a94d5ffa708b378cfa37e8d4fe5"><div class="ttname"><a href="namespacefirestarr_1_1logging.php#a7ecc8a94d5ffa708b378cfa37e8d4fe5">firestarr::logging::check_fatal</a></div><div class="ttdeci">void check_fatal(const bool condition, const char *format, va_list *args) noexcept</div><div class="ttdef"><b>Definition:</b> <a href="Log_8cpp_source.php#l00143">Log.cpp:143</a></div></div>
<div class="ttc" id="anamespacefirestarr_1_1logging_php_ae505e6144c4c8127c9870e1dfa81039b"><div class="ttname"><a href="namespacefirestarr_1_1logging.php#ae505e6144c4c8127c9870e1dfa81039b">firestarr::logging::info</a></div><div class="ttdeci">void info(const char *format,...) noexcept</div><div class="ttdoc">Log with INFO level.</div><div class="ttdef"><b>Definition:</b> <a href="Log_8cpp_source.php#l00090">Log.cpp:90</a></div></div>
<div class="ttc" id="anamespacefirestarr_1_1topo_php"><div class="ttname"><a href="namespacefirestarr_1_1topo.php">firestarr::topo</a></div><div class="ttdef"><b>Definition:</b> <a href="Cell_8h_source.php#l00022">Cell.h:23</a></div></div>
<div class="ttc" id="anamespacefirestarr_php_a5202984444b8e149a7a00fc1fee9410e"><div class="ttname"><a href="namespacefirestarr.php#a5202984444b8e149a7a00fc1fee9410e">firestarr::Idx</a></div><div class="ttdeci">int16 Idx</div><div class="ttdoc">A row or column index for a grid.</div><div class="ttdef"><b>Definition:</b> <a href="stdafx_8h_source.php#l00148">stdafx.h:148</a></div></div>
<div class="ttc" id="astdafx_8h_php"><div class="ttname"><a href="stdafx_8h.php">stdafx.h</a></div></div>
</div><!-- fragment --></div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
