<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>FireSTARR: FireSTARR/src/StartPoint.cpp File Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">FireSTARR
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.php');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_4d88195d9c9596897c1a7e6e6c1a3b9e.php">FireSTARR</a></li><li class="navelem"><a class="el" href="dir_fee61d26c5aa45e5f9c842f18eee2357.php">src</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#namespaces">Namespaces</a> &#124;
<a href="#func-members">Functions</a>  </div>
  <div class="headertitle">
<div class="title">StartPoint.cpp File Reference</div>  </div>
</div><!--header-->
<div class="contents">
<div class="textblock"><code>#include &quot;<a class="el" href="stdafx_8h_source.php">stdafx.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="StartPoint_8h_source.php">StartPoint.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="Settings_8h_source.php">Settings.h</a>&quot;</code><br />
<code>#include &quot;<a class="el" href="Util_8h_source.php">Util.h</a>&quot;</code><br />
</div><div class="textblock"><div class="dynheader">
Include dependency graph for StartPoint.cpp:</div>
<div class="dyncontent">
<div class="center"><img src="StartPoint_8cpp__incl.png" border="0" usemap="#aFireSTARR_2src_2StartPoint_8cpp" alt=""/></div>
<map name="aFireSTARR_2src_2StartPoint_8cpp" id="aFireSTARR_2src_2StartPoint_8cpp">
<area shape="rect" title=" " alt="" coords="3909,5,4105,32"/>
<area shape="rect" href="stdafx_8h.php" title=" " alt="" coords="2210,155,2277,181"/>
<area shape="rect" href="StartPoint_8h.php" title=" " alt="" coords="4166,80,4257,107"/>
<area shape="rect" href="Settings_8h.php" title=" " alt="" coords="4098,155,4178,181"/>
<area shape="rect" href="Util_8h.php" title=" " alt="" coords="3949,80,4001,107"/>
<area shape="rect" title=" " alt="" coords="2780,229,2835,256"/>
<area shape="rect" title=" " alt="" coords="2859,229,2921,256"/>
<area shape="rect" title=" " alt="" coords="2945,229,3019,256"/>
<area shape="rect" title=" " alt="" coords="3043,229,3094,256"/>
<area shape="rect" title=" " alt="" coords="3118,229,3179,256"/>
<area shape="rect" title=" " alt="" coords="3204,229,3269,256"/>
<area shape="rect" title=" " alt="" coords="3294,229,3353,256"/>
<area shape="rect" title=" " alt="" coords="3377,229,3435,256"/>
<area shape="rect" title=" " alt="" coords="3460,229,3525,256"/>
<area shape="rect" title=" " alt="" coords="3549,229,3607,256"/>
<area shape="rect" title=" " alt="" coords="3631,229,3698,256"/>
<area shape="rect" title=" " alt="" coords="3723,229,3801,256"/>
<area shape="rect" title=" " alt="" coords="5,229,60,256"/>
<area shape="rect" title=" " alt="" coords="85,229,151,256"/>
<area shape="rect" title=" " alt="" coords="175,229,247,256"/>
<area shape="rect" title=" " alt="" coords="272,229,335,256"/>
<area shape="rect" title=" " alt="" coords="359,229,413,256"/>
<area shape="rect" title=" " alt="" coords="437,229,476,256"/>
<area shape="rect" title=" " alt="" coords="501,229,639,256"/>
<area shape="rect" title=" " alt="" coords="663,229,719,256"/>
<area shape="rect" title=" " alt="" coords="744,229,791,256"/>
<area shape="rect" title=" " alt="" coords="815,229,883,256"/>
<area shape="rect" title=" " alt="" coords="907,229,988,256"/>
<area shape="rect" title=" " alt="" coords="1013,229,1111,256"/>
<area shape="rect" title=" " alt="" coords="1136,229,1201,256"/>
<area shape="rect" title=" " alt="" coords="1225,229,1265,256"/>
<area shape="rect" title=" " alt="" coords="1289,229,1339,256"/>
<area shape="rect" title=" " alt="" coords="1363,229,1430,256"/>
<area shape="rect" title=" " alt="" coords="1454,229,1534,256"/>
<area shape="rect" title=" " alt="" coords="1558,229,1627,256"/>
<area shape="rect" title=" " alt="" coords="1651,229,1715,256"/>
<area shape="rect" title=" " alt="" coords="3825,229,3880,256"/>
<area shape="rect" title=" " alt="" coords="1739,229,1803,256"/>
<area shape="rect" title=" " alt="" coords="1827,229,1915,256"/>
<area shape="rect" title=" " alt="" coords="3904,229,4015,256"/>
<area shape="rect" title=" " alt="" coords="4039,229,4091,256"/>
<area shape="rect" title=" " alt="" coords="4115,229,4174,256"/>
<area shape="rect" title=" " alt="" coords="1939,229,2094,256"/>
<area shape="rect" title=" " alt="" coords="2118,229,2225,256"/>
<area shape="rect" title=" " alt="" coords="2249,229,2379,256"/>
<area shape="rect" title=" " alt="" coords="2404,229,2451,256"/>
<area shape="rect" title=" " alt="" coords="2475,229,2529,256"/>
<area shape="rect" title=" " alt="" coords="2553,229,2653,256"/>
<area shape="rect" title=" " alt="" coords="2677,229,2756,256"/>
<area shape="rect" title=" " alt="" coords="4202,155,4253,181"/>
</map>
</div>
</div>
<p><a href="StartPoint_8cpp_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="namespaces"></a>
Namespaces</h2></td></tr>
<tr class="memitem:namespacefirestarr"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr.php">firestarr</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:namespacefirestarr_1_1topo"><td class="memItemLeft" align="right" valign="top"> &#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1topo.php">firestarr::topo</a></td></tr>
<tr class="separator:"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:a930c2160fca19f1a495f2281e409f794"><td class="memTemplParams" colspan="2">template&lt;typename T &gt; </td></tr>
<tr class="memitem:a930c2160fca19f1a495f2281e409f794"><td class="memTemplItemLeft" align="right" valign="top">static T&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1topo.php#a930c2160fca19f1a495f2281e409f794">firestarr::topo::fix_range</a> (T value, T min_value, T max_value) noexcept</td></tr>
<tr class="separator:a930c2160fca19f1a495f2281e409f794"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a49475fec1712a1d137f5374e9000b0a7"><td class="memTemplParams" colspan="2">template&lt;typename T &gt; </td></tr>
<tr class="memitem:a49475fec1712a1d137f5374e9000b0a7"><td class="memTemplItemLeft" align="right" valign="top">static T&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1topo.php#a49475fec1712a1d137f5374e9000b0a7">firestarr::topo::fix_degrees</a> (T value) noexcept</td></tr>
<tr class="separator:a49475fec1712a1d137f5374e9000b0a7"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a5f05233dc6917eb1c2eafb376d4d2276"><td class="memTemplParams" colspan="2">template&lt;typename T &gt; </td></tr>
<tr class="memitem:a5f05233dc6917eb1c2eafb376d4d2276"><td class="memTemplItemLeft" align="right" valign="top">static T&#160;</td><td class="memTemplItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1topo.php#a5f05233dc6917eb1c2eafb376d4d2276">firestarr::topo::fix_hours</a> (T value) noexcept</td></tr>
<tr class="separator:a5f05233dc6917eb1c2eafb376d4d2276"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a323235b777c91f207111a24b1bb6d2c8"><td class="memItemLeft" align="right" valign="top">static double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1topo.php#a323235b777c91f207111a24b1bb6d2c8">firestarr::topo::sunrise_sunset</a> (const int jd, const double latitude, const double longitude, const bool for_sunrise) noexcept</td></tr>
<tr class="separator:a323235b777c91f207111a24b1bb6d2c8"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a3016776d2dc0cd5aedcb619d094629a1"><td class="memItemLeft" align="right" valign="top">static double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1topo.php#a3016776d2dc0cd5aedcb619d094629a1">firestarr::topo::sunrise</a> (const int jd, const double latitude, const double longitude) noexcept</td></tr>
<tr class="separator:a3016776d2dc0cd5aedcb619d094629a1"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a518930bc272c0d4b5a4d9aa57ebdd9ff"><td class="memItemLeft" align="right" valign="top">static double&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1topo.php#a518930bc272c0d4b5a4d9aa57ebdd9ff">firestarr::topo::sunset</a> (const int jd, const double latitude, const double longitude) noexcept</td></tr>
<tr class="separator:a518930bc272c0d4b5a4d9aa57ebdd9ff"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:a625dffb14b1c034629a62175af5467d5"><td class="memItemLeft" align="right" valign="top">static array&lt; tuple&lt; double, double &gt;, MAX_DAYS &gt;&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="namespacefirestarr_1_1topo.php#a625dffb14b1c034629a62175af5467d5">firestarr::topo::make_days</a> (const double latitude, const double longitude) noexcept</td></tr>
<tr class="separator:a625dffb14b1c034629a62175af5467d5"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
