<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=9"/>
<meta name="generator" content="Doxygen 1.9.1"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>WeatherSHIELD: WeatherSHIELD/gui/firestarr/index.php File Reference</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="dynsections.js"></script>
<link href="search/search.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="search/searchdata.js"></script>
<script type="text/javascript" src="search/search.js"></script>
<link href="doxygen.css" rel="stylesheet" type="text/css" />
</head>
<body>
<div id="top"><!-- do not remove this div, it is closed by doxygen! -->
<div id="titlearea">
<table cellspacing="0" cellpadding="0">
 <tbody>
 <tr style="height: 56px;">
  <td id="projectalign" style="padding-left: 0.5em;">
   <div id="projectname">WeatherSHIELD
   </div>
  </td>
 </tr>
 </tbody>
</table>
</div>
<!-- end header part -->
<!-- Generated by Doxygen 1.9.1 -->
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
var searchBox = new SearchBox("searchBox", "search",false,'Search','.php');
/* @license-end */
</script>
<script type="text/javascript" src="menudata.js"></script>
<script type="text/javascript" src="menu.js"></script>
<script type="text/javascript">
/* @license magnet:?xt=urn:btih:cf05388f2679ee054f2beb29a391d25f4e673ac3&amp;dn=gpl-2.0.txt GPL-v2 */
$(function() {
  initMenu('',true,false,'search.php','Search');
  $(document).ready(function() { init_search(); });
});
/* @license-end */</script>
<div id="main-nav"></div>
<!-- window showing the filter options -->
<div id="MSearchSelectWindow"
     onmouseover="return searchBox.OnSearchSelectShow()"
     onmouseout="return searchBox.OnSearchSelectHide()"
     onkeydown="return searchBox.OnSearchSelectKey(event)">
</div>

<!-- iframe showing the search results (closed by default) -->
<div id="MSearchResultsWindow">
<iframe src="javascript:void(0)" frameborder="0" 
        name="MSearchResults" id="MSearchResults">
</iframe>
</div>

<div id="nav-path" class="navpath">
  <ul>
<li class="navelem"><a class="el" href="dir_efb9b02d96da17fe24d2757b77512e9c.php">WeatherSHIELD</a></li><li class="navelem"><a class="el" href="dir_5fc6f6a3a11d95919a5ab1ab667a4c80.php">gui</a></li><li class="navelem"><a class="el" href="dir_32dff87057e452ac0b7554cb953eb0a2.php">firestarr</a></li>  </ul>
</div>
</div><!-- top -->
<div class="header">
  <div class="summary">
<a href="#func-members">Functions</a> &#124;
<a href="#var-members">Variables</a>  </div>
  <div class="headertitle">
<div class="title">index.php File Reference</div>  </div>
</div><!--header-->
<div class="contents">

<p><a href="firestarr_2index_8php_source.php">Go to the source code of this file.</a></p>
<table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="func-members"></a>
Functions</h2></td></tr>
<tr class="memitem:ae0899f18eb7c111fda0c8b5ea1c0f214"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="firestarr_2index_8php.php#ae0899f18eb7c111fda0c8b5ea1c0f214">listdir</a> ($dir)</td></tr>
<tr class="separator:ae0899f18eb7c111fda0c8b5ea1c0f214"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table><table class="memberdecls">
<tr class="heading"><td colspan="2"><h2 class="groupheader"><a name="var-members"></a>
Variables</h2></td></tr>
<tr class="memitem:a1e42906f7e81b68b33fc7ca9b36a2748"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="firestarr_2index_8php.php#a1e42906f7e81b68b33fc7ca9b36a2748">$ROOT_DIR</a> = '/app/data/output/'</td></tr>
<tr class="separator:a1e42906f7e81b68b33fc7ca9b36a2748"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:abb48f7c83753ddd42467c47693d024cf"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="firestarr_2index_8php.php#abb48f7c83753ddd42467c47693d024cf">$PERIM_DIR</a> = $ROOT_DIR.'perimeter/'</td></tr>
<tr class="separator:abb48f7c83753ddd42467c47693d024cf"><td class="memSeparator" colspan="2">&#160;</td></tr>
<tr class="memitem:adaf36fef4479504eb91934435d643288"><td class="memItemLeft" align="right" valign="top">&#160;</td><td class="memItemRight" valign="bottom"><a class="el" href="firestarr_2index_8php.php#adaf36fef4479504eb91934435d643288">$PROB_DIR</a> = $ROOT_DIR.'probability/'</td></tr>
<tr class="separator:adaf36fef4479504eb91934435d643288"><td class="memSeparator" colspan="2">&#160;</td></tr>
</table>
<h2 class="groupheader">Function Documentation</h2>
<a id="ae0899f18eb7c111fda0c8b5ea1c0f214"></a>
<h2 class="memtitle"><span class="permalink"><a href="#ae0899f18eb7c111fda0c8b5ea1c0f214">&#9670;&nbsp;</a></span>listdir()</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">listdir </td>
          <td>(</td>
          <td class="paramtype">&#160;</td>
          <td class="paramname"><em>$dir</em></td><td>)</td>
          <td></td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="firestarr_2index_8php_source.php#l00032">32</a> of file <a class="el" href="firestarr_2index_8php_source.php">index.php</a>.</p>

</div>
</div>
<h2 class="groupheader">Variable Documentation</h2>
<a id="abb48f7c83753ddd42467c47693d024cf"></a>
<h2 class="memtitle"><span class="permalink"><a href="#abb48f7c83753ddd42467c47693d024cf">&#9670;&nbsp;</a></span>$PERIM_DIR</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">$PERIM_DIR = $ROOT_DIR.'perimeter/'</td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="firestarr_2index_8php_source.php#l00030">30</a> of file <a class="el" href="firestarr_2index_8php_source.php">index.php</a>.</p>

</div>
</div>
<a id="adaf36fef4479504eb91934435d643288"></a>
<h2 class="memtitle"><span class="permalink"><a href="#adaf36fef4479504eb91934435d643288">&#9670;&nbsp;</a></span>$PROB_DIR</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">$PROB_DIR = $ROOT_DIR.'probability/'</td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="firestarr_2index_8php_source.php#l00031">31</a> of file <a class="el" href="firestarr_2index_8php_source.php">index.php</a>.</p>

</div>
</div>
<a id="a1e42906f7e81b68b33fc7ca9b36a2748"></a>
<h2 class="memtitle"><span class="permalink"><a href="#a1e42906f7e81b68b33fc7ca9b36a2748">&#9670;&nbsp;</a></span>$ROOT_DIR</h2>

<div class="memitem">
<div class="memproto">
      <table class="memname">
        <tr>
          <td class="memname">$ROOT_DIR = '/app/data/output/'</td>
        </tr>
      </table>
</div><div class="memdoc">

<p class="definition">Definition at line <a class="el" href="firestarr_2index_8php_source.php#l00029">29</a> of file <a class="el" href="firestarr_2index_8php_source.php">index.php</a>.</p>

</div>
</div>
</div><!-- contents -->
<!-- start footer part -->
<hr class="footer"/><address class="footer"><small>
Generated by&#160;<a href="https://www.doxygen.org/index.html"><img class="footer" src="doxygen.svg" width="104" height="31" alt="doxygen"/></a> 1.9.1
</small></address>
</body>
</html>
